# Generated by Django 5.2.7 on 2025-11-04 03:00

from django.db import migrations, models


def normalize_status_values(apps, schema_editor):
    BlogPost = apps.get_model("blog", "BlogPost")
    replacements = {
        "0": "draft",
        "1": "published",
        0: "draft",
        1: "published",
    }
    for source, target in replacements.items():
        BlogPost.objects.filter(status=source).update(status=target)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.RunPython(normalize_status_values, migrations.RunPython.noop),
    ]
