# Generated by Django 5.2.8 on 2025-12-04 08:24

import simplevalidations.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.FileField(blank=True, null=True, storage=simplevalidations.blog.models.select_public_storage, upload_to=''),
        ),
    ]
