# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import validibot.validations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('submissions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_id', models.CharField(help_text='Unique callback identifier from the input envelope.', max_length=255, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When this callback was first processed.')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', help_text='Processing status of this callback receipt.', max_length=50)),
                ('result_uri', models.CharField(blank=True, default='', help_text='URI to the output envelope (e.g., gs:// for GCS, s3:// for S3).', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMED_OUT', 'Timed Out')], default='PENDING', max_length=16)),
                ('short_description', models.CharField(blank=True, default='', help_text='Optional short description of this validation run.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('error_category', models.CharField(blank=True, choices=[('VALIDATION_FAILED', 'Validation Failed'), ('TIMEOUT', 'Timed Out'), ('OOM', 'Out of Memory'), ('RUNTIME_ERROR', 'Runtime Error'), ('SYSTEM_ERROR', 'System Error')], default='', help_text='Classification of why the run failed (TIMEOUT, OOM, etc.).', max_length=32)),
                ('source', models.CharField(choices=[('LAUNCH_PAGE', 'Launch Page'), ('API', 'API')], default='LAUNCH_PAGE', help_text='Where this run was initiated (web launch page, API, etc.).', max_length=32)),
                ('output_retention_policy', models.CharField(choices=[('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_90_DAYS', 'Store for 90 days'), ('STORE_1_YEAR', 'Store for 1 year'), ('STORE_PERMANENTLY', 'Store permanently')], default='STORE_30_DAYS', help_text="Snapshot of workflow's output retention policy at run time.", max_length=32)),
                ('output_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When outputs should be purged (null = never expires or not yet computed).', null=True)),
                ('output_purged_at', models.DateTimeField(blank=True, help_text='When outputs were purged (for audit trail).', null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='users.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs', to='projects.project')),
                ('submission', models.ForeignKey(blank=True, help_text='Can be NULL if submission record was deleted. Code accessing this field must handle the None case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='submissions.submission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('step_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(default=0)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationStepRunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('step_name', models.CharField(blank=True, default='', max_length=255)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['step_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the validator, used in URLs.')),
                ('short_description', models.CharField(blank=True, default='', help_text="A brief summary of the validator's purpose. This description appears in lists and cards.", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description of the validator.')),
                ('name', models.CharField(max_length=120)),
                ('validation_type', models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40)),
                ('version', models.CharField(blank=True, default='', help_text="Version label for this validator (e.g. '2020-12', '1.0').", max_length=40)),
                ('processor_name', models.CharField(blank=True, default='', help_text='The name of the process that generates output signals from input signals.', max_length=200)),
                ('has_processor', models.BooleanField(default=False, help_text='True when the validator includes an intermediate processor that produces output signals.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Relative ordering for display purposes.')),
                ('is_system', models.BooleanField(default=True, help_text='True when the validator ships with the platform.')),
                ('release_state', models.CharField(choices=[('DRAFT', 'Draft'), ('COMING_SOON', 'Coming Soon'), ('PUBLISHED', 'Published')], default='PUBLISHED', help_text='Release state for system validators. DRAFT hides the validator, COMING_SOON shows it disabled, PUBLISHED makes it fully available.', max_length=16)),
                ('allow_custom_assertion_targets', models.BooleanField(default=False, help_text='Allow authors to enter assertion targets not present in the catalog.')),
                ('supported_data_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('energyplus_idf', 'EnergyPlus IDF'), ('energyplus_epjson', 'EnergyPlus epJSON'), ('fmu', 'FMU'), ('unknown', 'Unknown')], max_length=32), default=validibot.validations.models._default_validator_data_formats, help_text='Data formats this validator can parse (e.g., JSON, EnergyPlus IDF).')),
                ('supported_file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('binary', 'Binary'), ('UNKNOWN', 'Unknown')], max_length=32), default=validibot.validations.models._default_validator_file_types, help_text='Logical file types this validator can process (JSON, XML, text, etc.).')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValidatorCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entry_type', models.CharField(choices=[('signal', 'Signal'), ('derivation', 'Derivation')], max_length=32)),
                ('run_stage', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='input', help_text="Phase of the validator run when this entry is available. INPUT is before the validator's processor operates on the data. OUTPUT is the data generated by the validator's processor.", max_length=16)),
                ('slug', models.SlugField(help_text='Unique name for this catalog entry within the validator. You use this name in assertions and CEL statements.', max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text='Human-friendly label shown in editors.', max_length=255)),
                ('target_field', models.CharField(help_text='Path used to locate this signal in the input or processor output.', max_length=255)),
                ('input_binding_path', models.CharField(blank=True, default='', help_text='Optional path to the submission field used for this input signal. If empty, the system uses the catalog slug as a top-level key. Workflow authors cannot override this binding.', max_length=255)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('timeseries', 'Timeseries'), ('string', 'String'), ('boolean', 'Boolean'), ('object', 'Object')], default='number', max_length=32)),
                ('description', models.TextField(blank=True, default='', help_text='A short description to help you remember what data this signal represents.')),
                ('binding_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific binding metadata.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional UI metadata (example units, tags, etc.).')),
                ('is_required', models.BooleanField(default=False, help_text='Requires the signal to be present in the submission (inputs) or processor output (outputs).')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden signals remain available to bindings but are not shown in authoring interfaces.')),
                ('default_value', models.JSONField(blank=True, default=None, help_text='Optional default applied when the signal is hidden.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ValidatorCatalogRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(choices=[('cel_expr', 'CEL expression')], default='cel_expr', max_length=32)),
                ('expression', models.TextField(help_text='Rule definition (e.g., CEL expression).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data for this rule.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Relative ordering for evaluation/display.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValidatorCatalogRuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=120)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file', models.FileField(upload_to=validibot.validations.models.artifact_upload_to)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustomValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('custom_type', models.CharField(choices=[('SIMPLE', 'Simple'), ('MODELICA', 'Modelica'), ('KERML', 'KerML')], max_length=32)),
                ('base_validation_type', models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_validators', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_validator_configs', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FMUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=validibot.validations.models._fmu_upload_path)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA256 checksum used to reference cached FMUs in storage.', max_length=128)),
                ('gcs_uri', models.CharField(blank=True, default='', help_text='Cloud storage URI to the canonical FMU object (e.g., gs://bucket/fmus/<checksum>.fmu for GCS).', max_length=512)),
                ('fmi_version', models.CharField(choices=[('2.0', 'FMI 2.0'), ('3.0', 'FMI 3.0')], default='2.0', max_length=8)),
                ('kind', models.CharField(choices=[('ModelExchange', 'Model Exchange'), ('CoSimulation', 'Co-Simulation')], default='CoSimulation', max_length=32)),
                ('is_approved', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('introspection_metadata', models.JSONField(blank=True, default=dict)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fmu_models', to='users.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmu_models', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FMIVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('causality', models.CharField(max_length=64)),
                ('variability', models.CharField(blank=True, default='', max_length=64)),
                ('value_reference', models.BigIntegerField(default=0)),
                ('value_type', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, default='', max_length=128)),
                ('fmu_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='validations.fmumodel')),
            ],
        ),
        migrations.CreateModel(
            name='FMUProbeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('fmu_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='probe_result', to='validations.fmumodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('ruleset_type', models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40)),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('rules_file', models.FileField(blank=True, help_text='Optional uploaded file containing the ruleset definition. Leave empty when pasting rules directly.', upload_to='rulesets/')),
                ('rules_text', models.TextField(blank=True, default='', help_text='Inline ruleset definition (for example, JSON Schema or XML schema text). Use this when you prefer to paste or store the rules without uploading a file.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the ruleset (non-rule data only).')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='users.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The user who created this ruleset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rulesets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RulesetAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assertion_type', models.CharField(choices=[('basic', 'Basic Assertion'), ('cel_expr', 'CEL expression')], default='basic', max_length=32)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('lt', 'Less than'), ('le', 'Less than or equal'), ('gt', 'Greater than'), ('ge', 'Greater than or equal'), ('between', 'Between (range)'), ('in', 'Is one of'), ('not_in', 'Is not one of'), ('subset', 'Set is subset of'), ('superset', 'Set is superset of'), ('unique', 'All values unique'), ('contains', 'Contains'), ('not_contains', 'Does not contain'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('matches', 'Matches regex'), ('is_null', 'Is null'), ('not_null', 'Is not null'), ('is_empty', 'Is empty'), ('not_empty', 'Is not empty'), ('type_is', 'Type is'), ('len_eq', 'Length equals'), ('len_le', 'Length ≤'), ('len_ge', 'Length ≥'), ('count_between', 'Count between'), ('before', 'Before'), ('after', 'After'), ('within', 'Within duration'), ('approx_eq', '≈ Equals (tolerance)'), ('any', 'Any element satisfies'), ('all', 'All elements satisfy'), ('none', 'No element satisfies'), ('cel_expr', 'CEL expression')], default='le', help_text='Structured operator used for BASIC assertions.', max_length=32)),
                ('target_field', models.CharField(blank=True, default='', help_text='Custom JSON-style path for validators that allow free-form targets.', max_length=255)),
                ('severity', models.CharField(choices=[('SUCCESS', 'Success'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=16)),
                ('when_expression', models.TextField(blank=True, default='', help_text='Optional CEL expression gating when the assertion evaluates.')),
                ('rhs', models.JSONField(blank=True, default=dict, help_text='Operator payload (values, range bounds, regex pattern, etc.).')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Operator options (inclusive bounds, tolerance metadata, case folding, etc.).')),
                ('message_template', models.TextField(blank=True, default='', help_text='Message rendered when the assertion fails.')),
                ('success_message', models.TextField(blank=True, default='', help_text='Message rendered when the assertion passes.')),
                ('cel_cache', models.TextField(blank=True, default='', help_text='Normalized CEL preview generated from the stored payload.')),
                ('spec_version', models.PositiveIntegerField(default=1, help_text='Schema version for `rhs` and `options` payloads.')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='validations.ruleset')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('severity', models.CharField(choices=[('SUCCESS', 'Success'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField()),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ruleset_assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='validations.rulesetassertion')),
            ],
            options={
                'ordering': [models.Case(models.When(severity='ERROR', then=models.Value(0)), models.When(severity='WARNING', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), '-created'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRunSummary',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary_record', serialize=False, to='validations.validationrun')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMED_OUT', 'Timed Out')], default='PENDING', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('assertion_failure_count', models.PositiveIntegerField(default=0)),
                ('assertion_total_count', models.PositiveIntegerField(default=0)),
                ('extras', models.JSONField(blank=True, default=dict, help_text='Optional metadata for reporting (for example exemplar messages).')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
