# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('validations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_runs', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='validationfinding',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='callbackreceipt',
            name='validation_run',
            field=models.ForeignKey(help_text='The validation run this callback was for.', on_delete=django.db.models.deletion.CASCADE, related_name='callback_receipts', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='validationsteprun',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='validationsteprun',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='validationfinding',
            name='validation_step_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='validations.validationsteprun'),
        ),
        migrations.AddField(
            model_name='validationsteprunsummary',
            name='step_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_summary', to='validations.validationsteprun'),
        ),
        migrations.AddField(
            model_name='validator',
            name='default_ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='validations.ruleset'),
        ),
        migrations.AddField(
            model_name='validator',
            name='fmu_model',
            field=models.ForeignKey(blank=True, help_text='FMU artifact backing this validator (only used for FMI validators).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validators', to='validations.fmumodel'),
        ),
        migrations.AddField(
            model_name='validator',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Owning organization for custom validators (null for system validators).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='users.organization'),
        ),
        migrations.AddField(
            model_name='customvalidator',
            name='validator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_validator', to='validations.validator'),
        ),
        migrations.AddField(
            model_name='validatorcatalogentry',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='validations.validator'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='target_catalog_entry',
            field=models.ForeignKey(blank=True, help_text='Reference to a catalog entry when targeting a known signal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruleset_assertions', to='validations.validatorcatalogentry'),
        ),
        migrations.AddField(
            model_name='fmivariable',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmi_variables', to='validations.validatorcatalogentry'),
        ),
        migrations.AddField(
            model_name='validatorcatalogrule',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='validations.validator'),
        ),
        migrations.AddField(
            model_name='validatorcatalogruleentry',
            name='catalog_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_rules', to='validations.validatorcatalogentry'),
        ),
        migrations.AddField(
            model_name='validatorcatalogruleentry',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_entries', to='validations.validatorcatalogrule'),
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['org', 'ruleset_type'], name='validations_org_id_617f8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('org', 'ruleset_type', 'name', 'version'), name='uq_ruleset_org_ruleset_type_name_version'),
        ),
        migrations.AddField(
            model_name='validationsteprunsummary',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_summaries', to='validations.validationrunsummary'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['org', 'project', 'workflow', 'created'], name='validations_org_id_8bb46b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['status', 'created'], name='validations_status_ba8d2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationrun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_run_times_valid'),
        ),
        migrations.AddIndex(
            model_name='callbackreceipt',
            index=models.Index(fields=['callback_id'], name='validations_callbac_647c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackreceipt',
            index=models.Index(fields=['validation_run'], name='validations_validat_2570c9_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackreceipt',
            index=models.Index(fields=['received_at'], name='validations_receive_c9be3d_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['validation_run', 'created'], name='validations_validat_517e90_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsteprun',
            index=models.Index(fields=['validation_run', 'status'], name='validations_validat_1b7c62_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'step_order'), name='uq_step_run_run_order'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'workflow_step'), name='uq_step_run_run_step'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_step_run_times_valid'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_run', 'severity'], name='validations_validat_288fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'severity'], name='validations_validat_8354a9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'code'], name='validations_validat_a1aede_idx'),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['validation_type', 'slug'], name='validations_validat_379228_idx'),
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='uq_validator_slug_version'),
        ),
        migrations.AddConstraint(
            model_name='customvalidator',
            constraint=models.UniqueConstraint(fields=('org', 'custom_type', 'validator'), name='uq_custom_validator_org_type_validator'),
        ),
        migrations.AddConstraint(
            model_name='validatorcatalogentry',
            constraint=models.UniqueConstraint(fields=('validator', 'entry_type', 'run_stage', 'slug'), name='uq_validator_catalog_entry'),
        ),
        migrations.AddIndex(
            model_name='rulesetassertion',
            index=models.Index(fields=['ruleset', 'order'], name='validations_ruleset_2ba147_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesetassertion',
            index=models.Index(fields=['operator'], name='validations_operato_8efc76_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_catalog_entry__isnull', False), ('target_field', '')), models.Q(('target_catalog_entry__isnull', True), models.Q(('target_field', ''), _negated=True)), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
        migrations.AddIndex(
            model_name='fmivariable',
            index=models.Index(fields=['fmu_model', 'name'], name='validations_fmu_mod_69d7e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='validatorcatalogrule',
            constraint=models.UniqueConstraint(fields=('validator', 'name'), name='uq_validator_rule_name'),
        ),
        migrations.AddConstraint(
            model_name='validatorcatalogrule',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='ck_validator_rule_order_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='validatorcatalogruleentry',
            index=models.Index(fields=['rule', 'catalog_entry'], name='validations_rule_id_3fe185_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validatorcatalogruleentry',
            unique_together={('rule', 'catalog_entry')},
        ),
        migrations.AddIndex(
            model_name='validationsteprunsummary',
            index=models.Index(fields=['summary', 'status'], name='validations_summary_4cdb67_idx'),
        ),
    ]
