# Generated by Django 5.2.7 on 2025-10-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_runs', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='validationfinding',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='validationsteprun',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='validationsteprun',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='validationfinding',
            name='validation_step_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='validations.validationsteprun'),
        ),
        migrations.AddField(
            model_name='validator',
            name='default_ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='validations.ruleset'),
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['org', 'ruleset_type'], name='validations_org_id_617f8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('org', 'ruleset_type', 'name', 'version'), name='uq_ruleset_org_ruleset_type_name_version'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['org', 'project', 'workflow', 'created'], name='validations_org_id_8bb46b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['status', 'created'], name='validations_status_ba8d2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationrun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_run_times_valid'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['validation_run', 'created'], name='validations_validat_517e90_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsteprun',
            index=models.Index(fields=['validation_run', 'status'], name='validations_validat_1b7c62_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'step_order'), name='uq_step_run_run_order'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'workflow_step'), name='uq_step_run_run_step'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_step_run_times_valid'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'severity'], name='validations_validat_8354a9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'code'], name='validations_validat_a1aede_idx'),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['validation_type', 'slug'], name='validations_validat_379228_idx'),
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='uq_validator_slug_version'),
        ),
    ]
