# Generated by Django 6.0.2 on 2026-02-05 01:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('validations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorResourceFile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('weather', 'Weather File'), ('library', 'Library'), ('config', 'Configuration'), ('other', 'Other')], help_text='Type of resource (weather, library, config, etc.).', max_length=32)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'San Francisco TMY3').", max_length=200)),
                ('filename', models.CharField(help_text="Original filename (e.g., 'USA_CA_San.Francisco...epw').", max_length=255)),
                ('file', models.FileField(help_text='The resource file stored in private media.', upload_to=validibot.validations.models._resource_file_upload_path)),
                ('is_default', models.BooleanField(default=False, help_text='Show this resource in dropdowns by default. System defaults are shown to all orgs; org defaults only to that org.')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or notes about this resource.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Validator-specific metadata (e.g., location info for weather).')),
                ('org', models.ForeignKey(blank=True, help_text='Owning organization (NULL for system-wide resources visible to all orgs).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validator_resource_files', to='users.organization')),
                ('validator', models.ForeignKey(help_text='The validator this resource file is for.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='validations.validator')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['validator', 'resource_type'], name='validations_validat_353311_idx'), models.Index(fields=['org', 'resource_type'], name='validations_org_id_61190d_idx')],
            },
        ),
    ]
