# Generated by Django 6.0.2 on 2026-02-05 02:41

import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_add_validator_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorresourcefile',
            name='file',
            field=models.FileField(help_text='The resource file stored in private media.', max_length=500, upload_to=validibot.validations.models._resource_file_upload_path),
        ),
        migrations.AlterField(
            model_name='validatorresourcefile',
            name='resource_type',
            field=models.CharField(choices=[('energyplus_weather', 'EnergyPlus Weather File (EPW)')], help_text='Type of resource (weather, library, config, etc.).', max_length=32),
        ),
    ]
