# Generated by Django 6.0.2 on 2026-02-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0004_increase_resource_file_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="validatorcatalogrule",
            name="uq_validator_rule_name",
        ),
        migrations.RemoveConstraint(
            model_name="validatorcatalogrule",
            name="ck_validator_rule_order_nonnegative",
        ),
        migrations.AlterUniqueTogether(
            name="validatorcatalogruleentry",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="validatorcatalogruleentry",
            name="validations_rule_id_3fe185_idx",
        ),
        migrations.RemoveField(
            model_name="validatorcatalogruleentry",
            name="catalog_entry",
        ),
        migrations.RemoveField(
            model_name="validatorcatalogruleentry",
            name="rule",
        ),
        migrations.DeleteModel(
            name="ValidatorCatalogRule",
        ),
        migrations.DeleteModel(
            name="ValidatorCatalogRuleEntry",
        ),
    ]
