# Generated by Django 6.0.2 on 2026-02-11 19:44

import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0005_remove_validator_catalog_rule_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorresourcefile',
            name='file',
            field=models.FileField(help_text='The resource file stored in default media storage (public/ prefix).', max_length=500, upload_to=validibot.validations.models._resource_file_upload_path),
        ),
    ]
