# Generated by Django 6.0.2 on 2026-02-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0006_alter_validatorresourcefile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorresourcefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this resource file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resource_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
