# Generated by Django 6.0.2 on 2026-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0007_add_uploaded_by_to_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorresourcefile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this resource as a default when displaying to workflow authors. System defaults are shown to all orgs; org defaults only to that org.'),
        ),
    ]
