# Generated by Django 6.0.2 on 2026-02-19 00:31

import django.contrib.postgres.fields
import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0008_alter_validatorresourcefile_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist'), ('THERM', 'THERM Thermal Analysis')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('THERM', 'THERM')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='supported_data_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('energyplus_idf', 'EnergyPlus IDF'), ('energyplus_epjson', 'EnergyPlus epJSON'), ('fmu', 'FMU'), ('therm_thmx', 'THERM THMX'), ('therm_thmz', 'THERM THMZ (Archive)'), ('unknown', 'Unknown')], max_length=32), default=validibot.validations.models._default_validator_data_formats, help_text='Data formats this validator can parse (e.g., JSON, EnergyPlus IDF).'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist'), ('THERM', 'THERM Thermal Analysis')], max_length=40),
        ),
    ]
