# Generated by Django 6.0.2 on 2026-02-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0011_rename_fmivariable_to_fmuvariable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fmuvariable',
            new_name='validations_fmu_mod_c4bd31_idx',
            old_name='validations_fmu_mod_69d7e9_idx',
        ),
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMU', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist'), ('THERM', 'THERM Thermal Analysis')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMU', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('THERM', 'THERM')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='fmu_model',
            field=models.ForeignKey(blank=True, help_text='FMU artifact backing this validator (only used for FMU validators).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validators', to='validations.fmumodel'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMU', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist'), ('THERM', 'THERM Thermal Analysis')], max_length=40),
        ),
    ]
