# Generated by Django 6.0.2 on 2026-02-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0012_rename_fmu_model_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmuvariable',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmu_variables', to='validations.validatorcatalogentry'),
        ),
    ]
