# Generated by Django 6.0.2 on 2026-02-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0015_remove_input_binding_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Disabled validators are hidden from users and cannot be added to workflows. Toggle via the admin panel.'),
        ),
    ]
