# Generated by Django 6.0.2 on 2026-02-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0016_add_validator_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='compute_tier',
            field=models.CharField(choices=[('LOW', 'Low compute'), ('HIGH', 'High compute')], default='LOW', help_text='Compute intensity classification. LOW = metered by launch count. HIGH = metered by credit consumption.', max_length=10),
        ),
        migrations.AddField(
            model_name='validator',
            name='compute_weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal (1x)'), (2, 'Medium (2x)'), (3, 'Heavy (3x)'), (5, 'Extreme (5x)')], default=1, help_text='Credit multiplier for HIGH-compute validators. Higher weight = more credits consumed per minute of runtime.'),
        ),
    ]
