# Generated by Django 6.0.2 on 2026-02-26 05:20

from django.db import migrations


# Validators whose validation_type maps to HIGH compute tier.
HIGH_COMPUTE_TYPES = ("ENERGYPLUS", "FMU", "THERM")


def set_compute_tier_for_heavy_validators(apps, schema_editor):
    """Set compute_tier=HIGH for existing heavy validators (EnergyPlus, FMU, THERM)."""
    Validator = apps.get_model("validations", "Validator")
    Validator.objects.filter(validation_type__in=HIGH_COMPUTE_TYPES).update(
        compute_tier="HIGH",
    )


def reverse_compute_tier(apps, schema_editor):
    """Reset all validators back to LOW (the field default)."""
    Validator = apps.get_model("validations", "Validator")
    Validator.objects.filter(validation_type__in=HIGH_COMPUTE_TYPES).update(
        compute_tier="LOW",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0017_add_compute_tier_and_weight_to_validator"),
    ]

    operations = [
        migrations.RunPython(
            set_compute_tier_for_heavy_validators,
            reverse_code=reverse_compute_tier,
        ),
    ]
