# Generated by Django 5.2.7 on 2025-11-18 21:15

from django.db import migrations, models


OLD_VALIDATION_TYPE = "CUSTOM_RULES"
NEW_VALIDATION_TYPE = "CUSTOM_VALIDATOR"


def _update_validation_type(apps, model_name: str, field_name: str, from_value: str, to_value: str):
    Model = apps.get_model("validations", model_name)
    Model.objects.filter(**{field_name: from_value}).update(**{field_name: to_value})


def forwards(apps, schema_editor):
    for model_name, field_name in (
        ("Validator", "validation_type"),
        ("Ruleset", "ruleset_type"),
        ("CustomValidator", "base_validation_type"),
    ):
        _update_validation_type(apps, model_name, field_name, OLD_VALIDATION_TYPE, NEW_VALIDATION_TYPE)


def backwards(apps, schema_editor):
    for model_name, field_name in (
        ("Validator", "validation_type"),
        ("Ruleset", "ruleset_type"),
        ("CustomValidator", "base_validation_type"),
    ):
        _update_validation_type(apps, model_name, field_name, NEW_VALIDATION_TYPE, OLD_VALIDATION_TYPE)


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0018_validationrun_short_description'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Validator')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
    ]
