# Generated by Django 6.0.2 on 2026-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0018_set_compute_tier_for_heavy_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='supports_assertions',
            field=models.BooleanField(default=False, help_text='True when this validator supports step-level assertions (Basic and CEL). Schema-only validators (JSON Schema, XML Schema) do not support assertions.'),
        ),
    ]
