# Generated by Django 6.0.2 on 2026-03-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0021_rename_xml_validator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='allow_custom_assertion_targets',
            field=models.BooleanField(default=False, help_text='Allow assertions against data paths not declared as signals.'),
        ),
    ]
