# Generated by Django 6.0.3 on 2026-03-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0022_workflowstepresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='output_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the canonical validation output record, computed at run completion. Covers the stable workflow context and the final run outcome.', max_length=64),
        ),
    ]
