# Generated by Django 6.0.3 on 2026-03-10 02:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0022_workflowstepresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrun",
            name="evidence_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 hash of the canonical run evidence record, "
                    "computed at run completion. Covers: content hash, run "
                    "ID, user, status, timestamps, finding counts, and "
                    "submission name."
                ),
                max_length=64,
            ),
        ),
    ]
