# Generated by Django 6.0.3 on 2026-03-12 01:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0023_add_evidence_hash_to_validation_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("LAUNCH_PAGE", "Launch Page"),
                    ("API", "API"),
                    ("MCP", "MCP (AI Agent)"),
                ],
                default="LAUNCH_PAGE",
                help_text=(
                    "Where this run was initiated (web launch page, API, etc.)."
                ),
                max_length=32,
            ),
        ),
    ]
