# Generated by Django 6.0.3 on 2026-03-19 01:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0025_fmu_allow_custom_assertion_targets'),
        ('workflows', '0006_add_description_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contract_key', models.SlugField(help_text='Stable slug identifier used in CEL expressions, API responses, and data path bindings. Must be unique per owner and direction.', max_length=255)),
                ('native_name', models.CharField(blank=True, default='', help_text="The provider's original name for this signal, preserved verbatim (e.g., an FMU variable name or template placeholder).", max_length=500)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable display label for the signal.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of what this signal represents.')),
                ('direction', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], help_text='Whether this signal is consumed (input) or produced (output).', max_length=10)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('timeseries', 'Timeseries'), ('string', 'String'), ('boolean', 'Boolean'), ('object', 'Object')], default='number', help_text='The data type of the signal value.', max_length=20)),
                ('origin_kind', models.CharField(choices=[('catalog', 'Catalog'), ('fmu', 'FMU'), ('template', 'Template')], help_text='How this signal definition was created: from a catalog entry, an FMU probe, or a template scan.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Display ordering within the owner's signal list.")),
                ('is_hidden', models.BooleanField(default=False, help_text='If True, this signal is hidden from the default signals UI.')),
                ('unit', models.CharField(blank=True, default='', help_text="Unit of measurement (e.g., 'kW', 'm2', 'degC').", max_length=50)),
                ('provider_binding', models.JSONField(blank=True, default=dict, help_text='Validator-type-specific properties needed by the resolution layer (e.g., FMU causality/value_reference, EnergyPlus variable_type/min/max). Typed access via Pydantic models.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata for extensions and integrations.')),
                ('validator', models.ForeignKey(blank=True, help_text='The validator that owns this signal (for library validators). Mutually exclusive with workflow_step.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_definitions', to='validations.validator')),
                ('workflow_step', models.ForeignKey(blank=True, help_text='The workflow step that owns this signal (for step-level FMUs, templates, or author-customized signals). Mutually exclusive with validator.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_definitions', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResolvedInputTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('signal_contract_key', models.CharField(help_text='Denormalized contract_key from the signal definition, preserved for auditability if the definition is deleted.', max_length=255)),
                ('source_scope_used', models.CharField(help_text="The source scope that was actually used to resolve the value (may differ from the binding's configured scope if fallback logic was applied).", max_length=30)),
                ('source_data_path_used', models.CharField(help_text='The data path that was actually used to resolve the value.', max_length=500)),
                ('upstream_step_key', models.CharField(blank=True, default='', help_text="If source_scope_used is 'upstream_step', the key of the upstream step whose output was consulted.", max_length=100)),
                ('resolved', models.BooleanField(help_text='Whether the resolution engine found a value for this signal.')),
                ('used_default', models.BooleanField(default=False, help_text="Whether the resolved value came from the binding's default_value rather than the source data path.")),
                ('value_snapshot', models.JSONField(blank=True, help_text='Snapshot of the resolved value at resolution time, for debugging and reproducibility.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if resolution failed (e.g., required signal not found and no default configured).')),
                ('step_run', models.ForeignKey(help_text='The step run this trace belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='input_traces', to='validations.validationsteprun')),
                ('signal_definition', models.ForeignKey(help_text='The signal definition that was being resolved. SET_NULL on delete so traces survive schema evolution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='validations.signaldefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepSignalBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source_scope', models.CharField(choices=[('submission_payload', 'Submission Payload'), ('submission_metadata', 'Submission Metadata'), ('upstream_step', 'Upstream Step'), ('system', 'System')], default='submission_payload', help_text='The data scope to resolve the signal value from: submission payload, submission metadata, upstream step output, or system.', max_length=30)),
                ('source_data_path', models.CharField(blank=True, default='', help_text="Dotted path expression into the source scope (e.g., 'building.envelope.panel_area' or 'stations[0].temp').", max_length=500)),
                ('default_value', models.JSONField(blank=True, default=None, help_text='Fallback value used when the source path resolves to nothing and the signal is not marked as required.', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='If True, a missing value with no default raises a structured error before validator execution begins.')),
                ('signal_definition', models.ForeignKey(help_text='The signal definition this binding wires up.', on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='validations.signaldefinition')),
                ('workflow_step', models.ForeignKey(help_text='The workflow step this binding belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='signal_bindings', to='workflows.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contract_key', models.SlugField(help_text='Stable slug identifier for this derivation, used in CEL expressions and API responses.', max_length=255)),
                ('expression', models.TextField(help_text="CEL expression that computes this derivation's value. Can reference signal contract_keys and other derivation keys.")),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of what this derivation computes.')),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable display label for the derivation.', max_length=255)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('string', 'String'), ('boolean', 'Boolean')], default='number', help_text='The data type of the computed value. Limited to scalar types (number, string, boolean).', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Display ordering within the owner's derivation list.")),
                ('is_hidden', models.BooleanField(default=False, help_text='If True, this derivation is hidden from the default UI.')),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement for the computed value.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata for extensions and integrations.')),
                ('validator', models.ForeignKey(blank=True, help_text='The validator that owns this derivation (for library validators). Mutually exclusive with workflow_step.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivations', to='validations.validator')),
                ('workflow_step', models.ForeignKey(blank=True, help_text='The workflow step that owns this derivation. Mutually exclusive with validator.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivations', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('validator__isnull', False), ('workflow_step__isnull', True)), models.Q(('validator__isnull', True), ('workflow_step__isnull', False)), _connector='OR'), name='ck_derivation_one_owner'), models.UniqueConstraint(condition=models.Q(('validator__isnull', False)), fields=('validator', 'contract_key'), name='uq_derivation_validator_key'), models.UniqueConstraint(condition=models.Q(('workflow_step__isnull', False)), fields=('workflow_step', 'contract_key'), name='uq_derivation_step_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='signaldefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('validator__isnull', False), ('workflow_step__isnull', True)), models.Q(('validator__isnull', True), ('workflow_step__isnull', False)), _connector='OR'), name='ck_sigdef_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='signaldefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('validator__isnull', False)), fields=('validator', 'contract_key', 'direction'), name='uq_sigdef_validator_key_dir'),
        ),
        migrations.AddConstraint(
            model_name='signaldefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_step__isnull', False)), fields=('workflow_step', 'contract_key', 'direction'), name='uq_sigdef_step_key_dir'),
        ),
        migrations.AddConstraint(
            model_name='stepsignalbinding',
            constraint=models.UniqueConstraint(fields=('workflow_step', 'signal_definition'), name='uq_binding_step_signal'),
        ),
    ]
