# Generated by Django 6.0.7 on 2026-07-16 05:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_current_schema"),
        ("validations", "0025_fmu_allow_custom_assertion_targets"),
        ("workflows", "0006_add_description_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Derivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "contract_key",
                    models.SlugField(
                        help_text="Stable slug identifier for this derivation, used in CEL expressions and API responses.",
                        max_length=255,
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="CEL expression that computes this derivation's value. Can reference step I/O contract keys and other derivation keys."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of what this derivation computes.",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable display label for the derivation.",
                        max_length=255,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                        ],
                        default="number",
                        help_text="The data type of the computed value. Limited to scalar types (number, string, boolean).",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display ordering within the owner's derivation list.",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this derivation is hidden from the default UI.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of measurement for the computed value.",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata for extensions and integrations.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionAttempt",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPATCHING", "Dispatching"),
                            ("RUNNING", "Running"),
                            ("UNKNOWN", "Provider acceptance unknown"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                            ("TIMED_OUT", "Timed out"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("runner_type", models.CharField(max_length=64)),
                (
                    "provider_job_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "provider_execution_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "callback_nonce_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Digest verifier for the per-attempt callback secret.",
                        max_length=128,
                    ),
                ),
                (
                    "execution_bundle_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "input_envelope_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "input_envelope_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "output_envelope_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "output_envelope_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "backend_image_ref",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "backend_image_digest",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("timeout_at", models.DateTimeField(blank=True, null=True)),
                ("retry_policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("dispatch_started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_finished_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_status_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
            ],
            options={
                "ordering": ["step_run_id", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="ResolvedInputTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "input_contract_key",
                    models.CharField(
                        help_text="Denormalized contract_key from the step I/O definition, preserved for auditability if the definition is deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "source_scope_used",
                    models.CharField(
                        help_text="The source scope that was actually used to resolve the value (may differ from the binding's configured scope if fallback logic was applied).",
                        max_length=30,
                    ),
                ),
                (
                    "source_data_path_used",
                    models.CharField(
                        help_text="The data path that was actually used to resolve the value.",
                        max_length=500,
                    ),
                ),
                (
                    "upstream_step_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If source_scope_used is 'upstream_step', the key of the upstream step whose output was consulted.",
                        max_length=100,
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        help_text="Whether the resolution engine found a value for this step input."
                    ),
                ),
                (
                    "used_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the resolved value came from the binding's default_value rather than the source data path.",
                    ),
                ),
                (
                    "value_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the resolved value at resolution time, for debugging and reproducibility.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if resolution failed (e.g., required step input not found and no default configured).",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RunEvidenceArtifact",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        help_text="The validibot.evidence.vN schema string the manifest was produced under. Verifiers parse the manifest's schema_version field at read time, but storing it here lets the auditor query for runs on stale schemas without fetching the bytes.",
                        max_length=64,
                    ),
                ),
                (
                    "manifest_path",
                    models.FileField(
                        blank=True,
                        help_text="Path to the canonical-JSON manifest in default storage. Empty when availability is FAILED (generation never produced bytes).",
                        max_length=500,
                        upload_to=validibot.validations.models._evidence_manifest_upload_path,
                    ),
                ),
                (
                    "manifest_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of the manifest's canonical-JSON bytes. Empty when availability is FAILED. Future signed credentials (Phase 4 Session C) cite this hash, so a re-fetch + re-hash detects tampering.",
                        max_length=64,
                    ),
                ),
                (
                    "cached_bundle_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phase 4 Session C: path to a cached export-bundle tarball (manifest + inputs + outputs + signature). Empty until the operator triggers an export.",
                        max_length=500,
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Workflow.input_retention at the time the manifest was generated. Mirrored here so retention-sweep code can filter without joining to Workflow.",
                        max_length=32,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Manifest generated and bytes available"),
                            ("PURGED", "Manifest bytes purged; only hash remains"),
                            (
                                "FAILED",
                                "Manifest generation failed; row records the gap",
                            ),
                        ],
                        default="GENERATED",
                        help_text="Lifecycle state: GENERATED (bytes in storage), PURGED (only hash remains), or FAILED (generation aborted).",
                        max_length=16,
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="When availability is FAILED, the exception message from the manifest builder. Empty otherwise.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepInputBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source_scope",
                    models.CharField(
                        choices=[
                            ("submission_payload", "Submission Payload"),
                            ("submission_metadata", "Submission Metadata"),
                            ("submission_file", "Submission File"),
                            ("upstream_step", "Upstream Step"),
                            ("upstream_artifact", "Upstream Step Artifact"),
                            ("signal", "Workflow Signal"),
                            ("constant", "Workflow Constant"),
                            ("workflow_resource", "Workflow Resource"),
                            ("system", "System"),
                        ],
                        default="submission_payload",
                        help_text="The data scope to resolve the input value from: submission payload, submission metadata, workflow signal, upstream step output, or system.",
                        max_length=30,
                    ),
                ),
                (
                    "source_data_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path expression into the source scope. Supports dot notation (e.g., 'building.panel_area'), [index] for arrays, and filter expressions for named elements (e.g., 'items[?@.name==\"x\"].value').",
                        max_length=500,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Fallback value used when the source path resolves to nothing and the input is not marked as required.",
                        null=True,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If True, a missing value with no default raises a structured error before validator execution begins.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepIODefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "contract_key",
                    models.SlugField(
                        help_text="Stable slug identifier used in CEL expressions, API responses, and data path bindings. Must be unique per owner and direction.",
                        max_length=255,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The provider's original name for this step input or output, preserved verbatim (e.g., an FMU variable name or template placeholder).",
                        max_length=500,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable display label for this step input or output.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of this step input or output.",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")],
                        help_text="Whether this definition is consumed (input) or produced (output).",
                        max_length=10,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("timeseries", "Timeseries"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                            ("object", "Object"),
                            ("artifact_ref", "Artifact reference"),
                        ],
                        default="number",
                        help_text="The data type of the step input or output value.",
                        max_length=20,
                    ),
                ),
                (
                    "io_medium",
                    models.CharField(
                        choices=[("value", "Value"), ("artifact", "Artifact")],
                        default="value",
                        help_text="Whether this step I/O definition carries a small JSON value or a storage-backed artifact reference.",
                        max_length=20,
                    ),
                ),
                (
                    "artifact_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("file", "File"),
                            ("directory", "Directory"),
                            ("archive", "Archive"),
                            ("dataset", "Dataset"),
                            ("report", "Report"),
                            ("log", "Log"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Artifact kind when io_medium is artifact.",
                        max_length=32,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expected media type for artifact ports.",
                        max_length=128,
                    ),
                ),
                (
                    "data_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Domain data format for artifact ports.",
                        max_length=64,
                    ),
                ),
                (
                    "accepted_data_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Accepted domain data formats for artifact ports.",
                    ),
                ),
                (
                    "accepted_media_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Accepted media/MIME types for artifact ports.",
                    ),
                ),
                (
                    "allowed_source_scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Binding source scopes allowed for artifact ports.",
                    ),
                ),
                (
                    "default_source_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted_file_first", "Submitted file first"),
                            (
                                "submitted_file_then_default_resource",
                                "Submitted file then default resource",
                            ),
                            ("workflow_resource_default", "Workflow resource default"),
                            (
                                "upstream_artifact_suggestion",
                                "Upstream artifact suggestion",
                            ),
                            ("manual", "Manual"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="Default source-selection strategy for artifact input ports.",
                        max_length=64,
                    ),
                ),
                (
                    "envelope_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("input_files", "Input files"),
                            ("resource_files", "Resource files"),
                            ("output_artifacts", "Output artifacts"),
                        ],
                        default="",
                        help_text="Envelope channel this artifact port renders into.",
                        max_length=32,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resource type for artifact ports rendered as resource_files.",
                        max_length=64,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Validator-facing role for artifact ports.",
                        max_length=80,
                    ),
                ),
                (
                    "is_collection",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this port accepts or emits multiple artifact refs.",
                    ),
                ),
                (
                    "min_items",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum artifact count for artifact ports.",
                    ),
                ),
                (
                    "max_items",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum artifact count for artifact ports; null means unbounded.",
                        null=True,
                    ),
                ),
                (
                    "origin_kind",
                    models.CharField(
                        choices=[
                            ("catalog", "Catalog"),
                            ("fmu", "FMU"),
                            ("template", "Template"),
                        ],
                        help_text="How this step I/O definition was created: from a validator config declaration, an FMU probe, or a template scan.",
                        max_length=20,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("payload_path", "Payload Path"),
                            ("internal", "Internal"),
                        ],
                        default="payload_path",
                        help_text="How this step input/output value is obtained: from a known data path in the submission payload (PAYLOAD_PATH) or via the validator's own internal extraction mechanism (INTERNAL).",
                        max_length=20,
                    ),
                ),
                (
                    "is_path_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the workflow author can edit the source data path for this step input's binding. False when the validator controls the extraction path internally.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display ordering within the owner's step I/O list.",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this definition is hidden from the default step I/O UI.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of measurement (e.g., 'kW', 'm2', 'degC').",
                        max_length=50,
                    ),
                ),
                (
                    "provider_binding",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validator-type-specific properties needed by the resolution layer (e.g., FMU causality/value_reference, EnergyPlus variable_type/min/max). Typed access via Pydantic models.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata for extensions and integrations.",
                    ),
                ),
                (
                    "promoted_signal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional name for symmetric promotion (per ADR-2026-05-22b). When set on a step input or step output, the value is promoted into the s (signal) workflow vocabulary, available in downstream steps as s.<promoted_signal_name>. Must be a valid CEL identifier.",
                        max_length=100,
                    ),
                ),
                (
                    "on_missing",
                    models.CharField(
                        choices=[
                            ("error", "Fail the run with a clear message"),
                            (
                                "null",
                                "Inject null; assertions guard with has() or != null",
                            ),
                            ("ignore", "Omit silently; references resolve to null"),
                        ],
                        default="null",
                        help_text="Behaviour when the value cannot be resolved. Default 'null' is the safe choice; 'error' for entries downstream assertions reliably depend on; 'ignore' for genuinely optional facts. Runtime enforcement is deferred — the field is captured now so future PRs can read intent.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepIOPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "promoted_signal_name",
                    models.CharField(
                        help_text="The workflow-vocabulary name the promoted value is exposed under (s.<promoted_signal_name>). Must be a valid CEL identifier and unique across the workflow.",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="validatorcatalogentry",
            name="uq_validator_catalog_entry",
        ),
        migrations.RemoveField(
            model_name="fmuvariable",
            name="catalog_entry",
        ),
        migrations.RemoveConstraint(
            model_name="rulesetassertion",
            name="ck_ruleset_assertion_target_oneof",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="evidence_hash",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="summary",
        ),
        migrations.AddField(
            model_name="artifact",
            name="contract_key",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Stable artifact output name used in steps.<step_key>.artifact.*.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="data_format",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="artifact",
            name="item_key",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Stable item key for collection artifact outputs.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("directory", "Directory"),
                    ("archive", "Archive"),
                    ("dataset", "Dataset"),
                    ("report", "Report"),
                    ("log", "Log"),
                    ("other", "Other"),
                ],
                default="file",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="manifest_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="artifact",
            name="manifest_uri",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="artifact",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="artifact",
            name="producer_backend_image_digest",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="artifact",
            name="producer_validator_type",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="artifact",
            name="producer_validator_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="artifact",
            name="retention_class",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="artifact",
            name="role",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="artifact",
            name="sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="artifact",
            name="step_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Step run that produced this artifact, if step-scoped.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="validations.validationsteprun",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="storage_uri",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal storage URI; never a public signed URL.",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="workflow_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Workflow step that produced this artifact, if step-scoped.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="rulesetassertion",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes on the rationale behind this assertion. Not shown to data submitters.",
                max_length=5000,
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
        migrations.AddField(
            model_name="validationrun",
            name="output_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of the canonical validation output record, computed at run completion. Covers the stable workflow context and the final run outcome.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="validationsteprun",
            name="input_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Canonical contract-keyed input values resolved for this step.",
            ),
        ),
        migrations.AddField(
            model_name="validationsteprun",
            name="output_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Canonical contract-keyed output values produced by this step.",
            ),
        ),
        migrations.AddField(
            model_name="validationsteprun",
            name="validator_backend_image_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved sha256 digest of the validator backend image that executed this step (e.g. 'sha256:abc...' or 'registry/path/...@sha256:abc...'). Empty for simple-validator steps that run inline without a container. 256 chars accommodates registry-anchored references (registry path + image name + '@sha256:' + 64 hex), which commonly run 100+ chars for nested GCS / GAR paths.",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="availability_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Operator-facing reason this validator is unavailable, if any.",
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="availability_state",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MISSING_CONFIG", "Missing config"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                help_text="Whether this validator's runtime config/class is available in the current deployment. Missing validators remain in the DB for history but cannot launch.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="config_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Python provider module that last synced this validator from a ValidatorConfig. Empty means the row is not managed by plugin config reconciliation.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="semantic_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the semantic config at sync time. Used to detect drift when a validator's behavior changes under the same (slug, version) without an explicit version bump.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="trust_tier",
            field=models.CharField(
                choices=[
                    ("TIER_1", "Tier 1 (first-party)"),
                    ("TIER_2", "Tier 2 (user-added or partner-authored)"),
                ],
                default="TIER_1",
                help_text="Trust tier of the validator backend container this validator dispatches to. TIER_1 is the first-party hardening profile (default); TIER_2 applies a stricter sandbox for user-added or partner-authored backends. Simple validators (no backend) stay at TIER_1 by construction.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="validatorresourcefile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the file's content, computed on save. Used to detect drift when a catalog file referenced by a locked workflow tries to mutate.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=validibot.validations.models.artifact_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="callbackreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="PROCESSING",
                help_text="Processing status of this callback receipt.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customvalidator",
            name="base_validation_type",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="ruleset_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic Assertions"),
                    ("JSON_SCHEMA", "JSON Schema"),
                    ("XML_SCHEMA", "XML Schema"),
                    ("SCHEMATRON", "Schematron"),
                    ("SHACL", "SHACL Shapes"),
                    ("ENERGYPLUS", "EnergyPlus"),
                    ("FMU", "FMU Validator"),
                    ("CUSTOM_VALIDATOR", "Custom Basic Validator"),
                    ("THERM", "THERM"),
                    ("TABULAR", "Tabular"),
                ],
                help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="rulesetassertion",
            name="assertion_type",
            field=models.CharField(
                choices=[
                    ("shacl", "SHACL"),
                    ("basic", "Basic Assertion"),
                    ("cel_expr", "CEL expression"),
                ],
                default="basic",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rulesetassertion",
            name="operator",
            field=models.CharField(
                choices=[
                    ("sparql_ask", "SPARQL ASK"),
                    ("eq", "Equals"),
                    ("ne", "Not equals"),
                    ("lt", "Less than"),
                    ("le", "Less than or equal"),
                    ("gt", "Greater than"),
                    ("ge", "Greater than or equal"),
                    ("between", "Between (range)"),
                    ("in", "Is one of"),
                    ("not_in", "Is not one of"),
                    ("subset", "Set is subset of"),
                    ("superset", "Set is superset of"),
                    ("unique", "All values unique"),
                    ("contains", "Contains"),
                    ("not_contains", "Does not contain"),
                    ("starts_with", "Starts with"),
                    ("ends_with", "Ends with"),
                    ("matches", "Matches regex"),
                    ("is_null", "Is null"),
                    ("not_null", "Is not null"),
                    ("is_empty", "Is empty"),
                    ("not_empty", "Is not empty"),
                    ("type_is", "Type is"),
                    ("len_eq", "Length equals"),
                    ("len_le", "Length ≤"),
                    ("len_ge", "Length ≥"),
                    ("count_between", "Count between"),
                    ("before", "Before"),
                    ("after", "After"),
                    ("within", "Within duration"),
                    ("approx_eq", "≈ Equals (tolerance)"),
                    ("any", "Any element satisfies"),
                    ("all", "All elements satisfy"),
                    ("none", "No element satisfies"),
                    ("cel_expr", "CEL expression"),
                ],
                default="le",
                help_text="Structured operator used for BASIC assertions.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rulesetassertion",
            name="target_data_path",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom JSON-style path for validators that allow free-form targets. Supports dot notation, [index], and filter expressions (e.g., items[?@.name=='x'].value).",
            ),
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("LAUNCH_PAGE", "Launch Page"),
                    ("API", "API"),
                    ("MCP", "MCP (AI Agent)"),
                    ("X402_AGENT", "x402 Anonymous Agent"),
                    ("CLI", "Command-line Interface"),
                    ("SCHEDULE", "Scheduled / Automation"),
                ],
                default="LAUNCH_PAGE",
                help_text="Where this run was initiated (web launch page, API, etc.).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="allow_custom_assertion_targets",
            field=models.BooleanField(
                default=False,
                help_text="Allow assertions against data paths not declared by step I/O definitions.",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="has_processor",
            field=models.BooleanField(
                default=False,
                help_text="True when the validator includes an intermediate processor that produces step outputs.",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="processor_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the process that generates step outputs from step inputs.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="supported_data_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("json", "JSON"),
                        ("xml", "XML"),
                        ("text", "Plain Text"),
                        ("yaml", "YAML"),
                        ("energyplus_idf", "EnergyPlus IDF"),
                        ("energyplus_epjson", "EnergyPlus epJSON"),
                        ("fmu", "FMU"),
                        ("therm_thmx", "THERM THMX"),
                        ("therm_thmz", "THERM THMZ (Archive)"),
                        ("csv", "CSV (tabular)"),
                        ("unknown", "Unknown"),
                    ],
                    max_length=32,
                ),
                default=validibot.validations.models._default_validator_data_formats,
                help_text="Data formats this validator can parse (e.g., JSON, EnergyPlus IDF).",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="supports_assertions",
            field=models.BooleanField(
                default=False,
                help_text="True when this validator supports step-level assertions (Basic, CEL, or validator-specific assertion types).",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="validation_type",
            field=models.CharField(
                help_text="Runtime validator type string. Built-in validators use ValidationType constants, but plugin validators may register additional strings at startup.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Positive integer revision for this validator contract. Domain versions such as EnergyPlus/FMI/JSON Schema versions belong in tags or metadata, not this field.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["step_run", "contract_key"],
                name="validations_step_ru_7b9ffc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validator",
            index=models.Index(
                fields=["availability_state", "validation_type"],
                name="val_validator_avail_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("workflow_step__isnull", False),
                    models.Q(("contract_key", ""), _negated=True),
                    ("item_key", ""),
                ),
                fields=("validation_run", "workflow_step", "contract_key"),
                name="uq_artifact_run_step_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("workflow_step__isnull", False),
                    models.Q(("contract_key", ""), _negated=True),
                    models.Q(("item_key", ""), _negated=True),
                ),
                fields=("validation_run", "workflow_step", "contract_key", "item_key"),
                name="uq_artifact_run_step_item",
            ),
        ),
        migrations.AddField(
            model_name="derivation",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                help_text="The validator that owns this derivation (for library validators). Mutually exclusive with workflow_step.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derivations",
                to="validations.validator",
            ),
        ),
        migrations.AddField(
            model_name="derivation",
            name="workflow_step",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow step that owns this derivation. Mutually exclusive with validator.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derivations",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="executionattempt",
            name="step_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_attempts",
                to="validations.validationsteprun",
            ),
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="execution_attempt",
            field=models.ForeignKey(
                default=None,
                help_text="The concrete execution that produced this callback.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="callback_receipts",
                to="validations.executionattempt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resolvedinputtrace",
            name="step_run",
            field=models.ForeignKey(
                help_text="The step run this trace belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_traces",
                to="validations.validationsteprun",
            ),
        ),
        migrations.AddField(
            model_name="runevidenceartifact",
            name="run",
            field=models.OneToOneField(
                help_text="The validation run this manifest documents.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_artifact",
                to="validations.validationrun",
            ),
        ),
        migrations.AddField(
            model_name="stepinputbinding",
            name="workflow_step",
            field=models.ForeignKey(
                help_text="The workflow step this binding belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_bindings",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                help_text="The validator that owns this step I/O definition. Mutually exclusive with workflow_step.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_io_definitions",
                to="validations.validator",
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="workflow_step",
            field=models.ForeignKey(
                blank=True,
                help_text="The workflow step that owns this step I/O definition. Mutually exclusive with validator.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_io_definitions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="stepinputbinding",
            name="io_definition",
            field=models.ForeignKey(
                help_text="The step input definition this binding wires up.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_bindings",
                to="validations.stepiodefinition",
            ),
        ),
        migrations.AddField(
            model_name="resolvedinputtrace",
            name="io_definition",
            field=models.ForeignKey(
                help_text="The step I/O definition that was being resolved. SET_NULL on delete so traces survive schema evolution.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="validations.stepiodefinition",
            ),
        ),
        migrations.AddField(
            model_name="rulesetassertion",
            name="target_io_definition",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to a step I/O definition when targeting a known input or output.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ruleset_assertions",
                to="validations.stepiodefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_data_path", ""),
                        ("target_io_definition__isnull", False),
                    ),
                    ("target_io_definition__isnull", True),
                    _connector="OR",
                ),
                name="ck_ruleset_assertion_target_oneof",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepiopromotion",
            name="io_definition",
            field=models.ForeignKey(
                help_text="The validator-owned step input or step output being promoted. Step-owned rows must use their in-row promoted_signal_name field instead — overlay rows on step-owned definitions are rejected by clean().",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_promotions",
                to="validations.stepiodefinition",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepiopromotion",
            name="workflow_step",
            field=models.ForeignKey(
                help_text="The workflow step that owns this promotion. Same step the assertion form is editing — the overlay is workflow-scoped, not validator-scoped.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="io_promotions",
                to="workflows.workflowstep",
            ),
        ),
        migrations.RemoveField(
            model_name="validatorcatalogentry",
            name="validator",
        ),
        migrations.RemoveField(
            model_name="rulesetassertion",
            name="target_catalog_entry",
        ),
        migrations.AddConstraint(
            model_name="derivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("validator__isnull", False), ("workflow_step__isnull", True)
                    ),
                    models.Q(
                        ("validator__isnull", True), ("workflow_step__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_derivation_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="derivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("validator__isnull", False)),
                fields=("validator", "contract_key"),
                name="uq_derivation_validator_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="derivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workflow_step__isnull", False)),
                fields=("workflow_step", "contract_key"),
                name="uq_derivation_step_key",
            ),
        ),
        migrations.AddIndex(
            model_name="executionattempt",
            index=models.Index(
                fields=["state", "timeout_at"], name="validations_state_2ec69f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionattempt",
            index=models.Index(
                fields=["provider_execution_id"], name="validations_provide_664a0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                fields=("step_run", "attempt_number"), name="uq_attempt_step_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ("PENDING", "DISPATCHING", "RUNNING", "UNKNOWN"))
                ),
                fields=("step_run",),
                name="uq_attempt_one_active_per_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_execution_id", ""), _negated=True),
                fields=("runner_type", "provider_job_name", "provider_execution_id"),
                name="uq_attempt_provider_execution",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_number__gte", 1)),
                name="ck_attempt_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "PENDING",
                            "DISPATCHING",
                            "RUNNING",
                            "UNKNOWN",
                            "COMPLETED",
                            "FAILED",
                            "CANCELED",
                            "TIMED_OUT",
                        ],
                    )
                ),
                name="ck_attempt_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_finished_at__isnull", True),
                    ("provider_started_at__isnull", True),
                    ("provider_finished_at__gte", models.F("provider_started_at")),
                    _connector="OR",
                ),
                name="ck_attempt_provider_times_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="runevidenceartifact",
            index=models.Index(
                fields=["availability", "created"],
                name="validations_availab_3491fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="runevidenceartifact",
            index=models.Index(
                fields=["schema_version"], name="validations_schema__bbcd3d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stepiodefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("validator__isnull", False), ("workflow_step__isnull", True)
                    ),
                    models.Q(
                        ("validator__isnull", True), ("workflow_step__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_step_io_definition_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepiodefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("validator__isnull", False)),
                fields=("validator", "contract_key", "direction"),
                name="uq_step_io_definition_validator_key_dir",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepiodefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workflow_step__isnull", False)),
                fields=("workflow_step", "contract_key", "direction"),
                name="uq_step_io_definition_step_key_dir",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepiodefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("io_medium", "value"),
                    ("promoted_signal_name", ""),
                    _connector="OR",
                ),
                name="ck_step_io_promotion_value_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepinputbinding",
            constraint=models.UniqueConstraint(
                fields=("workflow_step", "io_definition"),
                name="uq_step_input_binding_definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstepiopromotion",
            constraint=models.UniqueConstraint(
                fields=("workflow_step", "io_definition"),
                name="uq_step_io_promotion_definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstepiopromotion",
            constraint=models.UniqueConstraint(
                fields=("workflow_step", "promoted_signal_name"),
                name="uq_step_io_promotion_name",
            ),
        ),
        migrations.DeleteModel(
            name="ValidatorCatalogEntry",
        ),
    ]
