# Generated by Django 6.0.3 on 2026-03-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0029_migrate_step_template_to_signal_definitions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulesetassertion',
            name='ck_ruleset_assertion_target_oneof',
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='target_signal_definition',
            field=models.ForeignKey(blank=True, help_text='Reference to a signal definition when targeting a known signal. Preferred over target_catalog_entry (which is deprecated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruleset_assertions', to='validations.signaldefinition'),
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_catalog_entry__isnull', True), ('target_data_path', ''), ('target_signal_definition__isnull', False)), models.Q(('target_catalog_entry__isnull', False), ('target_data_path', ''), ('target_signal_definition__isnull', True)), models.Q(('target_catalog_entry__isnull', True), ('target_signal_definition__isnull', True), models.Q(('target_data_path', ''), _negated=True)), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
    ]
