# Generated by Django 5.2.8 on 2025-11-23 22:47

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0029_fmu_checksum_modal_path'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fmivariable',
            new_name='validations_fmu_mod_69d7e9_idx',
            old_name='validations_fmivariable_fmu_model_4e1d1e_idx',
        ),
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMI Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.AlterField(
            model_name='fmivariable',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='fmivariable',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='fmumodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='fmumodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='fmuproberesult',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='fmuproberesult',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMI Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMI Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
    ]
