# Generated by Django 6.0.7 on 2026-07-23 05:22

import django.contrib.postgres.fields
import validibot.validations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0030_execution_deployment_attempt_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('SCHEMATRON', 'Schematron'), ('SHACL', 'SHACL Shapes'), ('ENERGYPLUS', 'EnergyPlus'), ('FMU', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('THERM', 'THERM'), ('TABULAR', 'Tabular'), ('PORTFOLIO_MANAGER', 'Portfolio Manager')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='supported_data_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('energyplus_idf', 'EnergyPlus IDF'), ('energyplus_epjson', 'EnergyPlus epJSON'), ('fmu', 'FMU'), ('therm_thmx', 'THERM THMX'), ('therm_thmz', 'THERM THMZ (Archive)'), ('csv', 'CSV (tabular)'), ('portfolio_manager_report', 'ENERGY STAR Portfolio Manager Report'), ('unknown', 'Unknown')], max_length=32), default=validibot.validations.models._default_validator_data_formats, help_text='Data formats this validator can parse (e.g., JSON, EnergyPlus IDF).'),
        ),
    ]
