# Generated by Django 6.0.3 on 2026-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0031_migrate_assertion_targets_to_signal_definitions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulesetassertion',
            name='ck_ruleset_assertion_target_oneof',
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_catalog_entry__isnull', True), ('target_data_path', ''), ('target_signal_definition__isnull', False)), models.Q(('target_catalog_entry__isnull', False), ('target_data_path', ''), ('target_signal_definition__isnull', True)), models.Q(('target_catalog_entry__isnull', True), ('target_signal_definition__isnull', True)), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
    ]
