# Generated by Django 5.2.8 on 2025-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0032_alter_validatorcatalogentry_run_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text="A brief summary of the validator's purpose. This description appears in lists and cards.", max_length=255),
        ),
    ]
