# Generated by Django 6.0.3 on 2026-03-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0032_relax_assertion_target_xor_for_orphans'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulesetassertion',
            name='ck_ruleset_assertion_target_oneof',
        ),
        migrations.AlterField(
            model_name='rulesetassertion',
            name='target_signal_definition',
            field=models.ForeignKey(blank=True, help_text='Reference to a signal definition when targeting a known signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruleset_assertions', to='validations.signaldefinition'),
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_data_path', ''), ('target_signal_definition__isnull', False)), ('target_signal_definition__isnull', True), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
        migrations.RemoveField(
            model_name='rulesetassertion',
            name='target_catalog_entry',
        ),
    ]
