# Generated by Django 6.0.7 on 2026-07-27 23:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0033_alter_ruleset_ruleset_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationrun",
            name="output_retention_policy",
            field=models.CharField(
                choices=[
                    ("DO_NOT_STORE", "Do not retain (purge after validation)"),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_90_DAYS", "Store for 90 days"),
                    ("STORE_1_YEAR", "Store for 1 year"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text="Snapshot of workflow's output retention policy at run time.",
                max_length=32,
            ),
        ),
    ]
