# Generated by Django 5.2.8 on 2025-11-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0033_validator_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorcatalogruleentry',
            name='catalog_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_rules', to='validations.validatorcatalogentry'),
        ),
    ]
