# Generated by Django 6.0.7 on 2026-08-02 05:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0034_alter_validationrun_output_retention_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runevidenceartifact",
            name="schema_version",
            field=models.CharField(
                help_text=(
                    "The published $schema URL for the manifest. Storing it here "
                    "lets the auditor query for runs on stale schemas without "
                    "fetching the bytes."
                ),
                max_length=64,
            ),
        ),
    ]
