# Generated by Django 6.0.3 on 2026-03-27 18:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0035_normalize_library_signal_bindings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="validationrun",
            old_name="evidence_hash",
            new_name="output_hash",
        ),
        migrations.AlterField(
            model_name="validationrun",
            name="output_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 hash of the canonical validation output record, "
                    "computed at run completion. Covers the stable workflow "
                    "context and the final run outcome."
                ),
                max_length=64,
            ),
        ),
    ]
