# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Cut the pre-launch evidence row over to the permanent receipt model."""

    dependencies = [
        ("validations", "0035_alter_runevidenceartifact_schema_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runevidenceartifact",
            name="cached_bundle_path",
        ),
        migrations.RemoveField(
            model_name="runevidenceartifact",
            name="retention_class",
        ),
        migrations.AlterField(
            model_name="runevidenceartifact",
            name="availability",
            field=models.CharField(
                choices=[
                    ("GENERATED", "Manifest generated and bytes available"),
                    (
                        "FAILED",
                        "Manifest generation failed; row records the gap",
                    ),
                ],
                default="GENERATED",
                help_text=(
                    "Generation state: GENERATED (bytes in storage) or FAILED "
                    "(generation aborted)."
                ),
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="runevidenceartifact",
            name="manifest_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 of the manifest's canonical-JSON bytes. Empty "
                    "when availability is FAILED. Signed credentials cite this "
                    "hash, so a re-fetch + re-hash detects tampering."
                ),
                max_length=64,
            ),
        ),
    ]
