# Generated by Django 5.2.8 on 2025-11-26 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0035_alter_rulesetassertion_target_catalog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetassertion',
            name='target_catalog_entry',
            field=models.ForeignKey(blank=True, help_text='Reference to a catalog entry when targeting a known signal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruleset_assertions', to='validations.validatorcatalogentry'),
        ),
    ]
