# Generated by Django 6.0.3 on 2026-03-27 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0036_rename_evidence_hash_to_output_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaldefinition",
            name="origin_kind",
            field=models.CharField(
                choices=[
                    ("catalog", "Catalog"),
                    ("fmu", "FMU"),
                    ("template", "Template"),
                ],
                help_text=(
                    "How this signal definition was created: from a validator "
                    "config declaration, an FMU probe, or a template scan."
                ),
                max_length=20,
            ),
        ),
    ]
