# Generated by Django 5.2.8 on 2025-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0036_alter_rulesetassertion_target_catalog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrun',
            name='resolved_config',
        ),
    ]
