# Generated by Django 6.0.7 on 2026-08-04

from django.db import migrations
from django.db import models
from django.db.models import Q


class Migration(migrations.Migration):
    """Add the durable workflow-definition use fence for validation runs.

    This project explicitly chose a clean data reset for this trust-boundary
    change. No historical-run backfill is attempted: clean installations start
    with the marker populated only by the new finalization lifecycle.
    """

    dependencies = [
        ("validations", "0036_remove_legacy_evidence_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrun",
            name="definition_released_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this run stopped reading its live workflow definition. "
                    "Null means semantic edits to a Mutable workflow remain fenced."
                ),
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                condition=Q(definition_released_at__isnull=True),
                fields=["workflow"],
                name="run_unreleased_workflow_idx",
            ),
        ),
    ]
