# Generated by Django 6.0.3 on 2026-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0037_alter_signaldefinition_origin_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaldefinition',
            name='signal_name',
            field=models.CharField(blank=True, default='', help_text='Optional signal name for output promotion. When set on an output-direction SignalDefinition, the output value is promoted to the s (signal) namespace in CEL expressions as s.<signal_name>. Must be a valid CEL identifier.', max_length=100),
        ),
        migrations.AlterField(
            model_name='rulesetassertion',
            name='target_data_path',
            field=models.CharField(blank=True, default='', help_text="Custom JSON-style path for validators that allow free-form targets. Supports dot notation, [index], and filter expressions (e.g., items[?@.name=='x'].value).", max_length=255),
        ),
        migrations.AlterField(
            model_name='stepsignalbinding',
            name='source_data_path',
            field=models.CharField(blank=True, default='', help_text='Path expression into the source scope. Supports dot notation (e.g., \'building.panel_area\'), [index] for arrays, and filter expressions for named elements (e.g., \'items[?@.name=="x"].value\').', max_length=500),
        ),
    ]
