# Generated by Django 6.0.3 on 2026-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0038_add_signal_name_to_signal_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsignalbinding',
            name='source_scope',
            field=models.CharField(choices=[('submission_payload', 'Submission Payload'), ('submission_metadata', 'Submission Metadata'), ('upstream_step', 'Upstream Step'), ('signal', 'Workflow Signal'), ('system', 'System')], default='submission_payload', help_text='The data scope to resolve the signal value from: submission payload, submission metadata, upstream step output, or system.', max_length=30),
        ),
    ]
