# Generated by Django 6.0 on 2025-12-08 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0039_alter_fmumodel_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_id', models.CharField(help_text='Unique callback identifier from the input envelope.', max_length=255, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When this callback was first processed.')),
                ('status', models.CharField(help_text='The validation status from the callback payload.', max_length=50)),
                ('result_uri', models.CharField(blank=True, default='', help_text='GCS URI to the output envelope.', max_length=500)),
                ('validation_run', models.ForeignKey(help_text='The validation run this callback was for.', on_delete=django.db.models.deletion.CASCADE, related_name='callback_receipts', to='validations.validationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['callback_id'], name='validations_callbac_647c8a_idx'), models.Index(fields=['validation_run'], name='validations_validat_2570c9_idx'), models.Index(fields=['received_at'], name='validations_receive_c9be3d_idx')],
            },
        ),
    ]
