# Generated by Django 6.0.3 on 2026-04-08 06:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_source_kind(apps, schema_editor):
    """Set source_kind and is_path_editable for existing signals.

    - EnergyPlus and THERM validator signals → INTERNAL, not editable
    - FMU-origin output signals → INTERNAL, not editable
    - Everything else keeps the default (PAYLOAD_PATH, editable)
    """
    SignalDefinition = apps.get_model("validations", "SignalDefinition")

    # EnergyPlus and THERM: all signals are INTERNAL + non-editable.
    # Identify by the owning validator's validation_type field.
    SignalDefinition.objects.filter(
        validator__validation_type__in=["energyplus", "therm"],
    ).update(
        source_kind="internal",
        is_path_editable=False,
    )

    # FMU-origin output signals: INTERNAL + non-editable.
    # FMU inputs remain PAYLOAD_PATH + editable (the default).
    SignalDefinition.objects.filter(
        origin_kind="fmu",
        direction="output",
    ).update(
        source_kind="internal",
        is_path_editable=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0040_backfill_signal_binding_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaldefinition',
            name='is_path_editable',
            field=models.BooleanField(default=True, help_text="Whether the workflow author can edit the source data path for this signal's step binding. False for signals where the validator controls the extraction path internally."),
        ),
        migrations.AddField(
            model_name='signaldefinition',
            name='source_kind',
            field=models.CharField(choices=[('payload_path', 'Payload Path'), ('internal', 'Internal')], default='payload_path', help_text="How the signal's value is obtained: from a known data path in the submission payload (PAYLOAD_PATH) or via the validator's own internal extraction mechanism (INTERNAL).", max_length=20),
        ),
        migrations.RunPython(
            backfill_source_kind,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='stepsignalbinding',
            name='default_value',
            field=models.JSONField(blank=True, default=None, help_text='Fallback value used when the source path resolves to nothing and the input is not marked as required.', null=True),
        ),
        migrations.AlterField(
            model_name='stepsignalbinding',
            name='signal_definition',
            field=models.ForeignKey(help_text='The validator input or output definition this binding wires up.', on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='validations.signaldefinition'),
        ),
        migrations.AlterField(
            model_name='stepsignalbinding',
            name='source_scope',
            field=models.CharField(choices=[('submission_payload', 'Submission Payload'), ('submission_metadata', 'Submission Metadata'), ('upstream_step', 'Upstream Step'), ('signal', 'Workflow Signal'), ('system', 'System')], default='submission_payload', help_text='The data scope to resolve the input value from: submission payload, submission metadata, workflow signal, upstream step output, or system.', max_length=30),
        ),
    ]
