# Generated by Django 6.0 on 2025-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0040_callback_receipt_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='error_category',
            field=models.CharField(blank=True, choices=[('VALIDATION_FAILED', 'Validation Failed'), ('TIMEOUT', 'Timed Out'), ('OOM', 'Out of Memory'), ('RUNTIME_ERROR', 'Runtime Error'), ('SYSTEM_ERROR', 'System Error')], default='', help_text='Classification of why the run failed (TIMEOUT, OOM, etc.).', max_length=32),
        ),
    ]
