# Generated by Django 6.0 on 2025-12-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_ephemeral_retention'),
        ('validations', '0041_add_error_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Can be NULL if submission record was deleted. Code accessing this field must handle the None case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='submissions.submission'),
        ),
    ]
