# Generated by Django 6.0.4 on 2026-05-01 05:27
#
# ADR-2026-04-27 Phase 3 Session B (tasks 8–9):
# Adds the ``semantic_digest`` field to ``Validator`` to enable drift
# detection. We deliberately do NOT backfill digests here because:
#
#   1. Computing digests requires importing the validator-config
#      registry, which in turn imports models — circular at migration
#      time.
#   2. The first ``sync_validators`` run after this migration deploys
#      computes the digest for every known config and populates the
#      column naturally. The drift detection in sync_validators
#      treats an empty ``semantic_digest`` as "uninitialised" and
#      allows the empty → populated transition without raising.
#
# Custom org-owned validators (``is_system=False``) are not synced
# from a ValidatorConfig at all; their ``semantic_digest`` stays
# empty by design. The audit command (Session D) reports those as
# "legacy versioning" rather than "drift".

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0041_add_source_kind_and_is_path_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="semantic_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 of the semantic config at sync time. Used to "
                    "detect drift when a validator's behavior changes under "
                    "the same (slug, version) without an explicit version "
                    "bump."
                ),
                max_length=64,
            ),
        ),
    ]
