# Generated by Django 6.0.4 on 2026-05-01 06:08
#
# ADR-2026-04-27 Phase 3 Session C (task 11):
# Adds the ``content_hash`` field to ``ValidatorResourceFile`` so the
# bytes of a catalog resource (weather files, FMU bundles, etc.) can
# be compared on every save. We deliberately do NOT backfill at
# migration time — the first ``save()`` after deploy computes and
# stores the hash for each row naturally. The drift gate in
# ``ValidatorResourceFile.save()`` treats an empty ``content_hash``
# as uninitialised and allows the empty -> populated transition.
#
# This pattern mirrors the ``semantic_digest`` rollout in Session B
# (migration 0042): trust gate sleeps until the column is populated;
# locked workflows still get protection because mutating a catalog
# file requires a save, which is when the hash gets computed and
# the drift check fires.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0042_add_validator_semantic_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="validatorresourcefile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 of the file's content, computed on save. "
                    "Used to detect drift when a catalog file "
                    "referenced by a locked workflow tries to mutate."
                ),
                max_length=64,
            ),
        ),
    ]
