# Generated by Django 6.0 on 2026-01-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0042_ephemeral_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='release_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMING_SOON', 'Coming Soon'), ('PUBLISHED', 'Published')], default='PUBLISHED', help_text='Release state for system validators. DRAFT hides the validator, COMING_SOON shows it disabled, PUBLISHED makes it fully available.', max_length=16),
        ),
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('FMI', 'FMU Validator'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
    ]
