# Generated by Django 6.0.4 on 2026-05-01 22:48
#
# ADR-2026-04-27 Phase 4 Session A (task 2):
# Adds the ``RunEvidenceArtifact`` table — one row per validation run,
# pinning the canonical-JSON manifest's path + hash + retention class.
# No backfill: existing completed runs remain manifest-less until they
# get re-finalised (rare). The auditor flags coverage gaps as
# ``MANIFEST_MISSING`` so operators see legacy state explicitly.

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models

import validibot.validations.models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0043_add_resource_content_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunEvidenceArtifact',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(help_text="The validibot.evidence.vN schema string the manifest was produced under. Verifiers parse the manifest's schema_version field at read time, but storing it here lets the auditor query for runs on stale schemas without fetching the bytes.", max_length=64)),
                ('manifest_path', models.FileField(blank=True, help_text='Path to the canonical-JSON manifest in default storage. Empty when availability is FAILED (generation never produced bytes).', max_length=500, upload_to=validibot.validations.models._evidence_manifest_upload_path)),
                ('manifest_hash', models.CharField(blank=True, default='', help_text="SHA-256 of the manifest's canonical-JSON bytes. Empty when availability is FAILED. Future signed credentials (Phase 4 Session C) cite this hash, so a re-fetch + re-hash detects tampering.", max_length=64)),
                ('cached_bundle_path', models.CharField(blank=True, default='', help_text='Phase 4 Session C: path to a cached export-bundle tarball (manifest + inputs + outputs + signature). Empty until the operator triggers an export.', max_length=500)),
                ('retention_class', models.CharField(blank=True, default='', help_text='Workflow.data_retention at the time the manifest was generated. Mirrored here so retention-sweep code can filter without joining to Workflow.', max_length=32)),
                ('availability', models.CharField(choices=[('GENERATED', 'Manifest generated and bytes available'), ('PURGED', 'Manifest bytes purged; only hash remains'), ('FAILED', 'Manifest generation failed; row records the gap')], default='GENERATED', help_text='Lifecycle state: GENERATED (bytes in storage), PURGED (only hash remains), or FAILED (generation aborted).', max_length=16)),
                ('generation_error', models.TextField(blank=True, default='', help_text='When availability is FAILED, the exception message from the manifest builder. Empty otherwise.')),
                ('run', models.OneToOneField(help_text='The validation run this manifest documents.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifact', to='validations.validationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['availability', 'created'], name='validations_availab_3491fc_idx'), models.Index(fields=['schema_version'], name='validations_schema__bbcd3d_idx')],
            },
        ),
    ]
