# Generated by Django 6.0 on 2026-01-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0043_add_validator_release_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetassertion',
            name='success_message',
            field=models.TextField(blank=True, default='', help_text='Message rendered when the assertion passes.'),
        ),
    ]
