# Generated by Django 6.0 on 2026-01-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0044_rulesetassertion_success_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetassertion',
            name='severity',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=16),
        ),
        migrations.AlterField(
            model_name='validationfinding',
            name='severity',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16),
        ),
    ]
