# Generated by Django 6.0.4 on 2026-05-02
#
# ADR-2026-04-27 Phase 5 Session A (task 1):
# Adds ``validator_backend_image_digest`` to ``ValidationStepRun`` so
# the runner can persist the resolved sha256 digest of the validator
# backend container image that executed each advanced-validator step.
#
# We deliberately do NOT backfill historical step runs here because:
#
#   1. The digest only exists at execution time — Docker / Cloud Run
#      report it as part of the live container metadata. Past runs'
#      images may have been retagged or removed from registries since.
#   2. Backfilling synthetic values would dilute the trust contract:
#      an empty string means "this step ran before digest capture
#      shipped," which is the honest signal for an auditor.
#
# Simple-validator steps (those that run inline in the Django process
# without a container) leave the field empty by construction — there
# is no backend image to digest. The evidence-manifest builder
# documents the absence so verifiers know the gap is structural, not
# a bug.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0044_add_run_evidence_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationsteprun",
            name="validator_backend_image_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Resolved sha256 digest of the validator backend image "
                    "that executed this step (e.g. 'sha256:abc...' or "
                    "'registry/path/...@sha256:abc...'). Empty for "
                    "simple-validator steps that run inline without a "
                    "container. 256 chars accommodates registry-anchored "
                    "references (registry path + image name + '@sha256:' "
                    "+ 64 hex), which commonly run 100+ chars for nested "
                    "GCS / GAR paths."
                ),
                max_length=256,
            ),
        ),
    ]
