# Generated by Django 6.0.4 on 2026-05-02
#
# ADR-2026-04-27 Phase 5 Session C (task 7):
# Adds ``trust_tier`` to ``Validator`` so the runner can apply a
# stricter sandbox profile for user-added or partner-authored
# validator backends (the future case) while leaving the existing
# Phase 1 hardening profile in place for first-party backends.
#
# Existing rows backfill to ``TIER_1`` automatically via the field's
# ``default``. We don't run a data migration because:
#
#   1. ``TIER_1`` is the right answer for every row that exists
#      today — every validator we ship is first-party.
#   2. The backfill is structural ("we built this") rather than
#      computed from per-row state, so the column default is the
#      cleanest expression of intent.
#
# When the self-service backend registration flow ships, sync_validators
# (or the registration UI) will set ``trust_tier=TIER_2`` for those
# rows explicitly.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0045_add_validator_backend_image_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="trust_tier",
            field=models.CharField(
                choices=[
                    ("TIER_1", "Tier 1 (first-party)"),
                    ("TIER_2", "Tier 2 (user-added or partner-authored)"),
                ],
                default="TIER_1",
                help_text=(
                    "Trust tier of the validator backend container this "
                    "validator dispatches to. TIER_1 is the first-party "
                    "hardening profile (default); TIER_2 applies a stricter "
                    "sandbox for user-added or partner-authored backends. "
                    "Simple validators (no backend) stay at TIER_1 by "
                    "construction."
                ),
                max_length=16,
            ),
        ),
    ]
