# Generated by Django 6.0 on 2026-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0045_alter_rulesetassertion_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='output_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When outputs should be purged (null = never expires or not yet computed).', null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='output_purged_at',
            field=models.DateTimeField(blank=True, help_text='When outputs were purged (for audit trail).', null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='output_retention_policy',
            field=models.CharField(choices=[('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_90_DAYS', 'Store for 90 days'), ('STORE_1_YEAR', 'Store for 1 year'), ('STORE_PERMANENTLY', 'Store permanently')], default='STORE_30_DAYS', help_text="Snapshot of workflow's output retention policy at run time.", max_length=32),
        ),
    ]
