# Generated by Django 6.0.4 on 2026-05-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0046_add_validator_trust_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='source',
            field=models.CharField(choices=[('LAUNCH_PAGE', 'Launch Page'), ('API', 'API'), ('MCP', 'MCP (AI Agent)'), ('X402_AGENT', 'x402 Anonymous Agent'), ('CLI', 'Command-line Interface'), ('SCHEDULE', 'Scheduled / Automation')], default='LAUNCH_PAGE', help_text='Where this run was initiated (web launch page, API, etc.).', max_length=32),
        ),
    ]
