# Generated by Django 6.0.5 on 2026-05-19 02:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0048_seed_shacl_output_signals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customvalidator",
            name="base_validation_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic Assertions"),
                    ("JSON_SCHEMA", "JSON Schema"),
                    ("XML_SCHEMA", "XML Schema"),
                    ("SHACL", "SHACL (RDF Graph)"),
                    ("ENERGYPLUS", "EnergyPlus"),
                    ("FMU", "FMU Validator"),
                    ("CUSTOM_VALIDATOR", "Custom Basic Validator"),
                    ("AI_ASSIST", "AI Assist"),
                    ("THERM", "THERM Thermal Analysis"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="ruleset_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic Assertions"),
                    ("JSON_SCHEMA", "JSON Schema"),
                    ("XML_SCHEMA", "XML Schema"),
                    ("SHACL", "SHACL Shapes"),
                    ("ENERGYPLUS", "EnergyPlus"),
                    ("FMU", "FMU Validator"),
                    ("CUSTOM_VALIDATOR", "Custom Basic Validator"),
                    ("THERM", "THERM"),
                ],
                help_text=(
                    "Type of validation ruleset, e.g. "
                    "'json_schema', 'xml_schema'"
                ),
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="rulesetassertion",
            name="assertion_type",
            field=models.CharField(
                choices=[
                    ("shacl", "SHACL"),
                    ("basic", "Basic Assertion"),
                    ("cel_expr", "CEL expression"),
                ],
                default="basic",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rulesetassertion",
            name="operator",
            field=models.CharField(
                choices=[
                    ("sparql_ask", "SPARQL ASK"),
                    ("eq", "Equals"),
                    ("ne", "Not equals"),
                    ("lt", "Less than"),
                    ("le", "Less than or equal"),
                    ("gt", "Greater than"),
                    ("ge", "Greater than or equal"),
                    ("between", "Between (range)"),
                    ("in", "Is one of"),
                    ("not_in", "Is not one of"),
                    ("subset", "Set is subset of"),
                    ("superset", "Set is superset of"),
                    ("unique", "All values unique"),
                    ("contains", "Contains"),
                    ("not_contains", "Does not contain"),
                    ("starts_with", "Starts with"),
                    ("ends_with", "Ends with"),
                    ("matches", "Matches regex"),
                    ("is_null", "Is null"),
                    ("not_null", "Is not null"),
                    ("is_empty", "Is empty"),
                    ("not_empty", "Is not empty"),
                    ("type_is", "Type is"),
                    ("len_eq", "Length equals"),
                    ("len_le", "Length ≤"),
                    ("len_ge", "Length ≥"),
                    ("count_between", "Count between"),
                    ("before", "Before"),
                    ("after", "After"),
                    ("within", "Within duration"),
                    ("approx_eq", "≈ Equals (tolerance)"),
                    ("any", "Any element satisfies"),
                    ("all", "All elements satisfy"),
                    ("none", "No element satisfies"),
                    ("cel_expr", "CEL expression"),
                ],
                default="le",
                help_text="Structured operator used for BASIC assertions.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="validation_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic Assertions"),
                    ("JSON_SCHEMA", "JSON Schema"),
                    ("XML_SCHEMA", "XML Schema"),
                    ("SHACL", "SHACL (RDF Graph)"),
                    ("ENERGYPLUS", "EnergyPlus"),
                    ("FMU", "FMU Validator"),
                    ("CUSTOM_VALIDATOR", "Custom Basic Validator"),
                    ("AI_ASSIST", "AI Assist"),
                    ("THERM", "THERM Thermal Analysis"),
                ],
                max_length=40,
            ),
        ),
    ]
