"""Align migration state with current model definitions after PR 3 rename.

Migrations 0051 (model renames via SeparateDatabaseAndState) and 0052
(add on_missing field) left two residual state drifts that
``makemigrations --check --dry-run`` correctly reports:

1. **StepInputBinding.signal_definition FK target.** Migration 0051
   renamed ``SignalDefinition`` → ``StepIODefinition`` in state, but
   Django's ``RenameModel`` inside ``SeparateDatabaseAndState`` doesn't
   update the FK reference string stored on ``StepInputBinding`` (which
   was created when the target was still called ``SignalDefinition``).
   The current model definition has the FK pointing at
   ``StepIODefinition``; this migration aligns state with that.

2. **StepIODefinition.promoted_signal_name help_text.** The
   ``signal_name`` → ``promoted_signal_name`` rename in 0051 used
   ``RenameField``, which preserves the original ``help_text``. PR 3
   rewrote the ``help_text`` on the renamed field to describe its new
   purpose (symmetric promotion per ADR-2026-05-22b). Django tracks
   ``help_text`` as model state, so the wording change generates an
   ``AlterField``.

Neither change touches the database in a meaningful way — the FK
column type stays the same and ``help_text`` isn't persisted. But
Django's state graph must reflect the current code for
``makemigrations --check`` to pass in CI.

Generated by ``python manage.py makemigrations`` per the May 2026
code review's P1 finding.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0052_stepiodefinition_on_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepinputbinding',
            name='signal_definition',
            field=models.ForeignKey(help_text='The step input definition this binding wires up.', on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='validations.stepiodefinition'),
        ),
        migrations.AlterField(
            model_name='stepiodefinition',
            name='promoted_signal_name',
            field=models.CharField(blank=True, default='', help_text='Optional name for symmetric promotion (per ADR-2026-05-22b). When set on a step input or step output, the value is promoted into the s (signal) workflow vocabulary, available in downstream steps as s.<promoted_signal_name>. Must be a valid CEL identifier.', max_length=100),
        ),
    ]
