# Generated by Django 6.0.5 on 2026-05-22 23:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0053_align_state_after_rename'),
        ('workflows', '0026_alter_workflow_version_positive_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepIOPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('promoted_signal_name', models.CharField(help_text='The workflow-vocabulary name the promoted value is exposed under (s.<promoted_signal_name>). Must be a valid CEL identifier and unique across the workflow.', max_length=100)),
                ('signal_definition', models.ForeignKey(help_text='The step input or step output being promoted. May be validator-owned (catalog row) or step-owned — though step-owned rows typically use their own in-row promoted_signal_name instead.', on_delete=django.db.models.deletion.CASCADE, related_name='step_promotions', to='validations.stepiodefinition')),
                ('workflow_step', models.ForeignKey(help_text='The workflow step that owns this promotion. Same step the assertion form is editing — the overlay is workflow-scoped, not validator-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='io_promotions', to='workflows.workflowstep')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workflow_step', 'signal_definition'), name='uq_iopromotion_step_signal')],
            },
        ),
    ]
