# Generated by Django 6.0.5 on 2026-05-23 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0054_workflowstepiopromotion'),
        ('workflows', '0026_alter_workflow_version_positive_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepiopromotion',
            name='signal_definition',
            field=models.ForeignKey(help_text='The validator-owned step input or step output being promoted. Step-owned rows must use their in-row promoted_signal_name field instead — overlay rows on step-owned definitions are rejected by clean().', on_delete=django.db.models.deletion.CASCADE, related_name='step_promotions', to='validations.stepiodefinition'),
        ),
        migrations.AddConstraint(
            model_name='workflowstepiopromotion',
            constraint=models.UniqueConstraint(fields=('workflow_step', 'promoted_signal_name'), name='uq_iopromotion_step_name'),
        ),
    ]
