# Generated by Django 6.0.5 on 2026-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0058_alter_customvalidator_base_validation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetassertion',
            name='target_data_path',
            field=models.TextField(blank=True, default='', help_text="Custom JSON-style path for validators that allow free-form targets. Supports dot notation, [index], and filter expressions (e.g., items[?@.name=='x'].value)."),
        ),
    ]
