# Generated by Django 6.0.5 on 2026-06-05 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0059_alter_rulesetassertion_target_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetassertion',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes on the rationale behind this assertion. Not shown to data submitters.', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
