# Generated by Django 6.0.6 on 2026-06-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0060_rulesetassertion_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackreceipt',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PROCESSING', help_text='Processing status of this callback receipt.', max_length=50),
        ),
    ]
