# Generated by Codex on 2026-06-24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0061_callbackreceipt_rejected_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="validation_type",
            field=models.CharField(
                help_text=(
                    "Runtime validator type string. Built-in validators use "
                    "ValidationType constants, but plugin validators may register "
                    "additional strings at startup."
                ),
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="customvalidator",
            name="base_validation_type",
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name="validator",
            name="availability_state",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MISSING_CONFIG", "Missing config"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                help_text=(
                    "Whether this validator's runtime config/class is available in "
                    "the current deployment. Missing validators remain in the DB for "
                    "history but cannot launch."
                ),
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="availability_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Operator-facing reason this validator is unavailable, if any."
                ),
            ),
        ),
        migrations.AddField(
            model_name="validator",
            name="config_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Python provider module that last synced this validator from a "
                    "ValidatorConfig. Empty means the row is not managed by plugin "
                    "config reconciliation."
                ),
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="validator",
            index=models.Index(
                fields=["availability_state", "validation_type"],
                name="val_validator_avail_type_idx",
            ),
        ),
    ]
