# Generated by Django 6.0.6 on 2026-07-02 00:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0062_dynamic_validator_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleset",
            name="ruleset_type",
            field=models.CharField(choices=[("BASIC", "Basic Assertions"), ("JSON_SCHEMA", "JSON Schema"), ("XML_SCHEMA", "XML Schema"), ("SCHEMATRON", "Schematron"), ("SHACL", "SHACL Shapes"), ("ENERGYPLUS", "EnergyPlus"), ("FMU", "FMU Validator"), ("CUSTOM_VALIDATOR", "Custom Basic Validator"), ("THERM", "THERM"), ("TABULAR", "Tabular")], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
    ]
