# Generated by Django 6.0.6 on 2026-07-10

from django.db import migrations
from django.db import models

import validibot.validations.models


class Migration(migrations.Migration):
    """Allow artifact paths to contain their organization and run UUIDs."""

    dependencies = [
        ("validations", "0063_alter_ruleset_ruleset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=validibot.validations.models.artifact_upload_to,
            ),
        ),
    ]
