# Generated by Django 6.0.7 on 2026-07-10 08:01

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations
from django.db import models

RUN_PROFILE_HELP_TEXT = (
    "Immutable execution semantics selected when this run was created."
)
CALLBACK_NONCE_HELP_TEXT = "Digest verifier for the per-attempt callback secret."
CALLBACK_ATTEMPT_HELP_TEXT = (
    "The concrete execution that produced this callback. "
    "Null only for legacy callbacks during migration."
)


class Migration(migrations.Migration):
    dependencies = [
        ("validations", "0064_alter_artifact_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrun",
            name="runtime_profile",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy execution"),
                    ("ATTEMPT_LIFECYCLE_V1", "Execution attempt lifecycle v1"),
                    ("ATTEMPT_STRICT_V1", "Strict execution attempt I/O v1"),
                    ("ATTEMPT_CONTEXT_V1", "Canonical run context v1"),
                ],
                default="LEGACY",
                editable=False,
                help_text=RUN_PROFILE_HELP_TEXT,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ExecutionAttempt",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPATCHING", "Dispatching"),
                            ("RUNNING", "Running"),
                            ("UNKNOWN", "Provider acceptance unknown"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                            ("TIMED_OUT", "Timed out"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("runner_type", models.CharField(max_length=64)),
                (
                    "contract_version",
                    models.CharField(
                        choices=[
                            ("LEGACY_URI_V1", "Legacy URI envelope v1"),
                            ("STRICT_CONTENT_V1", "Strict content-addressed v1"),
                        ],
                        default="LEGACY_URI_V1",
                        max_length=32,
                    ),
                ),
                (
                    "provider_job_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "provider_execution_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "callback_nonce_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=CALLBACK_NONCE_HELP_TEXT,
                        max_length=128,
                    ),
                ),
                (
                    "execution_bundle_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "input_envelope_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "input_envelope_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "output_envelope_uri",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                (
                    "output_envelope_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "backend_image_ref",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "backend_image_digest",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("timeout_at", models.DateTimeField(blank=True, null=True)),
                ("retry_policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("dispatch_started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_finished_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_status_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "step_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_attempts",
                        to="validations.validationsteprun",
                    ),
                ),
            ],
            options={
                "ordering": ["step_run_id", "attempt_number"],
            },
        ),
        migrations.AddField(
            model_name="callbackreceipt",
            name="execution_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text=CALLBACK_ATTEMPT_HELP_TEXT,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="callback_receipts",
                to="validations.executionattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="executionattempt",
            index=models.Index(
                fields=["state", "timeout_at"], name="validations_state_2ec69f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionattempt",
            index=models.Index(
                fields=["provider_execution_id"], name="validations_provide_664a0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                fields=("step_run", "attempt_number"), name="uq_attempt_step_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ("PENDING", "DISPATCHING", "RUNNING", "UNKNOWN"))
                ),
                fields=("step_run",),
                name="uq_attempt_one_active_per_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_execution_id", ""), _negated=True),
                fields=("runner_type", "provider_job_name", "provider_execution_id"),
                name="uq_attempt_provider_execution",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_number__gte", 1)),
                name="ck_attempt_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "PENDING",
                            "DISPATCHING",
                            "RUNNING",
                            "UNKNOWN",
                            "COMPLETED",
                            "FAILED",
                            "CANCELED",
                            "TIMED_OUT",
                        ],
                    )
                ),
                name="ck_attempt_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_finished_at__isnull", True),
                    ("provider_started_at__isnull", True),
                    ("provider_finished_at__gte", models.F("provider_started_at")),
                    _connector="OR",
                ),
                name="ck_attempt_provider_times_valid",
            ),
        ),
    ]
