# Generated by Django 5.2.8 on 2026-07-13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0066_standardize_attempt_lifecycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationrun",
            name="runtime_profile",
        ),
        migrations.RemoveField(
            model_name="validationrun",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="executionattempt",
            name="contract_version",
        ),
        migrations.AddField(
            model_name="validationsteprun",
            name="input_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Canonical contract-keyed input values resolved for this step.",
            ),
        ),
        migrations.AddField(
            model_name="validationsteprun",
            name="output_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Canonical contract-keyed output values produced by this step.",
            ),
        ),
    ]
