# Generated by Django 6.0.7 on 2026-07-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_validibot_api_keys'),
        ('validations', '0067_canonical_step_values'),
        ('workflows', '0032_split_step_config_display_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='contract_key',
            field=models.SlugField(blank=True, default='', help_text='Stable artifact output name used in steps.<step_key>.artifact.*.', max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='data_format',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='item_key',
            field=models.SlugField(blank=True, default='', help_text='Stable item key for collection artifact outputs.', max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('file', 'File'), ('directory', 'Directory'), ('archive', 'Archive'), ('dataset', 'Dataset'), ('report', 'Report'), ('log', 'Log'), ('other', 'Other')], default='file', max_length=32),
        ),
        migrations.AddField(
            model_name='artifact',
            name='manifest_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='manifest_uri',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='artifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artifact',
            name='producer_backend_image_digest',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='artifact',
            name='producer_validator_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='artifact',
            name='producer_validator_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='artifact',
            name='retention_class',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='step_run',
            field=models.ForeignKey(blank=True, help_text='Step run that produced this artifact, if step-scoped.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='validations.validationsteprun'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='storage_uri',
            field=models.CharField(blank=True, default='', help_text='Internal storage URI; never a public signed URL.', max_length=1000),
        ),
        migrations.AddField(
            model_name='artifact',
            name='workflow_step',
            field=models.ForeignKey(blank=True, help_text='Workflow step that produced this artifact, if step-scoped.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='artifact_kind',
            field=models.CharField(blank=True, choices=[('file', 'File'), ('directory', 'Directory'), ('archive', 'Archive'), ('dataset', 'Dataset'), ('report', 'Report'), ('log', 'Log'), ('other', 'Other')], default='', help_text='Artifact kind when io_medium is artifact.', max_length=32),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='data_format',
            field=models.CharField(blank=True, default='', help_text='Domain data format for artifact ports.', max_length=64),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='io_medium',
            field=models.CharField(choices=[('value', 'Value'), ('artifact', 'Artifact')], default='value', help_text='Whether this step I/O definition carries a small JSON value or a storage-backed artifact reference.', max_length=20),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='is_collection',
            field=models.BooleanField(default=False, help_text='Whether this port accepts or emits multiple artifact refs.'),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='max_items',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum artifact count for artifact ports; null means unbounded.', null=True),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='media_type',
            field=models.CharField(blank=True, default='', help_text='Expected media type for artifact ports.', max_length=128),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='min_items',
            field=models.PositiveIntegerField(default=0, help_text='Minimum artifact count for artifact ports.'),
        ),
        migrations.AddField(
            model_name='stepiodefinition',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Validator-facing role for artifact ports.', max_length=80),
        ),
        migrations.AlterField(
            model_name='stepinputbinding',
            name='source_scope',
            field=models.CharField(choices=[('submission_payload', 'Submission Payload'), ('submission_metadata', 'Submission Metadata'), ('submission_file', 'Submission File'), ('upstream_step', 'Upstream Step'), ('upstream_artifact', 'Upstream Step Artifact'), ('signal', 'Workflow Signal'), ('constant', 'Workflow Constant'), ('workflow_resource', 'Workflow Resource'), ('system', 'System')], default='submission_payload', help_text='The data scope to resolve the input value from: submission payload, submission metadata, workflow signal, upstream step output, or system.', max_length=30),
        ),
        migrations.AlterField(
            model_name='stepiodefinition',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('timeseries', 'Timeseries'), ('string', 'String'), ('boolean', 'Boolean'), ('object', 'Object'), ('artifact_ref', 'Artifact reference')], default='number', help_text='The data type of the signal value.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['step_run', 'contract_key'], name='validations_step_ru_7b9ffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_step__isnull', False), models.Q(('contract_key', ''), _negated=True), ('item_key', '')), fields=('validation_run', 'workflow_step', 'contract_key'), name='uq_artifact_run_step_key'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_step__isnull', False), models.Q(('contract_key', ''), _negated=True), models.Q(('item_key', ''), _negated=True)), fields=('validation_run', 'workflow_step', 'contract_key', 'item_key'), name='uq_artifact_run_step_item'),
        ),
    ]
