# Generated by Django 6.0.7 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0068_step_artifact_refs_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepiodefinition",
            name="accepted_data_formats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Accepted domain data formats for artifact ports.",
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="accepted_media_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Accepted media/MIME types for artifact ports.",
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="allowed_source_scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Binding source scopes allowed for artifact ports.",
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="default_source_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted_file_first", "Submitted file first"),
                    (
                        "submitted_file_then_default_resource",
                        "Submitted file then default resource",
                    ),
                    ("workflow_resource_default", "Workflow resource default"),
                    (
                        "upstream_artifact_suggestion",
                        "Upstream artifact suggestion",
                    ),
                    ("manual", "Manual"),
                    ("none", "None"),
                ],
                default="none",
                help_text="Default source-selection strategy for artifact input ports.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="envelope_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("input_files", "Input files"),
                    ("resource_files", "Resource files"),
                    ("output_artifacts", "Output artifacts"),
                ],
                default="",
                help_text="Envelope channel this artifact port renders into.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="stepiodefinition",
            name="resource_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resource type for artifact ports rendered as resource_files.",
                max_length=64,
            ),
        ),
    ]
