# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignedCertificateAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.action')),
                ('certificate_template', models.FileField(blank=True, upload_to='actions/certificates/')),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='SlackMessageAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.action')),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text="Bootstrap icon class to render when displaying the action (e.g. 'bi-slack').", max_length=100)),
                ('action_category', models.CharField(choices=[('INTEGRATION', 'Integration'), ('CERTIFICATION', 'Certification')], max_length=32)),
                ('type', models.CharField(help_text='Implementation type identifier (e.g. SLACK_MESSAGE).', max_length=64)),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='Optional JSON schema describing the configuration for this action.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['action_category', 'name'],
                'unique_together': {('action_category', 'type')},
            },
        ),
        migrations.AddField(
            model_name='action',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='actions.actiondefinition'),
        ),
    ]
