# Generated by Django 6.0.7 on 2026-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="failure_mode",
            field=models.CharField(
                choices=[("BLOCKING", "Blocking"), ("ADVISORY", "Advisory")],
                default="BLOCKING",
                help_text="How this action's failure affects the run. BLOCKING: run fails. ADVISORY: step is marked failed but the run may still succeed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="actiondefinition",
            name="required_commercial_feature",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Commercial feature flag required for this action to appear in the step picker (e.g. 'signed_credentials'). Leave blank for actions available to all installations.",
                max_length=64,
            ),
        ),
    ]
