# Generated by Django 6.0.3 on 2026-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_rename_signed_certificate_to_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='failure_mode',
            field=models.CharField(choices=[('BLOCKING', 'Blocking'), ('ADVISORY', 'Advisory')], default='BLOCKING', help_text="How this action's failure affects the run. BLOCKING: run fails. ADVISORY: step is marked failed but the run may still succeed.", max_length=16),
        ),
    ]
