# Generated by Django 6.0.3 on 2026-03-25 05:34

from django.db import migrations, models


def set_credential_feature_flag(apps, schema_editor):
    """Backfill the required_feature on the signed credential definition."""
    ActionDefinition = apps.get_model("actions", "ActionDefinition")
    ActionDefinition.objects.filter(
        slug="certification-signed-credential",
    ).update(required_feature="signed_badges")


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_add_failure_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondefinition',
            name='required_feature',
            field=models.CharField(blank=True, default='', help_text="Commercial feature flag required for this action to appear in the step picker (e.g. 'signed_badges'). Leave blank for actions available to all installations.", max_length=64),
        ),
        migrations.RunPython(
            set_credential_feature_flag,
            migrations.RunPython.noop,
        ),
    ]
