# Generated by Django 6.0.3 on 2026-03-25 06:01

from django.db import migrations


def backfill_credential_actions_to_advisory(apps, schema_editor):
    """Set existing signed credential actions to ADVISORY failure mode.

    Migration 0003 introduced failure_mode with default='BLOCKING' for
    all actions.  That's correct for most action types, but signed
    credential actions should be ADVISORY per the ADR — issuance errors
    must not block an otherwise successful validation run.

    This backfill targets only SignedCredentialAction rows (which use
    multi-table inheritance from Action), updating their base Action
    row's failure_mode to 'ADVISORY'.
    """
    Action = apps.get_model("actions", "Action")
    ActionDefinition = apps.get_model("actions", "ActionDefinition")

    # Find the signed credential definition
    credential_defn_ids = ActionDefinition.objects.filter(
        type="SIGNED_CREDENTIAL",
    ).values_list("pk", flat=True)

    # Update all actions linked to that definition
    updated = Action.objects.filter(
        definition_id__in=credential_defn_ids,
        failure_mode="BLOCKING",
    ).update(failure_mode="ADVISORY")

    if updated:
        print(f"  Backfilled {updated} signed credential action(s) to ADVISORY.")


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_add_required_feature"),
    ]

    operations = [
        migrations.RunPython(
            backfill_credential_actions_to_advisory,
            migrations.RunPython.noop,
        ),
    ]
