# Generated by Django 6.0.3 on 2026-03-25 06:01

"""Keep the historical migration slot after credential ownership moved to Pro."""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_add_required_commercial_feature"),
    ]

    operations = []
