# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.utils.timezone
import model_utils.fields
import simplevalidations.submissions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Optional descriptive name.', max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('input_file', models.FileField(blank=True, help_text='The file to validate, e.g. IDF, JSON, XML, etc.', null=True, upload_to=simplevalidations.submissions.models.submission_input_file_upload_to)),
                ('file_type', models.CharField(choices=[('application/json', 'JSON'), ('application/xml', 'XML'), ('text/plain', 'Plain Text'), ('text/x-idf', 'EnergyPlus IDF File'), ('UNKNOWN', 'Unknown')], max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
