# Generated by Django 5.1.11 on 2025-09-04 03:05

import django_extensions.db.fields
import simplevalidations.submissions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Optional descriptive name.', max_length=256)),
                ('document', models.TextField(blank=True, default='')),
                ('input_file', models.FileField(blank=True, help_text='The file to validate, e.g. IDF, JSON, XML, etc.', null=True, upload_to=simplevalidations.submissions.models.submission_input_file_upload_to)),
                ('file_type', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML'), ('ENERGYPLUS_IDF', 'EnergyPlus IDF File'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
