# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('submissions', '0001_initial'),
        ('users', '0002_alter_organization_options_user_avatar_user_bio_and_more'),
        ('validations', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='latest_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='submission',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow *version* to run.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='workflows.workflow'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org', 'project', 'workflow', 'created'], name='submissions_org_id_7cc029_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org', 'created'], name='submissions_org_id_a2388d_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), models.Q(('input_file__isnull', False), models.Q(('input_file', ''), _negated=True)), _connector='OR'), name='submission_content_present'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), ('input_file__isnull', False), models.Q(('input_file', ''), _negated=True), _negated=True), name='submission_content_not_both'),
        ),
    ]
