# Generated by Django 5.1.11 on 2025-09-04 03:05

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extra_data', models.JSONField(blank=True, help_text='Optional additional data related to the event.', null=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('BUTTON_CLICK', 'Button Click'), ('FORM_SUBMIT', 'Form Submit'), ('FILE_DOWNLOAD', 'File Download'), ('CUSTOM_EVENT', 'Custom Event')], max_length=100)),
            ],
        ),
    ]
