# Generated by Django 5.1.11 on 2025-08-22 02:46

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_organization_user_current_org_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extra_data', models.JSONField(blank=True, help_text='Optional additional data related to the event.', null=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('file_download', 'File Download'), ('custom_event', 'Custom Event')], max_length=100)),
                ('org', models.ForeignKey(help_text='The organization this event is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='users.organization')),
                ('project', models.ForeignKey(help_text='The project this event is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'event_type'], name='tracking_tr_project_af103e_idx')],
            },
        ),
    ]
