# Generated by Django 5.1.11 on 2025-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('BUTTON_CLICK', 'Button Click'), ('FORM_SUBMIT', 'Form Submit'), ('FILE_DOWNLOAD', 'File Download'), ('CUSTOM_EVENT', 'Custom Event')], max_length=100),
        ),
    ]
