from django.urls import path

from validibot.validations import views

app_name = "validations"

urlpatterns = [
    path(
        "library/",
        views.ValidationLibraryView.as_view(),
        name="validation_library",
    ),
    path(
        "library/fmi/new/",
        views.FMIValidatorCreateView.as_view(),
        name="fmi_validator_create",
    ),
    path(
        "library/fmi/<int:pk>/probe/",
        views.FMIProbeStartView.as_view(),
        name="fmi_probe_start",
    ),
    path(
        "library/fmi/<int:pk>/probe/status/",
        views.FMIProbeStatusView.as_view(),
        name="fmi_probe_status",
    ),
    path(
        "library/custom/new/",
        views.CustomValidatorCreateView.as_view(),
        name="custom_validator_create",
    ),
    path(
        "library/custom/<slug:slug>/edit/",
        views.CustomValidatorUpdateView.as_view(),
        name="custom_validator_update",
    ),
    path(
        "library/custom/<slug:slug>/delete/",
        views.CustomValidatorDeleteView.as_view(),
        name="custom_validator_delete",
    ),
    path(
        "library/custom/<slug:slug>/",
        views.ValidatorDetailView.as_view(),
        name="validator_detail",
    ),
    path(
        "library/custom/<slug:slug>/signals/",
        views.ValidatorSignalsListView.as_view(),
        name="validator_signals_list",
    ),
    path(
        "library/custom/<slug:slug>/signals-tab/",
        views.ValidatorSignalsTabView.as_view(),
        name="validator_signals_tab",
    ),
    path(
        "library/custom/<slug:slug>/assertions/",
        views.ValidatorAssertionsTabView.as_view(),
        name="validator_assertions_tab",
    ),
    path(
        "library/custom/<slug:slug>/assertions/modal/",
        views.ValidatorDefaultAssertionsView.as_view(),
        name="validator_default_assertions",
    ),
    path(
        "library/custom/<slug:slug>/resource-files/",
        views.ValidatorResourceFilesTabView.as_view(),
        name="validator_resource_files",
    ),
    path(
        "library/custom/<int:pk>/resource-files/new/",
        views.ResourceFileCreateView.as_view(),
        name="resource_file_create",
    ),
    path(
        "library/custom/<int:pk>/resource-files/<uuid:rf_pk>/edit/",
        views.ResourceFileUpdateView.as_view(),
        name="resource_file_update",
    ),
    path(
        "library/custom/<int:pk>/resource-files/<uuid:rf_pk>/delete/",
        views.ResourceFileDeleteView.as_view(),
        name="resource_file_delete",
    ),
    path(
        "library/custom/<int:pk>/signals/new/",
        views.ValidatorSignalCreateView.as_view(),
        name="validator_signal_create",
    ),
    path(
        "library/custom/<int:pk>/signals/<int:entry_pk>/edit/",
        views.ValidatorSignalUpdateView.as_view(),
        name="validator_signal_update",
    ),
    path(
        "library/custom/<int:pk>/signals/<int:entry_pk>/delete/",
        views.ValidatorSignalDeleteView.as_view(),
        name="validator_signal_delete",
    ),
    path(
        "library/custom/<int:pk>/rules/",
        views.ValidatorRuleListView.as_view(),
        name="validator_rules",
    ),
    path(
        "library/custom/<int:pk>/rules/new/",
        views.ValidatorRuleCreateView.as_view(),
        name="validator_rule_create",
    ),
    path(
        "library/custom/<int:pk>/rules/<int:rule_pk>/edit/",
        views.ValidatorRuleUpdateView.as_view(),
        name="validator_rule_update",
    ),
    path(
        "library/custom/<int:pk>/rules/<int:rule_pk>/move/",
        views.ValidatorRuleMoveView.as_view(),
        name="validator_rule_move",
    ),
    path(
        "library/custom/<int:pk>/rules/<int:rule_pk>/delete/",
        views.ValidatorRuleDeleteView.as_view(),
        name="validator_rule_delete",
    ),
    path(
        "",
        views.ValidationRunListView.as_view(),
        name="validation_list",
    ),
    path(
        "my-runs/",
        views.GuestValidationRunListView.as_view(),
        name="guest_validation_list",
    ),
    path(
        "<uuid:pk>/",
        views.ValidationRunDetailView.as_view(),
        name="validation_detail",
    ),
    path(
        "<uuid:pk>/delete/",
        views.ValidationRunDeleteView.as_view(),
        name="validation_delete",
    ),
    path(
        "catalog-entry/<int:entry_pk>/",
        views.CatalogEntryDetailView.as_view(),
        name="catalog_entry_detail",
    ),
]
