from django.urls import path

from . import views

app_name = "marketing"
urlpatterns = [
    path(
        "",
        views.HomePageView.as_view(),
        name="home",
    ),
    path(
        "about/",
        views.AboutPageView.as_view(),
        name="about",
    ),
    path(
        "features/",
        views.FeaturesPageView.as_view(),
        name="features",
    ),
    path(
        "pricing/",
        views.PricingPageView.as_view(),
        name="pricing",
    ),
    path(
        "resources/",
        views.ResourcesPageView.as_view(),
        name="resources",
    ),
    path(
        "resources/docs/",
        views.DocsPageView.as_view(),
        name="resources_docs",
    ),
    path(
        "resources/blog/",
        views.BlogPageView.as_view(),
        name="resources_blog",
    ),
    path(
        "resources/youtube/",
        views.YoutubePageView.as_view(),
        name="resources_youtube",
    ),
    path(
        "resources/changelog/",
        views.ChangelogPageView.as_view(),
        name="resources_changelog",
    ),
    path(
        "faq/",
        views.FAQPageView.as_view(),
        name="faq",
    ),
    path(
        "contact/",
        views.ContactPageView.as_view(),
        name="contact",
    ),
    path(
        "support/help-center/",
        views.HelpCenterPageView.as_view(),
        name="help_center",
    ),
    path(
        "support/status/",
        views.StatusPageView.as_view(),
        name="status",
    ),
    path(
        "terms/",
        views.TermsPageView.as_view(),
        name="terms",
    ),
    path(
        "privacy/",
        views.PrivacyPageView.as_view(),
        name="privacy",
    ),
]
