# Generated by Django 5.2.7 on 2025-10-10 00:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the organization, e.g. 'My Organization'", max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_personal', models.BooleanField(default=False, help_text='Indicates if this organization is a personal workspace for a user.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('AUTHOR', 'Author'), ('EXECUTOR', 'Executor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('avatar', models.ImageField(blank=True, help_text='Square image works best across the app.', null=True, upload_to='avatars/')),
                ('job_title', models.CharField(blank=True, default='', max_length=128, verbose_name='Job title')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Company')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Location')),
                ('timezone', models.CharField(blank=True, default='', max_length=64, verbose_name='Timezone')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_org', models.ForeignKey(blank=True, help_text='Organization the user is currently working in (can be changed by user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='users.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orgs',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.Membership', to='users.organization'),
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='users.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='users.role')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='memberships', through='users.MembershipRole', to='users.role'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['membership', 'role'], name='users_membe_members_233ca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershiprole',
            unique_together={('membership', 'role')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['org', 'user'], name='users_membe_org_id_3dab85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'org')},
        ),
    ]
