# Generated by Django 6.0.2 on 2026-02-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='The trial duration in days, snapshotted when the trial was activated. NULL for non-trial orgs.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text="When this organization's trial expires. NULL means no trial (community/self-hosted or paid subscription).", null=True),
        ),
    ]
