# Generated by Django 5.2.7 on 2025-11-13 02:16

from django.db import migrations


def grant_all_roles_to_owners(apps, schema_editor):
    Membership = apps.get_model("users", "Membership")
    Role = apps.get_model("users", "Role")
    MembershipRole = apps.get_model("users", "MembershipRole")
    # Ensure related managers are available before iterating
    from validibot.users.constants import RoleCode

    roles_by_code = {}
    for role in RoleCode:
        db_role, _ = Role.objects.get_or_create(
            code=role.value,
            defaults={
                "name": role.label,
            },
        )
        roles_by_code[role.value] = db_role

    owner_memberships = (
        Membership.objects.filter(
            membership_roles__role__code=RoleCode.OWNER,
            is_active=True,
        )
        .distinct()
    )
    for membership in owner_memberships.iterator():
        for role in roles_by_code.values():
            MembershipRole.objects.get_or_create(
                membership=membership,
                role=role,
            )


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_code'),
    ]

    operations = [
        migrations.RunPython(grant_all_roles_to_owners, noop),
    ]
