# Generated by Django 6.0.7 on 2026-07-16 05:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_wipe_pre_encryption_authenticators"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allow_authors_to_adjust_access",
            field=models.BooleanField(
                default=False,
                help_text="When off (the default), only admins and superusers can change a workflow's access settings. When on, workflow authors may also adjust the per-workflow access controls — never the org-level ceilings above.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="mcp_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Whether workflows in this organization may be exposed to authenticated AI agents via MCP. Off by default; an admin opts in.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="workflow_visibility_cap",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private — only you and people you invite"),
                    ("ORG", "Your organization"),
                    ("ALL_USERS", "All Validibot users"),
                ],
                default="ALL_USERS",
                help_text="Maximum visibility any workflow in this organization may have. Workflows may be set no wider than this ceiling.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="x402_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Whether workflows in this organization may be published for paid anonymous access via x402. Off by default — enabling it permits a workflow to be made callable by anyone on the internet who pays.",
            ),
        ),
        migrations.CreateModel(
            name="ValidibotAPIKey",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("label", models.CharField(default="Personal API key", max_length=120)),
                ("format_version", models.PositiveSmallIntegerField(default=1)),
                ("digest_version", models.PositiveSmallIntegerField(default=1)),
                ("secret_digest", models.CharField(max_length=64)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rotated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotations",
                        to="users.validibotapikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at", "expires_at"],
                        name="users_valid_user_id_8ee81c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("format_version", "digest_version", "secret_digest"),
                        name="uq_vb_api_key_digest",
                    )
                ],
            },
        ),
    ]
