# Generated by Django 6.0.6 on 2026-06-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_kind_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_authors_to_adjust_access',
            field=models.BooleanField(default=False, help_text="When off (the default), only admins and superusers can change a workflow's access settings. When on, workflow authors may also adjust the per-workflow access controls — never the org-level ceilings above."),
        ),
        migrations.AddField(
            model_name='organization',
            name='mcp_allowed',
            field=models.BooleanField(default=False, help_text='Whether workflows in this organization may be exposed to authenticated AI agents via MCP. Off by default; an admin opts in.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='workflow_visibility_cap',
            field=models.CharField(choices=[('PRIVATE', 'Private — only you and people you invite'), ('ORG', 'Your organization'), ('ALL_USERS', 'All Validibot users')], default='ALL_USERS', help_text='Maximum visibility any workflow in this organization may have. Workflows may be set no wider than this ceiling.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='x402_allowed',
            field=models.BooleanField(default=False, help_text='Whether workflows in this organization may be published for paid anonymous access via x402. Off by default — enabling it permits a workflow to be made callable by anyone on the internet who pays.'),
        ),
    ]
