# Generated by Django 6.0.7 on 2026-07-14 00:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_organization_allow_authors_to_adjust_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidibotAPIKey',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(default='Personal API key', max_length=120)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('digest_version', models.PositiveSmallIntegerField(default=1)),
                ('secret_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations', to='users.validibotapikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='users_valid_user_id_8ee81c_idx')],
                'constraints': [models.UniqueConstraint(fields=('format_version', 'digest_version', 'secret_digest'), name='uq_vb_api_key_digest')],
            },
        ),
    ]
