# Generated by Django 6.0 on 2026-01-07 03:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_invite'),
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInvite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('roles', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_member_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_member_invites', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invites', to='users.organization')),
            ],
            options={
                'verbose_name': 'member invite',
                'verbose_name_plural': 'member invites',
                'db_table': 'users_memberinvite',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='PendingInvite',
        ),
    ]
