# Generated by Django 5.1.11 on 2025-09-10 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membership_user'),
        ('validations', '0003_alter_validationsteprun_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ruleset',
            name='uq_ruleset_org_type_name_version',
        ),
        migrations.RemoveIndex(
            model_name='ruleset',
            name='validations_org_id_a91fb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='validator',
            name='validations_type_9c7af0_idx',
        ),
        migrations.RenameField(
            model_name='ruleset',
            old_name='type',
            new_name='ruleset_type',
        ),
        migrations.RenameField(
            model_name='validator',
            old_name='type',
            new_name='validation_type',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='validator',
            name='version',
            field=models.CharField(blank=True, default='', help_text="Version label for this validator (e.g. '2020-12', '1.0').", max_length=40),
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['org', 'ruleset_type'], name='validations_org_id_617f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['validation_type', 'slug'], name='validations_validat_379228_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('org', 'ruleset_type', 'name', 'version'), name='uq_ruleset_org_ruleset_type_name_version'),
        ),
    ]
