# Generated by Django 5.2.7 on 2025-11-05 05:26

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_code'),
        ('validations', '0003_ruleset_rules_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='is_system',
            field=models.BooleanField(default=True, help_text='True when the validator ships with the platform.'),
        ),
        migrations.AddField(
            model_name='validator',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Owning organization for custom validators (null for system validators).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='users.organization'),
        ),
        migrations.CreateModel(
            name='CustomValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('custom_type', models.CharField(choices=[('MODELICA', 'Modelica'), ('PYWINCALC', 'PyWinCalc')], max_length=32)),
                ('base_validation_type', models.CharField(choices=[('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules'), ('AI_ASSIST', 'AI Assist')], max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_validators', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_validator_configs', to='users.organization')),
                ('validator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_validator', to='validations.validator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('org', 'custom_type', 'validator'), name='uq_custom_validator_org_type_validator')],
            },
        ),
        migrations.CreateModel(
            name='ValidatorCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entry_type', models.CharField(choices=[('signal_input', 'Signal (Input)'), ('signal_output', 'Signal (Output)'), ('derivation', 'Derivation')], max_length=32)),
                ('slug', models.SlugField(help_text='Unique identifier for this catalog entry within the validator.', max_length=255)),
                ('label', models.CharField(help_text='Human-friendly label shown in editors.', max_length=255)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('timeseries', 'Timeseries'), ('string', 'String'), ('boolean', 'Boolean'), ('object', 'Object')], default='number', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('binding_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific binding metadata.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional UI metadata (example units, tags, etc.).')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this entry must be present for every ruleset.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='validations.validator')),
            ],
            options={
                'ordering': ['order', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('validator', 'entry_type', 'slug'), name='uq_validator_catalog_entry')],
            },
        ),
    ]
