# Generated by Django 5.2.7 on 2025-11-05 07:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_ruleset_validator_validator_is_system_validator_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesetAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assertion_type', models.CharField(choices=[('threshold_max', 'Must Be ≤ Value'), ('threshold_min', 'Must Be ≥ Value')], default='threshold_max', max_length=64)),
                ('target_slug', models.CharField(help_text='Catalog slug this assertion references.', max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=16)),
                ('when_expression', models.TextField(blank=True, default='', help_text='Optional CEL expression gating when the assertion evaluates.')),
                ('definition', models.JSONField(blank=True, default=dict, help_text='Assertion specific payload (threshold config, values, etc.).')),
                ('message_template', models.TextField(blank=True, default='', help_text='Message rendered when the assertion fails.')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='validations.ruleset')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
