# Generated by Django 5.2.7 on 2025-11-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0005_rulesetassertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalidator',
            name='custom_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('MODELICA', 'Modelica'), ('KERML', 'KerML')], max_length=32),
        ),
    ]
