# Generated by Django 5.2.7 on 2025-11-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0006_alter_customvalidator_custom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesetassertion',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='rulesetassertion',
            name='target_slug',
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='cel_cache',
            field=models.TextField(blank=True, default='', help_text='Normalized CEL preview generated from the stored payload.'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('lt', 'Less than'), ('le', 'Less than or equal'), ('gt', 'Greater than'), ('ge', 'Greater than or equal'), ('between', 'Between (range)'), ('in', 'Is one of'), ('not_in', 'Is not one of'), ('subset', 'Set is subset of'), ('superset', 'Set is superset of'), ('unique', 'All values unique'), ('contains', 'Contains'), ('not_contains', 'Does not contain'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('matches', 'Matches regex'), ('is_null', 'Is null'), ('not_null', 'Is not null'), ('is_empty', 'Is empty'), ('not_empty', 'Is not empty'), ('type_is', 'Type is'), ('len_eq', 'Length equals'), ('len_le', 'Length ≤'), ('len_ge', 'Length ≥'), ('count_between', 'Count between'), ('before', 'Before'), ('after', 'After'), ('within', 'Within duration'), ('approx_eq', '≈ Equals (tolerance)'), ('any', 'Any element satisfies'), ('all', 'All elements satisfy'), ('none', 'No element satisfies'), ('cel_expr', 'CEL expression')], default='le', help_text='Structured operator used for BASIC assertions.', max_length=32),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Operator options (inclusive bounds, tolerance metadata, case folding, etc.).'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='rhs',
            field=models.JSONField(blank=True, default=dict, help_text='Operator payload (values, range bounds, regex pattern, etc.).'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='spec_version',
            field=models.PositiveIntegerField(default=1, help_text='Schema version for `rhs` and `options` payloads.'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='target_catalog',
            field=models.ForeignKey(blank=True, help_text='Reference to a catalog entry when targeting a known signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruleset_assertions', to='validations.validatorcatalogentry'),
        ),
        migrations.AddField(
            model_name='rulesetassertion',
            name='target_field',
            field=models.CharField(blank=True, default='', help_text='Custom JSON-style path for validators that allow free-form targets.', max_length=255),
        ),
        migrations.AddField(
            model_name='validator',
            name='allow_custom_assertion_targets',
            field=models.BooleanField(default=False, help_text='Allow authors to enter assertion targets not present in the catalog.'),
        ),
        migrations.AlterField(
            model_name='rulesetassertion',
            name='assertion_type',
            field=models.CharField(choices=[('basic', 'Basic Assertion'), ('cel_expr', 'CEL expression')], default='basic', max_length=32),
        ),
        migrations.AddIndex(
            model_name='rulesetassertion',
            index=models.Index(fields=['ruleset', 'order'], name='validations_ruleset_2ba147_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesetassertion',
            index=models.Index(fields=['operator'], name='validations_operato_8efc76_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_catalog__isnull', False), ('target_field', '')), models.Q(('target_catalog__isnull', True), models.Q(('target_field', ''), _negated=True)), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
    ]
