# Generated by Django 5.2.7 on 2025-11-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0007_remove_rulesetassertion_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
    ]
