# Generated by Django 5.1.11 on 2025-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0008_remove_validationsteprun_uq_step_run_run_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='error',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
