# Generated by Django 5.2.7 on 2025-11-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0009_set_basic_validator_custom_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
    ]
