# Generated by Django 5.2.6 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0009_alter_validationrun_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
