# Generated by Django 5.2.6 on 2025-10-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0010_alter_validationrun_error'),
        ('workflows', '0004_alter_workflow_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='validationfinding',
            name='validations_step_ru_a534f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='validationfinding',
            name='validations_step_ru_db8e9d_idx',
        ),
        migrations.RenameField(
            model_name='validationfinding',
            old_name='run',
            new_name='validation_run',
        ),
        migrations.RenameField(
            model_name='validationfinding',
            old_name='step_run',
            new_name='validation_step_run',
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_runs', to='workflows.workflow'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'severity'], name='validations_validat_8354a9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_step_run', 'code'], name='validations_validat_a1aede_idx'),
        ),
    ]
