# Generated by Django 5.2.6 on 2025-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0012_add_ai_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Relative ordering for display purposes.'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
    ]
