# Generated by Django 5.2.7 on 2025-11-11 00:25

import django.contrib.postgres.fields
import simplevalidations.validations.models
from django.db import migrations, models

from simplevalidations.submissions.constants import SubmissionFileType
from simplevalidations.validations.constants import ValidationType


FILE_TYPE_DEFAULTS = {
    ValidationType.BASIC: [
        SubmissionFileType.JSON,
        SubmissionFileType.XML,
        SubmissionFileType.TEXT,
        SubmissionFileType.YAML,
    ],
    ValidationType.JSON_SCHEMA: [SubmissionFileType.JSON],
    ValidationType.XML_SCHEMA: [SubmissionFileType.XML],
    ValidationType.ENERGYPLUS: [
        SubmissionFileType.TEXT,
        SubmissionFileType.JSON,
    ],
    ValidationType.CUSTOM_VALIDATOR: [
        SubmissionFileType.JSON,
        SubmissionFileType.TEXT,
    ],
    ValidationType.AI_ASSIST: [
        SubmissionFileType.JSON,
        SubmissionFileType.TEXT,
    ],
}


def seed_validator_file_types(apps, schema_editor):
    Validator = apps.get_model("validations", "Validator")
    for validator in Validator.objects.all():
        defaults = FILE_TYPE_DEFAULTS.get(
            validator.validation_type,
            [SubmissionFileType.JSON],
        )
        validator.supported_file_types = list(defaults)
        validator.save(update_fields=["supported_file_types"])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0012_validator_processor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='supported_file_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('binary', 'Binary'), ('UNKNOWN', 'Unknown')], max_length=32), default=simplevalidations.validations.models._default_validator_file_types, help_text='Logical file types this validator can process (JSON, XML, text, etc.).', size=None),
        ),
        migrations.RunPython(seed_validator_file_types, noop),
    ]
