# Generated by Django 5.2.6 on 2025-10-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0013_validator_order_alter_validator_validation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validator',
            options={'ordering': ['order', 'name']},
        ),
    ]
