# Generated by Django 5.2.7 on 2025-11-12 22:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0013_validator_supported_file_types'),
        ('workflows', '0010_workflow_allowed_file_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRunStepSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('step_name', models.CharField(blank=True, default='', max_length=255)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['step_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRunSummary',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary_record', serialize=False, to='validations.validationrun')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMED_OUT', 'Timed Out')], default='PENDING', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('assertion_failure_count', models.PositiveIntegerField(default=0)),
                ('assertion_total_count', models.PositiveIntegerField(default=0)),
                ('extras', models.JSONField(blank=True, default=dict, help_text='Optional metadata for reporting (for example exemplar messages).')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='validationfinding',
            name='ruleset_assertion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='validations.rulesetassertion'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['validation_run', 'severity'], name='validations_validat_288fdf_idx'),
        ),
        migrations.AddField(
            model_name='validationrunstepsummary',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_summaries', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='validationrunstepsummary',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='validations.validationrunsummary'),
        ),
        migrations.AddIndex(
            model_name='validationrunstepsummary',
            index=models.Index(fields=['summary', 'status'], name='validations_summary_fe9733_idx'),
        ),
    ]
