# Generated by Django 5.2.7 on 2025-11-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0015_rename_validationrunstepsummary_validationsteprunsummary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationfinding',
            options={'ordering': [models.Case(models.When(severity='ERROR', then=models.Value(0)), models.When(severity='WARNING', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), '-created']},
        ),
    ]
