# Generated by Django 5.2.7 on 2025-11-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0016_alter_validationfinding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='source',
            field=models.CharField(choices=[('LAUNCH_PAGE', 'Launch Page'), ('API', 'API')], default='LAUNCH_PAGE', help_text='Where this run was initiated (web launch page, API, etc.).', max_length=32),
        ),
    ]
