# Generated by Django 5.2.7 on 2025-11-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0017_validationrun_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='short_description',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional short description of this validation run.',
                max_length=255,
            ),
        ),
    ]
