# Generated by Django 5.2.7 on 2025-11-18 21:50

import django.contrib.postgres.fields
import simplevalidations.validations.models
from django.db import migrations, models


VALIDATION_TYPE_DATA_FORMAT_DEFAULTS = {
    "BASIC": ["json"],
    "JSON_SCHEMA": ["json"],
    "XML_SCHEMA": ["xml"],
    "ENERGYPLUS": ["energyplus_idf", "energyplus_epjson"],
    "CUSTOM_VALIDATOR": ["json", "text"],
    "AI_ASSIST": ["json", "text"],
}

DATA_FORMAT_FILE_TYPE_MAP = {
    "json": ["json", "text"],
    "xml": ["xml", "text"],
    "text": ["text"],
    "yaml": ["yaml", "text"],
    "energyplus_idf": ["text"],
    "energyplus_epjson": ["json", "text"],
    "fmu": ["binary"],
    "unknown": ["UNKNOWN"],
}


def _file_types_for_formats(data_formats: list[str]) -> list[str]:
    seen: list[str] = []
    for fmt in data_formats or []:
        for ft in DATA_FORMAT_FILE_TYPE_MAP.get(fmt, []):
            if ft not in seen:
                seen.append(ft)
    return seen


def forwards(apps, schema_editor):
    Validator = apps.get_model("validations", "Validator")
    for validator in Validator.objects.all():
        data_formats = VALIDATION_TYPE_DATA_FORMAT_DEFAULTS.get(
            validator.validation_type,
            ["json"],
        )
        validator.supported_data_formats = data_formats
        derived_file_types = _file_types_for_formats(data_formats)
        if derived_file_types:
            current = list(validator.supported_file_types or [])
            for ft in derived_file_types:
                if ft not in current:
                    current.append(ft)
            validator.supported_file_types = current
        validator.save(
            update_fields=[
                "supported_data_formats",
                "supported_file_types",
            ],
        )


def backwards(apps, schema_editor):
    Validator = apps.get_model("validations", "Validator")
    Validator.objects.update(supported_data_formats=[])


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0019_alter_customvalidator_base_validation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='supported_data_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('energyplus_idf', 'EnergyPlus IDF'), ('energyplus_epjson', 'EnergyPlus epJSON'), ('fmu', 'FMU'), ('unknown', 'Unknown')], max_length=32), default=simplevalidations.validations.models._default_validator_data_formats, help_text='Data formats this validator can parse (e.g., JSON, EnergyPlus IDF).', size=None),
        ),
        migrations.RunPython(forwards, backwards),
    ]
