# Generated by Django 5.2.7 on 2025-11-18 23:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0020_validator_supported_data_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalidator',
            name='base_validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.CharField(choices=[('BASIC', 'Basic Assertions'), ('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_VALIDATOR', 'Custom Basic Validator'), ('AI_ASSIST', 'AI Assist')], max_length=40),
        ),
        migrations.CreateModel(
            name='ValidatorCatalogRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(choices=[('cel_expr', 'CEL expression')], default='cel_expr', max_length=32)),
                ('expression', models.TextField(help_text='Rule definition (e.g., CEL expression).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data for this rule.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Relative ordering for evaluation/display.')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='validations.validator')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValidatorCatalogRuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencing_rules', to='validations.validatorcatalogentry')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_entries', to='validations.validatorcatalogrule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='validatorcatalogrule',
            constraint=models.UniqueConstraint(fields=('validator', 'name'), name='uq_validator_rule_name'),
        ),
        migrations.AddConstraint(
            model_name='validatorcatalogrule',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='ck_validator_rule_order_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='validatorcatalogruleentry',
            index=models.Index(fields=['rule', 'catalog_entry'], name='validations_rule_id_3fe185_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validatorcatalogruleentry',
            unique_together={('rule', 'catalog_entry')},
        ),
    ]
