# Generated by Django 5.2.7 on 2025-11-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0026_remove_rulesetassertion_ck_ruleset_assertion_target_oneof_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulesetassertion',
            name='ck_ruleset_assertion_target_oneof',
        ),
        migrations.AlterField(
            model_name='validatorcatalogentry',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for this catalog entry within the validator. You can use this slug in rules and CEL templates.', max_length=255),
        ),
        migrations.AlterField(
            model_name='validatorcatalogentry',
            name='target_field',
            field=models.CharField(help_text='Path used to locate this signal in the input or processor output.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='rulesetassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_catalog_entry__isnull', False), ('target_field', '')), models.Q(('target_catalog_entry__isnull', True), models.Q(('target_field', ''), _negated=True)), _connector='OR'), name='ck_ruleset_assertion_target_oneof'),
        ),
    ]
