# Generated by Django 5.2.8 on 2025-11-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0031_relax_catalog_slug_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorcatalogentry',
            name='run_stage',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='input', help_text="Phase of the validator run when this entry is available. INPUT is before the validator's processor operates on the data. OUTPUT is the data generated by the validator's processor.", max_length=16),
        ),
        migrations.AlterField(
            model_name='validatorcatalogentry',
            name='slug',
            field=models.SlugField(help_text='Unique name for this catalog entry within the validator. You use this name in assertions and CEL statements.', max_length=255),
        ),
    ]
