# Generated by Django 5.2.8 on 2025-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0038_add_fmu_gcs_uri_and_binding_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmumodel',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum used to reference cached FMUs in storage.', max_length=128),
        ),
    ]
