# Generated by Django 5.2.7 on 2025-10-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
