# Generated by Django 5.2.7 on 2025-10-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_events', to='users.organization'),
        ),
        migrations.AddField(
            model_name='outboundevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.outboundevent'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='users.organization'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint'),
        ),
        migrations.AddIndex(
            model_name='outboundevent',
            index=models.Index(fields=['org', 'event_type', 'created'], name='integration_org_id_56bb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='integration_resourc_f1f1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created'], name='integration_endpoin_cc598f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['success', 'created'], name='integration_success_4bb9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['next_retry_at'], name='integration_next_re_a21833_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookdelivery',
            unique_together={('endpoint', 'event')},
        ),
    ]
