# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.13'
  commands:
    # Install uv
    - pip install uv
    # Install dependencies using uv
    - uv sync --extra dev
    # Build documentation with Sphinx
    - uv run sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html/
