# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='guest_invite',
            field=models.ForeignKey(blank=True, help_text='Link to GuestInvite for guest_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.guestinvite'),
        ),
        migrations.AddField(
            model_name='notification',
            name='member_invite',
            field=models.ForeignKey(blank=True, db_column='invite_id', help_text='Link to MemberInvite for member_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.memberinvite'),
        ),
        migrations.AddField(
            model_name='notification',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='workflow_invite',
            field=models.ForeignKey(blank=True, help_text='Link to WorkflowInvite for workflow_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.workflowinvite'),
        ),
    ]
