# Generated by Django 6.0 on 2026-01-07 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_dismissed_at'),
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
        ('workflows', '0023_guest_invite_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='guest_invite',
            field=models.ForeignKey(blank=True, help_text='Link to GuestInvite for guest_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.guestinvite'),
        ),
        migrations.AddField(
            model_name='notification',
            name='workflow_invite',
            field=models.ForeignKey(blank=True, help_text='Link to WorkflowInvite for workflow_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.workflowinvite'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='invite',
            field=models.ForeignKey(blank=True, help_text='Link to PendingInvite for member_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.pendinginvite'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('member_invite', 'Member invite'), ('guest_invite', 'Guest invite'), ('workflow_invite', 'Workflow invite'), ('system_alert', 'System alert')], max_length=32),
        ),
    ]
