# Generated by Django 6.0 on 2026-01-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_guest_invite_phase2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='invite',
        ),
    ]
