# Generated by Django 6.0 on 2026-01-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_invite'),
        ('users', '0011_memberinvite_delete_pendinginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='member_invite',
            field=models.ForeignKey(blank=True, db_column='invite_id', help_text='Link to MemberInvite for member_invite notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.memberinvite'),
        ),
    ]
