# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'slug'], name='projects_pr_org_id_527094_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'is_active'], name='projects_pr_org_id_0e57f6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'deleted_at'], name='projects_pr_is_acti_ed77ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='uq_project_org_single_default'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('org', 'slug')},
        ),
    ]
