# Generated by Django 5.1.11 on 2025-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_user_current_org_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.Membership', to='users.organization'),
        ),
    ]
