# Generated by Django 5.1.11 on 2025-08-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organizations',
            new_name='orgs',
        ),
    ]
