# Generated by Django 5.1.11 on 2025-09-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_organizations_user_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('OWNER', 'Owner'), ('AUTHOR', 'Author'), ('EXECUTE', 'Execute'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='users.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='users.role')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='memberships', through='users.MembershipRole', to='users.role'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['membership', 'role'], name='users_membe_members_233ca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershiprole',
            unique_together={('membership', 'role')},
        ),
    ]
