# Generated by Django 5.2.7 on 2025-10-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('AUTHOR', 'Author'), ('EXECUTOR', 'Executor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=32),
        ),
    ]
