# Generated by Django 5.2.7 on 2025-11-13 02:16

from django.db import migrations


def grant_all_roles_to_owners(apps, schema_editor):
    Membership = apps.get_model("users", "Membership")
    # Ensure related managers are available before iterating
    from simplevalidations.users.constants import RoleCode

    owner_memberships = (
        Membership.objects.filter(
            membership_roles__role__code=RoleCode.OWNER,
            is_active=True,
        )
        .distinct()
    )
    for membership in owner_memberships:
        membership.refresh_from_db()
        if not membership.membership_roles.filter(role__code=RoleCode.OWNER).exists():
            continue
        # Reuse the runtime helper to normalize role assignments.
        membership.set_roles({RoleCode.OWNER})


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_code'),
    ]

    operations = [
        migrations.RunPython(grant_all_roles_to_owners, noop),
    ]
