# Generated by Django 5.2.7 on 2025-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ensure_owner_has_all_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('AUTHOR', 'Author'), ('EXECUTOR', 'Executor'), ('WORKFLOW_VIEWER', 'Workflow Viewer'), ('RESULTS_VIEWER', 'Validation Results Viewer')], default='WORKFLOW_VIEWER', max_length=32),
        ),
    ]
