# Generated by Django 5.2.7 on 2025-10-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_bio_alter_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('AUTHOR', 'Author'), ('EXECUTOR', 'Executor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=32),
        ),
    ]
