# Generated by Django 5.2.7 on 2025-10-08

from uuid import uuid4

from django.db import migrations
from django.utils.text import slugify


def _workspace_name(user):
    name = (user.name or "").strip() or (user.username or "Workspace")
    if name.endswith("s"):
        return f"{name}’ Workspace"
    return f"{name}’s Workspace"


def _unique_slug(model, base):
    base_slug = slugify(base) or f"workspace-{uuid4().hex[:8]}"
    slug = base_slug
    index = 2
    while model.objects.filter(slug=slug).exists():
        slug = f"{base_slug}-{index}"
        index += 1
    return slug


def _ensure_default_project(Project, org):
    default = Project.objects.filter(org=org, is_default=True).first()
    if default:
        if not default.is_active:
            default.is_active = True
            default.deleted_at = None
            default.save(update_fields=["is_active", "deleted_at"])
        return

    name = "Default Project"
    base_slug = slugify(name) or f"default-{uuid4().hex[:8]}"
    slug = base_slug
    counter = 2
    while Project.objects.filter(org=org, slug=slug).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    Project.objects.create(
        org=org,
        name=name,
        description="",
        slug=slug,
        is_default=True,
        is_active=True,
    )


def create_personal_workspaces(apps, schema_editor):
    User = apps.get_model("users", "User")
    Organization = apps.get_model("users", "Organization")
    Membership = apps.get_model("users", "Membership")
    Role = apps.get_model("users", "Role")
    Project = apps.get_model("projects", "Project")

    admin_role, _ = Role.objects.get_or_create(code="ADMIN", defaults={"name": "Admin"})
    owner_role, _ = Role.objects.get_or_create(code="OWNER", defaults={"name": "Owner"})
    executor_role, _ = Role.objects.get_or_create(code="EXECUTOR", defaults={"name": "Executor"})

    for user in User.objects.all():
        membership = (
            Membership.objects.filter(user=user, org__is_personal=True)
            .select_related("org")
            .first()
        )
        if membership:
            membership.roles.add(admin_role, owner_role, executor_role)
            _ensure_default_project(Project, membership.org)
            if user.current_org_id != membership.org_id:
                user.current_org = membership.org
                user.save(update_fields=["current_org"])
            continue

        workspace_name = _workspace_name(user)
        slug = _unique_slug(Organization, workspace_name)
        org = Organization.objects.create(
            name=workspace_name,
            slug=slug,
            is_personal=True,
        )
        membership = Membership.objects.create(
            user=user,
            org=org,
            is_active=True,
        )
        membership.roles.add(admin_role, owner_role, executor_role)
        _ensure_default_project(Project, org)
        user.current_org = org
        user.save(update_fields=["current_org"])


def rollback_personal_workspaces(apps, schema_editor):
    """No-op rollback."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_role_code"),
        ("projects", "0004_populate_default_projects"),
    ]

    operations = [
        migrations.RunPython(create_personal_workspaces, rollback_personal_workspaces),
    ]
