# Generated by Django 5.2.8 on 2025-12-04 08:24

import simplevalidations.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pendinginvite_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginvite',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square image works best across the app.', null=True, storage=simplevalidations.users.models.select_public_storage, upload_to='avatars/'),
        ),
    ]
