title: "[Idea] "
labels:
  - enhancement
  - idea
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Feature suggestions help make Validibot better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this idea solve? What's the use case?
      placeholder: Currently, when I try to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if Validibot could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any other approaches?
      placeholder: I also thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Validibot does this relate to?
      options:
        - Web UI
        - REST API
        - Workflow Engine
        - Built-in Validators
        - Advanced Validators (Docker)
        - CLI
        - Documentation
        - Other

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'd be interested in contributing this feature
