# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('validations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='validation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['org', 'key', 'endpoint'], name='core_idempo_org_id_cf6934_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at'], name='core_idempo_expires_6bf43d_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('org', 'key', 'endpoint'), name='uq_idempotency_org_key_endpoint'),
        ),
    ]
