# Generated by Django 6.0.3 on 2026-04-07 03:21

from django.db import migrations, models


def ensure_singleton_and_migrate_json(apps, schema_editor):
    """Ensure the singleton row exists and migrate JSON data to model fields.

    Creates the ``default`` SiteSettings row if it doesn't exist yet, then
    copies any values from ``data["api_submission"]`` into the new model
    columns and removes that key from the JSON blob.
    """
    SiteSettings = apps.get_model("core", "SiteSettings")
    obj, _ = SiteSettings.objects.get_or_create(slug="default")
    api = (obj.data or {}).get("api_submission", {})
    changed = False
    if "metadata_key_value_only" in api:
        obj.metadata_key_value_only = bool(api["metadata_key_value_only"])
        changed = True
    if "metadata_max_bytes" in api:
        obj.metadata_max_bytes = max(0, int(api["metadata_max_bytes"]))
        changed = True
    if api:
        obj.data.pop("api_submission", None)
        changed = True
    if changed:
        obj.save(update_fields=[
            "metadata_key_value_only",
            "metadata_max_bytes",
            "data",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="metadata_key_value_only",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When checked, metadata values must be scalars "
                    "(no nested lists or dicts)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="metadata_max_bytes",
            field=models.PositiveIntegerField(
                default=4096,
                help_text=(
                    "Maximum size (in bytes) of stored metadata per submission. "
                    "Set to 0 to disable the limit."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON catch-all for settings not yet promoted to model fields.",
            ),
        ),
        migrations.RunPython(
            ensure_singleton_and_migrate_json,
            migrations.RunPython.noop,
        ),
    ]
