# Generated by Django 6.0 on 2025-12-09 00:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_created_and_more'),
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
        ('validations', '0040_callback_receipt_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('response_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='users.organization')),
                ('validation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validations.validationrun')),
            ],
            options={
                'verbose_name': 'Idempotency key',
                'verbose_name_plural': 'Idempotency keys',
                'indexes': [models.Index(fields=['org', 'key', 'endpoint'], name='core_idempo_org_id_cf6934_idx'), models.Index(fields=['expires_at'], name='core_idempo_expires_6bf43d_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'key', 'endpoint'), name='uq_idempotency_org_key_endpoint')],
            },
        ),
    ]
