# Generated by Django 6.0 on 2026-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=20),
        ),
    ]
