# Generated by Django 5.1.11 on 2025-08-22 02:46

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_organization_user_current_org_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_submissions_per_day', models.IntegerField(default=100)),
                ('max_run_minutes_per_day', models.IntegerField(default=60)),
                ('artifact_retention_days', models.IntegerField(default=7)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='users.organization')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField()),
                ('submissions', models.IntegerField(default=0)),
                ('run_minutes', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'date'], name='billing_usa_org_id_cada85_idx')],
                'unique_together': {('org', 'date')},
            },
        ),
    ]
