"""Constants shared by the SHACL validator, forms, and tests."""

SHACL_RESULT_FAIL_IMMEDIATELY = "fail_immediately"
SHACL_RESULT_FAIL_AFTER_ASSERTIONS = "fail_after_assertions"
SHACL_RESULT_REPORT_ONLY = "report_only"

SHACL_RESULT_HANDLING_DEFAULT = SHACL_RESULT_FAIL_AFTER_ASSERTIONS
SHACL_RESULT_HANDLING_VALUES = frozenset(
    {
        SHACL_RESULT_FAIL_IMMEDIATELY,
        SHACL_RESULT_FAIL_AFTER_ASSERTIONS,
        SHACL_RESULT_REPORT_ONLY,
    },
)

__all__ = [
    "SHACL_RESULT_FAIL_AFTER_ASSERTIONS",
    "SHACL_RESULT_FAIL_IMMEDIATELY",
    "SHACL_RESULT_HANDLING_DEFAULT",
    "SHACL_RESULT_HANDLING_VALUES",
    "SHACL_RESULT_REPORT_ONLY",
]
