from django.urls import path

from validibot.workflows import views

app_name = "workflows"

urlpatterns = [
    path("", views.WorkflowListView.as_view(), name="workflow_list"),
    path("shared/", views.GuestWorkflowListView.as_view(), name="guest_workflow_list"),
    path("new/", views.WorkflowCreateView.as_view(), name="workflow_create"),
    path(
        "<int:pk>/launch/",
        views.WorkflowLaunchDetailView.as_view(),
        name="workflow_launch",
    ),
    path(
        "<int:pk>/launch/run/<uuid:run_id>/",
        views.WorkflowRunDetailView.as_view(),
        name="workflow_run_detail",
    ),
    # This route allows you to reload the results of a validation run
    # without having to redo the entire workflow launch.
    path(
        "<int:pk>/launch/run/latest/",
        views.WorkflowLastRunStatusView.as_view(),
        name="workflow_last_run",
    ),
    path(
        "<int:pk>/launch/run/<uuid:run_id>/status/",
        views.WorkflowLaunchStatusView.as_view(),
        name="workflow_launch_status",
    ),
    path(
        "<int:pk>/launch/run/<uuid:run_id>/cancel/",
        views.WorkflowLaunchCancelView.as_view(),
        name="workflow_launch_cancel",
    ),
    path(
        "<int:pk>/public-info/",
        views.WorkflowPublicInfoUpdateView.as_view(),
        name="workflow_public_info_edit",
    ),
    path(
        "<int:pk>/sharing/",
        views.WorkflowSharingView.as_view(),
        name="workflow_sharing",
    ),
    path(
        "<int:pk>/sharing/visibility/",
        views.WorkflowVisibilityUpdateView.as_view(),
        name="workflow_visibility_update",
    ),
    path(
        "<int:pk>/",
        views.WorkflowDetailView.as_view(),
        name="workflow_detail",
    ),
    path(
        "<int:pk>/activation/",
        views.WorkflowActivationUpdateView.as_view(),
        name="workflow_activation",
    ),
    path(
        "<int:pk>/public-info/visibility/",
        views.WorkflowPublicVisibilityUpdateView.as_view(),
        name="workflow_public_visibility",
    ),
    path(
        "<int:pk>/edit/",
        views.WorkflowUpdateView.as_view(),
        name="workflow_update",
    ),
    path(
        "<int:pk>/delete/",
        views.WorkflowDeleteView.as_view(),
        name="workflow_delete",
    ),
    path(
        "<int:pk>/archive/",
        views.WorkflowArchiveView.as_view(),
        name="workflow_archive",
    ),
    path(
        "<int:pk>/steps/",
        views.WorkflowStepListView.as_view(),
        name="workflow_step_list",
    ),
    path(
        "<int:pk>/steps/wizard/",
        views.WorkflowStepWizardView.as_view(),
        name="workflow_step_wizard",
    ),
    path(
        "<int:pk>/steps/add/<int:validator_id>/",
        views.WorkflowStepCreateView.as_view(),
        name="workflow_step_create",
    ),
    path(
        "<int:pk>/steps/add/action/<int:action_definition_id>/",
        views.WorkflowActionStepCreateView.as_view(),
        name="workflow_step_action_create",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/wizard/",
        views.WorkflowStepWizardView.as_view(),
        name="workflow_step_wizard_existing",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/edit/",
        views.WorkflowStepEditView.as_view(),
        name="workflow_step_edit",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/settings/",
        views.WorkflowStepUpdateView.as_view(),
        name="workflow_step_settings",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/delete/",
        views.WorkflowStepDeleteView.as_view(),
        name="workflow_step_delete",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/move/",
        views.WorkflowStepMoveView.as_view(),
        name="workflow_step_move",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/assertions/new/",
        views.WorkflowStepAssertionCreateView.as_view(),
        name="workflow_step_assertion_create",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/assertions/<int:assertion_id>/edit/",
        views.WorkflowStepAssertionUpdateView.as_view(),
        name="workflow_step_assertion_update",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/assertions/<int:assertion_id>/delete/",
        views.WorkflowStepAssertionDeleteView.as_view(),
        name="workflow_step_assertion_delete",
    ),
    path(
        "<int:pk>/steps/<int:step_id>/assertions/<int:assertion_id>/move/",
        views.WorkflowStepAssertionMoveView.as_view(),
        name="workflow_step_assertion_move",
    ),
    path(
        "<int:pk>/validations/",
        views.WorkflowValidationListView.as_view(),
        name="workflow_validation_list",
    ),
]
