from django.urls import path

from simplevalidations.validations import views

app_name = "validations"

urlpatterns = [
    path(
        "library/",
        views.ValidationLibraryView.as_view(),
        name="validation_library",
    ),
    path(
        "library/custom/new/",
        views.CustomValidatorCreateView.as_view(),
        name="custom_validator_create",
    ),
    path(
        "library/custom/<slug:slug>/edit/",
        views.CustomValidatorUpdateView.as_view(),
        name="custom_validator_update",
    ),
    path(
        "library/custom/<slug:slug>/delete/",
        views.CustomValidatorDeleteView.as_view(),
        name="custom_validator_delete",
    ),
    path(
        "library/custom/<slug:slug>/",
        views.ValidatorDetailView.as_view(),
        name="validator_detail",
    ),
    path(
        "library/custom/<int:pk>/signals/new/",
        views.ValidatorSignalCreateView.as_view(),
        name="validator_signal_create",
    ),
    path(
        "library/custom/<int:pk>/signals/<int:entry_pk>/edit/",
        views.ValidatorSignalUpdateView.as_view(),
        name="validator_signal_update",
    ),
    path(
        "library/custom/<int:pk>/signals/<int:entry_pk>/delete/",
        views.ValidatorSignalDeleteView.as_view(),
        name="validator_signal_delete",
    ),
    path(
        "library/custom/<int:pk>/rules/",
        views.ValidatorRuleListView.as_view(),
        name="validator_rules",
    ),
    path(
        "library/custom/<int:pk>/rules/new/",
        views.ValidatorRuleCreateView.as_view(),
        name="validator_rule_create",
    ),
    path(
        "library/custom/<int:pk>/rules/<int:rule_pk>/edit/",
        views.ValidatorRuleUpdateView.as_view(),
        name="validator_rule_update",
    ),
    path(
        "library/custom/<int:pk>/rules/<int:rule_pk>/delete/",
        views.ValidatorRuleDeleteView.as_view(),
        name="validator_rule_delete",
    ),
    path(
        "",
        views.ValidationRunListView.as_view(),
        name="validation_list",
    ),
    path(
        "<uuid:pk>/",
        views.ValidationRunDetailView.as_view(),
        name="validation_detail",
    ),
    path(
        "<uuid:pk>/delete/",
        views.ValidationRunDeleteView.as_view(),
        name="validation_delete",
    ),
]
