# Generated by Django 6.0.4 on 2026-04-22 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_wipe_pre_encryption_authenticators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Actor email captured at action time. Nulled during GDPR erasure; the ``erased_at`` timestamp distinguishes the two.', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP the action was taken from. Under APP 11 / GDPR treated as personal info when combined with other identifiers, so it is cleared by the erasure workflow.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='HTTP User-Agent header at action time.')),
                ('erased_at', models.DateTimeField(blank=True, help_text="Timestamp when this actor's PII was nulled. NULL means the actor still resolves to a named person.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The Django user who took the action. NULL for system-originated entries (management commands, signal handlers) or after the user row itself is purged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Actor',
                'verbose_name_plural': 'Audit Actors',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('workflow_created', 'Workflow Created'), ('workflow_updated', 'Workflow Updated'), ('workflow_deleted', 'Workflow Deleted'), ('ruleset_created', 'Ruleset Created'), ('ruleset_updated', 'Ruleset Updated'), ('ruleset_deleted', 'Ruleset Deleted'), ('validator_added', 'Validator Added'), ('validator_updated', 'Validator Updated'), ('validator_removed', 'Validator Removed'), ('member_invited', 'Member Invited'), ('member_role_changed', 'Member Role Changed'), ('member_removed', 'Member Removed'), ('guest_granted', 'Guest Access Granted'), ('guest_revoked', 'Guest Access Revoked'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('login_succeeded', 'Login Succeeded'), ('login_failed', 'Login Failed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_challenge_failed', 'MFA Challenge Failed'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('session_revoked', 'Session Revoked'), ('admin_object_changed', 'Admin Object Changed'), ('user_erasure_requested', 'User Erasure Requested'), ('user_erasure_completed', 'User Erasure Completed'), ('audit_entry_sanitised', 'Audit Entry Sanitised')], help_text='Machine-readable action code; see AuditAction.', max_length=64)),
                ('target_type', models.CharField(blank=True, default='', help_text='Django model label of the target, e.g. ``workflows.Workflow``. Empty for actions without a target (e.g. LOGIN_FAILED).', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', help_text='String primary key of the target. Stored as string (not FK) so the entry survives target deletion.', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', help_text='Human-readable label captured at action time — survives target deletion.', max_length=256)),
                ('changes', models.JSONField(blank=True, help_text="Whitelisted before/after field snapshot: ``{field: {'before': ..., 'after': ...}}``. Fields outside ``AUDITABLE_FIELDS`` are recorded as ``<redacted>``.", null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Free-form, sanitised supplementary context. Never stores secrets, full request bodies, or validation payloads.', null=True)),
                ('request_id', models.CharField(blank=True, default='', help_text='UUID per request, set by ``AuditContextMiddleware``. Used to correlate a DB entry back to Cloud Logging markers.', max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Wall-clock time the entry was written.')),
                ('actor', models.ForeignKey(help_text='PROTECT rather than CASCADE: deleting an actor should be rejected at the DB level. Actor rows are nulled via the erasure workflow, never removed.', on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='audit.auditactor')),
                ('org', models.ForeignKey(blank=True, help_text='Scope of the event. NULL for global/system-level actions (e.g. superuser admin changes outside an org context).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='users.organization')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
            },
        ),
        migrations.AddIndex(
            model_name='auditactor',
            index=models.Index(fields=['user'], name='audit_audit_user_id_b62885_idx'),
        ),
        migrations.AddIndex(
            model_name='auditactor',
            index=models.Index(fields=['email'], name='audit_audit_email_52b8da_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['org', '-occurred_at'], name='audit_audit_org_id_e3a243_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['actor', '-occurred_at'], name='audit_audit_actor_i_5026d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', '-occurred_at'], name='audit_audit_action_0bda6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__8a9e7e_idx'),
        ),
    ]
