from django.conf import settings
from django.urls import include
from django.urls import path

from . import views

app_name = "marketing"
urlpatterns = [
    path(
        "",
        views.HomePageView.as_view(),
        name="home",
    ),
    path(
        "waitlist/",
        views.submit_beta_waitlist,
        name="beta_waitlist",
    ),
    path(
        "webhooks/postmark/delivery/",
        views.postmark_delivery_webhook,
        name="postmark_delivery_webhook",
    ),
    path(
        "webhooks/postmark/bounce/",
        views.postmark_bounce_webhook,
        name="postmark_bounce_webhook",
    ),
    path("blog/", include("simplevalidations.blog.urls", namespace="blog")),
    path(
        "about/",
        views.AboutPageView.as_view(),
        name="about",
    ),
    path(
        "features/",
        views.FeaturesPageView.as_view(),
        name="features",
    ),
    path(
        "features/overview/",
        views.FeatureOverviewPageView.as_view(),
        name="features_overview",
    ),
    path(
        "features/schema-validation/",
        views.FeatureSchemaValidationPageView.as_view(),
        name="features_schema_validation",
    ),
    path(
        "features/simulation-validation/",
        views.FeatureSimulationValidationPageView.as_view(),
        name="features_simulation_validation",
    ),
    path(
        "features/certificates/",
        views.FeatureCertificatesPageView.as_view(),
        name="features_certificates",
    ),
    path(
        "features/blockchain/",
        views.FeatureBlockchainPageView.as_view(),
        name="features_blockchain",
    ),
    path(
        "features/integrations/",
        views.FeatureIntegrationsPageView.as_view(),
        name="features_integrations",
    ),
    path(
        "features/custom-validators/",
        views.FeatureCustomValidatorsPageView.as_view(),
        name="features_custom_validators",
    ),
    path(
        "features/data-validation-consulting/",
        views.FeatureConsultingPageView.as_view(),
        name="features_consulting",
    ),
    path(
        "resources/",
        views.ResourcesPageView.as_view(),
        name="resources",
    ),
    path(
        "resources/docs/",
        views.DocsPageView.as_view(),
        name="resources_docs",
    ),
    path(
        "resources/videos/",
        views.VideosPageView.as_view(),
        name="resources_videos",
    ),
    path(
        "resources/changelog/",
        views.ChangelogPageView.as_view(),
        name="resources_changelog",
    ),
    path(
        "faq/",
        views.FAQPageView.as_view(),
        name="faq",
    ),
    path(
        "support/",
        views.SupportHomePageView.as_view(),
        name="support",
    ),
    path(
        "contact/",
        views.ContactPageView.as_view(),
        name="contact",
    ),
    path(
        "support/help-center/",
        views.HelpCenterPageView.as_view(),
        name="help_center",
    ),
    path(
        "support/status/",
        views.StatusPageView.as_view(),
        name="status",
    ),
    path(
        "terms/",
        views.TermsPageView.as_view(),
        name="terms",
    ),
    path(
        "privacy/",
        views.PrivacyPageView.as_view(),
        name="privacy",
    ),
]


if settings.ENABLE_PRICING_SECTION:
    urlpatterns += [
        path(
            "pricing/",
            views.PricingPageView.as_view(),
            name="pricing",
        ),
        path(
            "pricing/starter/",
            views.PricingStarterPageView.as_view(),
            name="pricing_starter",
        ),
        path(
            "pricing/growth/",
            views.PricingGrowthPageView.as_view(),
            name="pricing_growth",
        ),
        path(
            "pricing/enterprise/",
            views.PricingEnterprisePageView.as_view(),
            name="pricing_enterprise",
        ),
    ]
