# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import validibot.core.mixins
import validibot.workflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
        ('validations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('featured_image', models.FileField(blank=True, help_text="Optional image to represent the workflow Shown on the 'info' page.", null=True, storage=validibot.workflows.models.select_public_storage, upload_to='')),
                ('name', models.CharField(help_text="Name of the workflow, e.g. 'My Workflow'", max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the workflow.', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the workflow, used in URLs. (Leave blank to auto-generate from name.)')),
                ('allow_submission_name', models.BooleanField(default=True, help_text='Allow users to submit a custom name along with their data for validation.')),
                ('allow_submission_meta_data', models.BooleanField(default=False, help_text='Allow users to submit meta-data along with their data for validation.')),
                ('allow_submission_short_description', models.BooleanField(default=False, help_text='Allow users to submit a short description along with their data for validation.')),
                ('version', models.CharField(blank=True, default='', help_text="Version identifier (integer or semantic version, e.g., '1' or '1.0.0').", max_length=40, validators=[validibot.workflows.models.validate_workflow_version])),
                ('is_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive workflows stay visible but cannot run validations.')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived workflows are disabled and hidden unless explicitly shown.')),
                ('make_info_page_public', models.BooleanField(default=False, help_text="Allows non-logged in users to see the workflow's info page.")),
                ('is_public', models.BooleanField(default=False, help_text='If true, any authenticated user can launch this workflow.')),
                ('allowed_file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('binary', 'Binary'), ('UNKNOWN', 'Unknown')], max_length=32), default=validibot.workflows.models._default_workflow_file_types, help_text='Logical file types (JSON, XML, text, etc.) this workflow can accept.')),
                ('data_retention', models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_1_DAY', 'Store for 1 day'), ('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_PERMANENTLY', 'Store permanently')], default='DO_NOT_STORE', help_text='How long to keep user-submitted files after validation completes. DO_NOT_STORE deletes the submission immediately after successful completion. The submission record is preserved for audit.', max_length=32)),
                ('output_retention', models.CharField(choices=[('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_90_DAYS', 'Store for 90 days'), ('STORE_1_YEAR', 'Store for 1 year'), ('STORE_PERMANENTLY', 'Store permanently')], default='STORE_30_DAYS', help_text='How long to keep validation outputs (results, artifacts, findings) after validation completes. Users need time to download results, so immediate deletion is not an option.', max_length=32)),
                ('success_message', models.TextField(blank=True, default='', help_text='Custom message displayed when validation succeeds. Leave blank for the default message.')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='users.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Default project to associate with runs triggered from this workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='projects.project')),
                ('user', models.ForeignKey(help_text='The user who created this workflow.', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug', '-version'],
            },
            bases=(validibot.core.mixins.FeaturedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email address of invitee (used when inviting non-users).', max_length=254)),
                ('scope', models.CharField(choices=[('ALL', 'All workflows in org'), ('SELECTED', 'Selected workflows')], default='SELECTED', help_text='Whether to grant access to all current workflows or a selection.', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for invite acceptance URL.', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite expires.')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='The invited user, if they already have an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_guest_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='The user who sent this invite.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_guest_invites', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='The organization this invite is for.', on_delete=django.db.models.deletion.CASCADE, related_name='guest_invites', to='users.organization')),
                ('workflows', models.ManyToManyField(blank=True, help_text='Workflows to grant access to (used when scope=SELECTED).', related_name='guest_invites', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'guest invite',
                'verbose_name_plural': 'guest invites',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grant is currently active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this access grant.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user who created this grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_workflow_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who has been granted access.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_grants', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow this grant provides access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'workflow access grant',
                'verbose_name_plural': 'workflow access grants',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInvite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email address of invitee (used when inviting non-users).', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for invite acceptance URL.', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite expires.')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='The invited user, if they already have an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_workflow_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='The user who sent this invite.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_workflow_invites', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow this invite grants access to.', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'workflow invite',
                'verbose_name_plural': 'workflow invites',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPublicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', help_text='Optional title to show on the public info page. If blank, the Workflow name will be used.', max_length=200)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('show_steps', models.BooleanField(default=True, help_text='Whether to show the workflow steps on the public info page.')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_info', to='workflows.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_role_access', to='users.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='Brief description to help users understand what this step does.', max_length=2000)),
                ('notes', models.CharField(blank=True, default='', help_text='Author notes about this step (visible only by you and other users with author permissions for this workflow).', max_length=2000)),
                ('display_schema', models.BooleanField(default=False, help_text='Allow launchers to view this schema in public workflow pages.')),
                ('show_success_messages', models.BooleanField(default=False, help_text='When enabled, assertions display their success message when they pass. If an assertion has no success message defined, a default is generated.')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='actions.action')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validations.ruleset')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='validations.validator')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('org', 'slug', 'version'), name='uq_workflow_org_slug_version'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['token'], name='workflows_g_token_45419d_idx'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['invitee_email', 'status'], name='workflows_g_invitee_cfcd07_idx'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['org', 'status'], name='workflows_g_org_id_25d889_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaccessgrant',
            index=models.Index(fields=['user', 'is_active'], name='workflows_w_user_id_abb030_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaccessgrant',
            index=models.Index(fields=['workflow', 'is_active'], name='workflows_w_workflo_2c234f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowaccessgrant',
            unique_together={('workflow', 'user')},
        ),
        migrations.AddIndex(
            model_name='workflowinvite',
            index=models.Index(fields=['token'], name='workflows_w_token_60e089_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinvite',
            index=models.Index(fields=['invitee_email', 'status'], name='workflows_w_invitee_b5ac80_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinvite',
            index=models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_b2ac73_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowroleaccess',
            index=models.Index(fields=['workflow', 'role'], name='workflows_w_workflo_1d18f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowroleaccess',
            unique_together={('workflow', 'role')},
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__isnull', True), ('validator__isnull', False)), models.Q(('action__isnull', False), ('validator__isnull', True)), _connector='OR'), name='workflowstep_validator_xor_action'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'order')},
        ),
    ]
