# Generated by Django 5.2.7 on 2025-10-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive workflows stay visible but cannot run validations.'),
        ),
    ]
