# Generated by Django 6.0.2 on 2026-03-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0022_workflowstepresource'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Purpose of this resource (e.g., WEATHER_FILE, MODEL_TEMPLATE).', max_length=50)),
                ('step_resource_file', models.FileField(blank=True, help_text='File owned by this step. Deleted when the step is deleted.', max_length=500, upload_to='step_resources/')),
                ('filename', models.CharField(blank=True, help_text='Original filename of the step-owned file.', max_length=255)),
                ('resource_type', models.CharField(blank=True, help_text='Resource type identifier for step-owned files.', max_length=32)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_resources', to='workflows.workflowstep')),
                ('validator_resource_file', models.ForeignKey(blank=True, help_text='Shared resource from the validator library.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_usages', to='validations.validatorresourcefile')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('step_resource_file', ''), ('validator_resource_file__isnull', False)), models.Q(('validator_resource_file__isnull', True), models.Q(('step_resource_file', ''), _negated=True)), _connector='OR'), name='ck_step_resource_xor_file')],
            },
        ),
    ]
