# Generated by Django 6.0.3 on 2026-03-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_migrate_resource_file_ids_to_step_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='agent_access_enabled',
            field=models.BooleanField(default=False, help_text='Allow AI agents to discover and submit to this workflow via MCP.'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='agent_billing_mode',
            field=models.CharField(choices=[('author_pays', 'Author pays (default)'), ('agent_pays_acp', 'Agent pays via Stripe ACP')], default='author_pays', help_text="Who pays for agent-initiated runs: the workflow author's plan, or the agent operator via Stripe ACP.", max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='agent_max_launches_per_hour',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum MCP-initiated launches per hour. Null means use the plan default.', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='agent_price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Price per agent invocation in US cents. Required when billing mode is AGENT_PAYS_ACP.', null=True),
        ),
    ]
