# Generated by Django 5.2.7 on 2025-10-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_make_info_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='featured_image',
            field=models.FileField(blank=True, help_text="Optional image to represent the workflow Shown on the 'info' page.", null=True, upload_to=''),
        ),
    ]
