# Generated by Django 6.0.3 on 2026-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_agent_access_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Short description of what this workflow validates. Shown to authenticated users in the web UI, CLI, and API. For a longer public-facing description, use the workflow's public info page instead."),
        ),
    ]
