# Generated by Django 5.2.7 on 2025-10-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowPublicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Optional title to show on the public info page. If blank, the Workflow name will be used.', max_length=200)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_info', to='workflows.workflow')),
            ],
        ),
    ]
