# Generated by Django 6.0.3 on 2026-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_add_workflow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Short description of what this workflow validates. Shown to authenticated users in the web UI, CLI, and API. For a longer public-facing description, use the workflow's public info page instead.", max_length=5000),
        ),
    ]
