# Generated by Django 5.2.7 on 2025-10-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_remove_workflowpublicinfo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Brief description to help users understand what this step does.', max_length=2000),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Author notes about this step (visible only by you and other users with author permissions for this workflow).', max_length=2000),
        ),
    ]
