# Generated by Django 6.0.3 on 2026-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('validations', '0026_signal_definition_models'),
        ('workflows', '0006_add_description_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='step_key',
            field=models.SlugField(blank=True, default='', help_text='Stable identifier for this step within the workflow. Used to reference output data from this step in downstream assertions (e.g., steps.simulation.signals.site_eui_kwh_m2). Auto-generated from the step name on creation. Immutable once set.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(condition=models.Q(('step_key', ''), _negated=True), fields=('workflow', 'step_key'), name='uq_workflowstep_workflow_step_key'),
        ),
    ]
