# Generated by Django 6.0.7 on 2026-07-16 05:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0002_current_schema"),
        ("projects", "0002_initial"),
        ("users", "0004_current_schema"),
        ("validations", "0026_current_schema"),
        ("workflows", "0006_add_description_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgGuestAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this org-wide guest access is currently active.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this access grant.",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization guest access",
                "verbose_name_plural": "organization guest accesses",
            },
        ),
        migrations.CreateModel(
            name="WorkflowConstant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Constant name.  Valid CEL identifier.  Used as c.<name>.",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="The literal value.  NUMBER is stored as a canonical decimal string; LIST/OBJECT as JSON; STRING/BOOLEAN directly."
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("NUMBER", "Number"),
                            ("BOOLEAN", "Boolean"),
                            ("LIST", "List"),
                            ("OBJECT", "Object"),
                        ],
                        help_text="Explicit value type (required; no inference).",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human note (e.g. 'agreed €/kWh per the 2026 contract').",
                        max_length=500,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in the constants editor."
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSignalMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Signal name.  Valid CEL identifier.  Used as s.<name>.",
                        max_length=100,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        help_text="Data path resolved against the submission payload.",
                        max_length=500,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True,
                        help_text="Fallback value when the source path resolves to nothing.",
                        null=True,
                    ),
                ),
                (
                    "on_missing",
                    models.CharField(
                        choices=[("error", "Fail the run"), ("null", "Inject null")],
                        default="error",
                        max_length=10,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expected type: number, string, boolean.  Empty = infer.",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in the signal mapping editor.",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="agent_access_enabled",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="data_retention",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="is_public",
        ),
        migrations.AddField(
            model_name="workflow",
            name="history_policy",
            field=models.CharField(
                choices=[
                    ("versioned", "Versioned history"),
                    ("mutable", "Mutable history"),
                ],
                default="versioned",
                help_text="Controls whether this workflow preserves historical run reproducibility by requiring new versions for semantic edits, or allows in-place changes after runs.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="input_retention",
            field=models.CharField(
                choices=[
                    ("DO_NOT_STORE", "Do not store (delete after validation)"),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text="How long to keep user-submitted input files after validation completes. DO_NOT_STORE deletes the submission immediately after successful completion. The submission record is preserved for audit.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="input_schema",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="JSON Schema defining the expected submission shape. When set on a JSON-only workflow, the launch form shows a structured form as an additional input mode.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="input_schema_source_mode",
            field=models.CharField(
                blank=True,
                choices=[("json_schema", "JSON Schema"), ("pydantic", "Pydantic")],
                default="",
                help_text="How the workflow author last edited the input contract. Authoring metadata only; not part of the runtime contract.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="input_schema_source_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Original authoring text for the input contract. Used to repopulate the workflow settings form.",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="is_tombstoned",
            field=models.BooleanField(
                default=False,
                help_text="Tombstoned workflows are removed from normal product surfaces but kept for historical run and credential continuity.",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="mcp_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow authenticated AI agents to run this workflow via MCP, on behalf of a user who already has identity access through 'workflow_visibility'. Billed to that user's plan quota. Independent of x402 paid access.",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstone_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Human-entered reason recorded during break-glass delete.",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstone_workflow_definition_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Workflow definition digest captured at the time of tombstoning.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstoned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the workflow entered the break-glass tombstone state.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstoned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who initiated the break-glass tombstone flow.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tombstoned_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="workflow_visibility",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private — only you and people you invite"),
                    ("ORG", "Your organization"),
                    ("ALL_USERS", "All Validibot users"),
                ],
                default="PRIVATE",
                help_text="Who, by Validibot identity, may run this workflow for free: PRIVATE (you and people you invite — the default), ORG (your organization), or ALL_USERS (any Validibot user). Capped by the organization ceiling. Independent of x402 paid access.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="x402_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Publish this workflow for PAID, ANONYMOUS access via x402: anyone on the internet who pays the per-call price can run it, regardless of 'workflow_visibility'. Automatically bills via x402 and requires a price and 'Do not store' retention.",
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="display_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="step_key",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Stable identifier for this step within the workflow. Used to reference output data from this step in downstream assertions (e.g., steps.simulation.output.site_eui_kwh_m2). Auto-generated from the step name on creation. Immutable once set.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workflowstepresource",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of step_resource_file content. Only used for step-owned files; catalog references look up the hash via validator_resource_file.content_hash.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_billing_mode",
            field=models.CharField(
                choices=[
                    ("AUTHOR_PAYS", "Author pays (plan quota)"),
                    ("AGENT_PAYS_X402", "Agent pays via x402 micropayment"),
                ],
                default="AUTHOR_PAYS",
                help_text="Who pays when an agent invokes this workflow. AUTHOR_PAYS uses your plan quota (authenticated agents only). AGENT_PAYS_X402 requires agents to pay per call via x402.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_max_launches_per_hour",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum agent launches per hour per wallet. Null means use the platform default.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_price_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price per agent invocation in US cents (USDC equivalent). Required when billing mode is AGENT_PAYS_X402.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Positive integer version number. Every workflow row must carry a version so the family identity ``(org, slug, version)`` stays unique and 'latest version' resolution stays deterministic.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agent_billing_mode", "AGENT_PAYS_X402"), _negated=True),
                    models.Q(
                        ("agent_price_cents__isnull", False),
                        ("agent_price_cents__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="ck_workflow_x402_requires_positive_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agent_billing_mode", "AGENT_PAYS_X402"), _negated=True),
                    ("input_retention", "DO_NOT_STORE"),
                    _connector="OR",
                ),
                name="ck_workflow_x402_requires_do_not_store_retention",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("x402_enabled", False),
                    ("agent_billing_mode", "AGENT_PAYS_X402"),
                    _connector="OR",
                ),
                name="ck_workflow_x402_enabled_requires_x402_billing",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("x402_enabled", False),
                    models.Q(
                        models.Q(
                            ("is_archived", False),
                            ("is_archived__isnull", True),
                            _connector="OR",
                        ),
                        models.Q(
                            ("is_tombstoned", False),
                            ("is_tombstoned__isnull", True),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="ck_workflow_x402_enabled_requires_alive_row",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                condition=models.Q(("step_key", ""), _negated=True),
                fields=("workflow", "step_key"),
                name="uq_workflowstep_workflow_step_key",
            ),
        ),
        migrations.AddField(
            model_name="orgguestaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this grant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_org_guest_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orgguestaccess",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this guest can access workflows in.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_accesses",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="orgguestaccess",
            name="user",
            field=models.ForeignKey(
                help_text="The user who has been granted org-wide guest access.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_guest_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowconstant",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constants",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflowsignalmapping",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_mappings",
                to="workflows.workflow",
            ),
        ),
        migrations.AddIndex(
            model_name="orgguestaccess",
            index=models.Index(
                fields=["user", "is_active"], name="workflows_o_user_id_d57834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgguestaccess",
            index=models.Index(
                fields=["org", "is_active"], name="workflows_o_org_id_12fcc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orgguestaccess",
            unique_together={("user", "org")},
        ),
        migrations.AddConstraint(
            model_name="workflowconstant",
            constraint=models.UniqueConstraint(
                fields=("workflow", "name"), name="unique_constant_name_per_workflow"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowsignalmapping",
            constraint=models.UniqueConstraint(
                fields=("workflow", "name"), name="unique_signal_name_per_workflow"
            ),
        ),
    ]
