# Generated by Django 6.0.7 on 2026-07-27 23:06

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
        ("users", "0004_current_schema"),
        ("workflows", "0007_current_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflow",
            name="ck_workflow_x402_requires_do_not_store_retention",
        ),
        migrations.AlterField(
            model_name="workflow",
            name="input_retention",
            field=models.CharField(
                choices=[
                    ("DO_NOT_STORE", "Do not store (delete after validation)"),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text=(
                    "How long to keep user-submitted input files after validation "
                    "completes. DO_NOT_STORE deletes the submission immediately "
                    "after any terminal outcome. The submission record is "
                    "preserved for audit."
                ),
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="output_retention",
            field=models.CharField(
                choices=[
                    ("DO_NOT_STORE", "Do not retain (purge after validation)"),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_90_DAYS", "Store for 90 days"),
                    ("STORE_1_YEAR", "Store for 1 year"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text=(
                    "How long to keep validation outputs (results, artifacts, "
                    "findings) after validation reaches a terminal state. "
                    "DO_NOT_STORE queues detailed output deletion immediately "
                    "while preserving a minimal run status and aggregate audit "
                    "record."
                ),
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agent_billing_mode", "AGENT_PAYS_X402"), _negated=True),
                    models.Q(
                        ("input_retention", "DO_NOT_STORE"),
                        ("output_retention", "DO_NOT_STORE"),
                    ),
                    _connector="OR",
                ),
                name="ck_workflow_x402_requires_do_not_store_retention",
            ),
        ),
    ]
