# Generated by Django 5.2.7 on 2025-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_workflowstep_description_workflowstep_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='display_schema',
            field=models.BooleanField(default=False, help_text='Allow launchers to view this schema in public workflow pages.'),
        ),
    ]
