# Generated by Django 6.0.3 on 2026-03-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_signal_definition_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='input_schema',
            field=models.JSONField(blank=True, default=None, help_text='JSON Schema defining the expected submission shape. When set on a JSON-only workflow, the launch form shows a structured form as an additional input mode.', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='input_schema_source_mode',
            field=models.CharField(blank=True, choices=[('json_schema', 'JSON Schema'), ('pydantic', 'Pydantic')], default='', help_text='How the workflow author last edited the input contract. Authoring metadata only; not part of the runtime contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='workflow',
            name='input_schema_source_text',
            field=models.TextField(blank=True, default='', help_text='Original authoring text for the input contract. Used to repopulate the workflow settings form.'),
        ),
    ]
