# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Clarify that output retention does not govern the evidence receipt."""

    dependencies = [
        (
            "workflows",
            "0008_remove_workflow_ck_workflow_x402_requires_do_not_store_retention_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="output_retention",
            field=models.CharField(
                choices=[
                    (
                        "DO_NOT_STORE",
                        "Do not retain (purge after validation)",
                    ),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_90_DAYS", "Store for 90 days"),
                    ("STORE_1_YEAR", "Store for 1 year"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text=(
                    "How long to keep validation outputs (results, artifacts, "
                    "findings) after validation reaches a terminal state. "
                    "DO_NOT_STORE queues detailed output deletion immediately "
                    "while preserving the minimal permanent evidence receipt "
                    "and aggregate run record."
                ),
                max_length=32,
            ),
        ),
    ]
