# Generated by Django 6.0.3 on 2026-03-26 14:30

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_input_schema_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="is_tombstoned",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Tombstoned workflows are removed from normal product "
                    "surfaces but kept for historical run and credential continuity."
                ),
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstoned_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When the workflow entered the break-glass tombstone state."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstoned_by",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The user who initiated the break-glass tombstone flow."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tombstoned_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstone_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Human-entered reason recorded during break-glass delete."
                ),
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tombstone_workflow_definition_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Workflow definition digest captured at the time of "
                    "tombstoning."
                ),
                max_length=64,
            ),
        ),
    ]
