# Generated by Django 6.0.3 on 2026-04-01 04:21

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_workflow_tombstone_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSignalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Signal name.  Valid CEL identifier.  Used as s.<name>.', max_length=100)),
                ('source_path', models.CharField(help_text='Data path resolved against the submission payload.', max_length=500)),
                ('default_value', models.JSONField(blank=True, help_text='Fallback value when the source path resolves to nothing.', null=True)),
                ('on_missing', models.CharField(choices=[('error', 'Fail the run'), ('null', 'Inject null')], default='error', max_length=10)),
                ('data_type', models.CharField(blank=True, default='', help_text='Expected type: number, string, boolean.  Empty = infer.', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order in the signal mapping editor.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_mappings', to='workflows.workflow')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'name'), name='unique_signal_name_per_workflow')],
            },
        ),
    ]
