# Generated by Django 5.2.7 on 2025-11-11 00:25

import django.contrib.postgres.fields
import validibot.workflows.models
from django.db import migrations, models

from validibot.submissions.constants import SubmissionFileType


def set_default_file_types(apps, schema_editor):
    Workflow = apps.get_model("workflows", "Workflow")
    Workflow.objects.update(
        allowed_file_types=[SubmissionFileType.JSON],
    )


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_workflowstep_action_alter_workflowstep_validator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='allowed_file_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('binary', 'Binary'), ('UNKNOWN', 'Unknown')], max_length=32), default=validibot.workflows.models._default_workflow_file_types, help_text='Logical file types (JSON, XML, text, etc.) this workflow can accept.', size=None),
        ),
        migrations.RunPython(set_default_file_types, noop),
    ]
