# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update agent access field metadata.

    The previous (uncommitted) version of this migration renamed
    ``agent_access_enabled`` to ``anonymous_agent_access_enabled``.
    That rename has been reverted: the field stays ``agent_access_enabled``
    because it now controls MCP visibility for *all* agent types, not just
    anonymous ones.

    This migration only updates help text and choice labels to reflect
    the decoupled semantics:

    - ``agent_access_enabled`` is a simple MCP visibility toggle.
    - ``agent_billing_mode`` controls who pays, with AUTHOR_PAYS now a
      real billing mode (plan quota) rather than a dormant placeholder.
    """

    dependencies = [
        ("workflows", "0010_add_workflow_signal_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="agent_access_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Expose this workflow for agent access via MCP. "
                    "With 'Author pays' billing, only authenticated agents using "
                    "your API key can use it. With 'Agent pays (x402)', anonymous "
                    "agents can also discover and pay for access."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_billing_mode",
            field=models.CharField(
                choices=[
                    ("author_pays", "Author pays (plan quota)"),
                    ("agent_pays_x402", "Agent pays via x402 micropayment"),
                ],
                default="author_pays",
                help_text=(
                    "Who pays when an agent invokes this workflow. "
                    "AUTHOR_PAYS uses your plan quota (authenticated agents only). "
                    "AGENT_PAYS_X402 requires agents to pay per call via x402."
                ),
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_max_launches_per_hour",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Maximum agent launches per hour per wallet. "
                    "Null means use the platform default."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="agent_price_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Price per agent invocation in US cents (USDC equivalent). "
                    "Required when billing mode is AGENT_PAYS_X402."
                ),
                null=True,
            ),
        ),
    ]
