# Generated by Django 6.0.4 on 2026-05-01 06:08
#
# ADR-2026-04-27 Phase 3 Session C (task 11):
# Adds ``content_hash`` to ``WorkflowStepResource`` for the
# step-owned-file mode. Catalog references inherit their hash from
# the ``ValidatorResourceFile`` they point to, so this column stays
# empty when ``validator_resource_file_id`` is set.
#
# No backfill: ``WorkflowStepResource.save()`` recomputes the hash
# on every save, so the column populates as rows are touched. The
# drift gate sleeps until ``content_hash`` is non-empty.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0014_add_agent_public_discovery"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstepresource",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "SHA-256 of step_resource_file content. Only used "
                    "for step-owned files; catalog references look up "
                    "the hash via validator_resource_file.content_hash."
                ),
                max_length=64,
            ),
        ),
    ]
