# Generated by Django 5.2.8 on 2025-12-04 08:24

import validibot.workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_workflow_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='featured_image',
            field=models.FileField(blank=True, help_text="Optional image to represent the workflow Shown on the 'info' page.", null=True, storage=validibot.workflows.models.select_public_storage, upload_to=''),
        ),
    ]
