# Generated by Django 6.0.4 on 2026-05-02 02:29
#
# ADR-2026-04-27 Phase 4 closing housekeeping: rename
# ``Workflow.data_retention`` to ``Workflow.input_retention`` so the
# field name mirrors the existing ``Workflow.output_retention`` and
# removes the long-standing ambiguity ("data" could mean input or
# output) that caused real reasoning bugs in retention-policy code.
#
# Manually rewritten from the auto-generated ``RemoveField`` +
# ``AddField`` pair to a single ``RenameField`` so production data
# in the ``data_retention`` column is preserved through the rename.
# The auto-generator can't detect renames; interactive
# ``makemigrations`` would have prompted, but for a CI-friendly
# migration we hand-write the ``RenameField`` and add an
# ``AlterField`` for the help-text change.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0015_add_resource_content_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflow",
            old_name="data_retention",
            new_name="input_retention",
        ),
        # Refresh field options (help_text wording was updated to
        # match the new name). RenameField doesn't carry options
        # over, but we explicitly AlterField to put the new
        # help_text in place.
        migrations.AlterField(
            model_name="workflow",
            name="input_retention",
            field=models.CharField(
                choices=[
                    ("DO_NOT_STORE", "Do not store (delete after validation)"),
                    ("STORE_1_DAY", "Store for 1 day"),
                    ("STORE_7_DAYS", "Store for 7 days"),
                    ("STORE_30_DAYS", "Store for 30 days"),
                    ("STORE_PERMANENTLY", "Store permanently"),
                ],
                default="DO_NOT_STORE",
                help_text=(
                    "How long to keep user-submitted input files after "
                    "validation completes. DO_NOT_STORE deletes the "
                    "submission immediately after successful completion. "
                    "The submission record is preserved for audit."
                ),
                max_length=32,
            ),
        ),
    ]
