# Generated by Django 6.0 on 2025-12-15 02:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_ephemeral_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grant is currently active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this access grant.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user who created this grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_workflow_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who has been granted access.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_grants', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow this grant provides access to.', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'workflow access grant',
                'verbose_name_plural': 'workflow access grants',
                'indexes': [models.Index(fields=['user', 'is_active'], name='workflows_w_user_id_abb030_idx'), models.Index(fields=['workflow', 'is_active'], name='workflows_w_workflo_2c234f_idx')],
                'unique_together': {('workflow', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInvite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email address of invitee (used when inviting non-users).', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for invite acceptance URL.', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite expires.')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='The invited user, if they already have an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_workflow_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='The user who sent this invite.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_workflow_invites', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow this invite grants access to.', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'workflow invite',
                'verbose_name_plural': 'workflow invites',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['token'], name='workflows_w_token_60e089_idx'), models.Index(fields=['invitee_email', 'status'], name='workflows_w_invitee_b5ac80_idx'), models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_b2ac73_idx')],
            },
        ),
    ]
