# Generated by Django 6.0.4 on 2026-05-03 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0003_wipe_pre_encryption_authenticators'),
        ('workflows', '0016_rename_data_retention_to_input_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('agent_public_discovery', False), ('agent_access_enabled', True), _connector='OR'), name='ck_workflow_public_discovery_requires_agent_access'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_billing_mode', 'AGENT_PAYS_X402'), _negated=True), ('agent_price_cents__gt', 0), _connector='OR'), name='ck_workflow_x402_requires_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_billing_mode', 'AGENT_PAYS_X402'), _negated=True), ('input_retention', 'DO_NOT_STORE'), _connector='OR'), name='ck_workflow_x402_requires_do_not_store_retention'),
        ),
    ]
