# Generated by Django 6.0.4 on 2026-05-04 00:03

from django.conf import settings
from django.db import migrations, models


def _normalize_pre_constraint_rows(apps, schema_editor):
    """Suppress public-x402 claims on rows the new constraints would reject.

    Mirrors the normalization in 0017 — see that migration for the
    full rationale.  This pass handles three invariants:

    1. ``AGENT_PAYS_X402`` rows with NULL or non-positive
       ``agent_price_cents`` (re-applied here as a safety step —
       see "Why we re-run the price normalization" below).
    2. Public discovery requires x402 billing.
    3. Public discovery requires the row is alive (not archived /
       tombstoned).

    The strategy is the same throughout: when a row is in a
    contradictory state, withdraw the public claim rather than
    mutate the operator's lifecycle / billing choices.

    Idempotent: a deployment with clean data updates 0 rows.

    Why we re-run the price normalization
    =====================================

    The 0017 migration was modified after-the-fact to prepend the
    same x402-price normalization to its operations, but Django
    does not re-run a migration that has already been applied.  A
    deployment that applied the *original* 0017 (before the
    normalization was added) will still have legacy
    ``AGENT_PAYS_X402`` rows with NULL prices — the old
    ``ck_workflow_x402_requires_positive_price`` constraint
    permitted them via the SQL UNKNOWN-on-NULL semantics.

    0018 below ``RemoveConstraint``s the old check and adds a
    stricter ``IS NOT NULL AND > 0`` version, which would fail on
    those legacy rows.  Re-running the price normalization here
    repairs the legacy state before the stricter constraint
    materializes — closing the upgrade-path edge case the reviewer
    flagged.
    """
    Workflow = apps.get_model("workflows", "Workflow")

    # x402 billing with non-positive or NULL price — safety repair
    # for deployments that applied the original 0017 before the
    # data-migration prefix landed.  Idempotent: 0 rows on a clean
    # DB or one that already ran the new 0017 normalization.
    Workflow.objects.filter(
        agent_billing_mode="AGENT_PAYS_X402",
    ).filter(
        models.Q(agent_price_cents__lte=0) | models.Q(agent_price_cents__isnull=True),
    ).update(
        agent_billing_mode="AUTHOR_PAYS",
        agent_public_discovery=False,
    )

    # Public discovery without x402 billing — withdraw the public
    # claim.  The new ``ck_workflow_public_discovery_requires_x402_billing``
    # constraint forbids this combination.
    Workflow.objects.filter(
        agent_public_discovery=True,
    ).exclude(
        agent_billing_mode="AGENT_PAYS_X402",
    ).update(agent_public_discovery=False)

    # Public discovery on archived or tombstoned rows — withdraw
    # both agent claims.  The new
    # ``ck_workflow_public_discovery_requires_alive_row`` constraint
    # forbids this combination.  Mirror what ``Workflow.tombstone()``
    # does on the harder removal path.
    Workflow.objects.filter(
        agent_public_discovery=True,
    ).filter(
        models.Q(is_archived=True) | models.Q(is_tombstoned=True),
    ).update(
        agent_public_discovery=False,
        agent_access_enabled=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0003_wipe_pre_encryption_authenticators'),
        ('workflows', '0017_add_workflow_x402_check_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Data normalization MUST run before the AddConstraint
        # operations below — see 0017 for rationale.
        migrations.RunPython(
            _normalize_pre_constraint_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='workflow',
            name='ck_workflow_x402_requires_positive_price',
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_billing_mode', 'AGENT_PAYS_X402'), _negated=True), models.Q(('agent_price_cents__isnull', False), ('agent_price_cents__gt', 0)), _connector='OR'), name='ck_workflow_x402_requires_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('agent_public_discovery', False), ('agent_billing_mode', 'AGENT_PAYS_X402'), _connector='OR'), name='ck_workflow_public_discovery_requires_x402_billing'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('agent_public_discovery', False), models.Q(models.Q(('is_archived', False), ('is_archived__isnull', True), _connector='OR'), models.Q(('is_tombstoned', False), ('is_tombstoned__isnull', True), _connector='OR')), _connector='OR'), name='ck_workflow_public_discovery_requires_alive_row'),
        ),
    ]
