# Generated by Django 6.0.5 on 2026-05-08 00:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_kind_groups'),
        ('workflows', '0018_add_workflow_publish_invariants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGuestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this org-wide guest access is currently active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this access grant.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user who created this grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_org_guest_accesses', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='The organization this guest can access workflows in.', on_delete=django.db.models.deletion.CASCADE, related_name='guest_accesses', to='users.organization')),
                ('user', models.ForeignKey(help_text='The user who has been granted org-wide guest access.', on_delete=django.db.models.deletion.CASCADE, related_name='org_guest_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization guest access',
                'verbose_name_plural': 'organization guest accesses',
                'indexes': [models.Index(fields=['user', 'is_active'], name='workflows_o_user_id_d57834_idx'), models.Index(fields=['org', 'is_active'], name='workflows_o_org_id_12fcc6_idx')],
                'unique_together': {('user', 'org')},
            },
        ),
    ]
