# Generated by Django 6.0 on 2026-01-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_alter_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='data_retention',
            field=models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_10_DAYS', 'Store for 10 days'), ('STORE_30_DAYS', 'Store for 30 days')], default='DO_NOT_STORE', help_text='How long to keep submission data after validation completes. DO_NOT_STORE queues deletion shortly after run completion.', max_length=32),
        ),
    ]
