# Generated by Django 6.0 on 2026-01-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_workflow_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='make_info_page_public',
            field=models.BooleanField(default=False, help_text="Allows non-logged in users to see the workflow's info page."),
        ),
    ]
