# Generated by Django 6.0 on 2026-01-07 00:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
        ('workflows', '0022_alter_workflow_make_info_page_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(blank=True, help_text='Email address of invitee (used when inviting non-users).', max_length=254)),
                ('scope', models.CharField(choices=[('ALL', 'All workflows in org'), ('SELECTED', 'Selected workflows')], default='SELECTED', help_text='Whether to grant access to all current workflows or a selection.', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for invite acceptance URL.', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite expires.')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='The invited user, if they already have an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_guest_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='The user who sent this invite.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_guest_invites', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='The organization this invite is for.', on_delete=django.db.models.deletion.CASCADE, related_name='guest_invites', to='users.organization')),
                ('workflows', models.ManyToManyField(blank=True, help_text='Workflows to grant access to (used when scope=SELECTED).', related_name='guest_invites', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'guest invite',
                'verbose_name_plural': 'guest invites',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['token'], name='workflows_g_token_45419d_idx'), models.Index(fields=['invitee_email', 'status'], name='workflows_g_invitee_cfcd07_idx'), models.Index(fields=['org', 'status'], name='workflows_g_org_id_25d889_idx')],
            },
        ),
    ]
