# Generated by Django 6.0 on 2026-01-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_guest_invite_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='show_success_messages',
            field=models.BooleanField(default=False, help_text='When enabled, assertions display their success message when they pass. If an assertion has no success message defined, a default is generated.'),
        ),
    ]
