# Generated by Django 6.0 on 2026-01-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_workflowstep_show_success_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='success_message',
            field=models.TextField(blank=True, default='', help_text='Custom message displayed when validation succeeds. Leave blank for the default message.'),
        ),
    ]
