# Generated by Django 6.0 on 2026-01-28 21:39

from django.db import migrations, models


def migrate_retention_values(apps, schema_editor):
    """
    Convert old retention values to new values.

    Old values:
        - DO_NOT_STORE -> DO_NOT_STORE (unchanged)
        - STORE_10_DAYS -> STORE_7_DAYS (closest new option)
        - STORE_30_DAYS -> STORE_30_DAYS (unchanged)
    """
    Workflow = apps.get_model("workflows", "Workflow")
    Workflow.objects.filter(data_retention="STORE_10_DAYS").update(
        data_retention="STORE_7_DAYS"
    )


def reverse_migrate_retention_values(apps, schema_editor):
    """Reverse migration: convert STORE_7_DAYS back to STORE_10_DAYS."""
    Workflow = apps.get_model("workflows", "Workflow")
    Workflow.objects.filter(data_retention="STORE_7_DAYS").update(
        data_retention="STORE_10_DAYS"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_workflow_success_message'),
    ]

    operations = [
        # First, convert old values to new values
        migrations.RunPython(
            migrate_retention_values,
            reverse_migrate_retention_values,
        ),
        # Then add the new field and alter the choices
        migrations.AddField(
            model_name='workflow',
            name='output_retention',
            field=models.CharField(choices=[('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_90_DAYS', 'Store for 90 days'), ('STORE_1_YEAR', 'Store for 1 year'), ('STORE_PERMANENTLY', 'Store permanently')], default='STORE_30_DAYS', help_text='How long to keep validation outputs (results, artifacts, findings) after validation completes. Users need time to download results, so immediate deletion is not an option.', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='data_retention',
            field=models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_1_DAY', 'Store for 1 day'), ('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_PERMANENTLY', 'Store permanently')], default='DO_NOT_STORE', help_text='How long to keep user-submitted files after validation completes. DO_NOT_STORE deletes the submission immediately after successful completion. The submission record is preserved for audit.', max_length=32),
        ),
    ]
