# Generated by Django 6.0.6 on 2026-06-27 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0005_organization_allow_authors_to_adjust_access_and_more'),
        ('workflows', '0028_guard_submission_reserved_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflow',
            name='ck_workflow_public_discovery_requires_agent_access',
        ),
        migrations.RemoveConstraint(
            model_name='workflow',
            name='ck_workflow_public_discovery_requires_x402_billing',
        ),
        migrations.RemoveConstraint(
            model_name='workflow',
            name='ck_workflow_public_discovery_requires_alive_row',
        ),
        migrations.AddField(
            model_name='workflow',
            name='mcp_enabled',
            field=models.BooleanField(default=False, help_text="Allow authenticated AI agents to run this workflow via MCP, on behalf of a user who already has identity access through 'workflow_visibility'. Billed to that user's plan quota. Independent of x402 paid access."),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private — only you and people you invite'), ('ORG', 'Your organization'), ('ALL_USERS', 'All Validibot users')], default='ORG', help_text='Who, by Validibot identity, may run this workflow for free: PRIVATE (you and people you invite), ORG (your organization — the default), or ALL_USERS (any Validibot user). Capped by the organization ceiling. Independent of x402 paid access.', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='x402_enabled',
            field=models.BooleanField(default=False, help_text="Publish this workflow for PAID, ANONYMOUS access via x402: anyone on the internet who pays the per-call price can run it, regardless of 'workflow_visibility'. Automatically bills via x402 and requires a price and 'Do not store' retention."),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('x402_enabled', False), ('agent_billing_mode', 'AGENT_PAYS_X402'), _connector='OR'), name='ck_workflow_x402_enabled_requires_x402_billing'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('x402_enabled', False), models.Q(models.Q(('is_archived', False), ('is_archived__isnull', True), _connector='OR'), models.Q(('is_tombstoned', False), ('is_tombstoned__isnull', True), _connector='OR')), _connector='OR'), name='ck_workflow_x402_enabled_requires_alive_row'),
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='agent_access_enabled',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='agent_public_discovery',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_public',
        ),
    ]
