# Generated by Django 6.0.6 on 2026-06-30 00:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_remove_workflow_ck_workflow_public_discovery_requires_agent_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Constant name.  Valid CEL identifier.  Used as c.<name>.', max_length=100)),
                ('value', models.JSONField(help_text='The literal value.  NUMBER is stored as a canonical decimal string; LIST/OBJECT as JSON; STRING/BOOLEAN directly.')),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('LIST', 'List'), ('OBJECT', 'Object')], help_text='Explicit value type (required; no inference).', max_length=20)),
                ('description', models.CharField(blank=True, default='', help_text="Optional human note (e.g. 'agreed €/kWh per the 2026 contract').", max_length=500)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order in the constants editor.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constants', to='workflows.workflow')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'name'), name='unique_constant_name_per_workflow')],
            },
        ),
    ]
