# Generated by Django 6.0.6 on 2026-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_workflowconstant'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='display_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
