# Generated by Django 6.0.7 on 2026-07-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_split_step_config_display_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_key',
            field=models.SlugField(blank=True, default='', help_text='Stable identifier for this step within the workflow. Used to reference output data from this step in downstream assertions (e.g., steps.simulation.output.site_eui_kwh_m2). Auto-generated from the step name on creation. Immutable once set.', max_length=100),
        ),
    ]
