# Generated by Django 5.1.11 on 2025-08-26 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('submission.created', 'Submission Created'), ('workflow.created', 'Workflow Created'), ('workflow.updated', 'Workflow Updated'), ('workflow.deleted', 'Workflow Deleted'), ('run.created', 'Run Created'), ('run.started', 'Run Started'), ('run.succeeded', 'Run Succeeded'), ('run.failed', 'Run Failed'), ('run.canceled', 'Run Canceled'), ('run.timed_out', 'Run Timed Out'), ('runstep.started', 'Run Step Started'), ('runstep.passed', 'Run Step Passed'), ('runstep.failed', 'Run Step Failed'), ('runstep.skipped', 'Run Step Skipped'), ('ruleset.created', 'Ruleset Created'), ('ruleset.updated', 'Ruleset Updated'), ('validator.created', 'Validator Created'), ('validator.updated', 'Validator Updated'), ('check_suite.requested', 'GitHub Check Suite Requested'), ('check_suite.completed', 'GitHub Check Suite Completed')], max_length=32), blank=True, default=list, help_text='Subset of official event types to deliver.', size=None),
        ),
    ]
