# Generated by Django 5.2.6 on 2025-09-18 01:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('submission.created', 'Submission Created'), ('workflow.created', 'Workflow Created'), ('workflow.updated', 'Workflow Updated'), ('workflow.deleted', 'Workflow Deleted'), ('validation_run.created', 'Run Created'), ('validation_run.started', 'Run Started'), ('validation_run.succeeded', 'Run Succeeded'), ('validation_run.failed', 'Run Failed'), ('validation_run.canceled', 'Run Canceled'), ('validation_run.timed_out', 'Run Timed Out'), ('validation_run_step.started', 'Run Step Started'), ('validation_run_step.passed', 'Run Step Passed'), ('validation_run_step.failed', 'Run Step Failed'), ('validation_run_step.skipped', 'Run Step Skipped'), ('ruleset.created', 'Ruleset Created'), ('ruleset.updated', 'Ruleset Updated'), ('validator.created', 'Validator Created'), ('validator.updated', 'Validator Updated'), ('check_suite.requested', 'GitHub Check Suite Requested'), ('check_suite.completed', 'GitHub Check Suite Completed')], max_length=32), blank=True, default=list, help_text='Subset of official event types to deliver.', size=None),
        ),
    ]
