# Generated by Django 5.1.11 on 2025-08-22 02:46

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_organization_user_current_org_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the project, e.g. 'My Project'", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the project, used in URLs.')),
                ('org', models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'slug'], name='projects_pr_org_id_527094_idx')],
                'unique_together': {('org', 'slug')},
            },
        ),
    ]
