# Generated by Django 5.1.11 on 2025-09-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'slug'], name='projects_pr_org_id_527094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('org', 'slug')},
        ),
    ]
