# Generated by Django 5.1.11 on 2025-08-22 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0002_organization_user_current_org_membership'),
        ('validations', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='latest_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='validations.validationrun'),
        ),
        migrations.AddField(
            model_name='submission',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow *version* to run.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='workflows.workflow'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org', 'project', 'workflow', 'created'], name='documents_s_org_id_68ff3d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org', 'created'], name='documents_s_org_id_33a9d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref', ''), _negated=True), fields=('org', 'client_ref'), name='uniq_submission_org_client_ref_nonempty'),
        ),
    ]
