# Generated by Django 5.1.11 on 2025-09-08 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('submissions', '0003_remove_submission_submission_content_present_and_more'),
        ('users', '0001_initial'),
        ('validations', '0003_alter_validationsteprun_unique_together'),
        ('workflows', '0002_alter_workflow_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='submission_content_present',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='submission_content_not_both',
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_type',
            field=models.CharField(choices=[('application/json', 'JSON'), ('application/xml', 'XML'), ('text/plain', 'Plain Text'), ('text/x-idf', 'EnergyPlus IDF File'), ('UNKNOWN', 'Unknown')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), ('input_file__gt', ''), _connector='OR'), name='submission_content_present'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), ('input_file__gt', ''), _negated=True), name='submission_content_not_both'),
        ),
    ]
