# Generated by Django 5.1.11 on 2025-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_submission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='requested_by',
            field=models.CharField(blank=True, choices=[('API', 'API'), ('UI', 'UI'), ('GITHUB_APP', 'GitHub App')], default='', max_length=32),
        ),
    ]
