# Generated by Django 5.2.6 on 2025-09-18 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('submissions', '0004_remove_submission_submission_content_present_and_more'),
        ('users', '0002_alter_membership_user'),
        ('validations', '0009_alter_validationrun_error'),
        ('workflows', '0003_alter_workflow_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='submission_content_present',
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='submission_content_not_both',
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), models.Q(('input_file__isnull', False), models.Q(('input_file', ''), _negated=True)), _connector='OR'), name='submission_content_present'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), ('input_file__isnull', False), models.Q(('input_file', ''), _negated=True), _negated=True), name='submission_content_not_both'),
        ),
    ]
