# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_organization_options_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('max_submissions_per_day', models.IntegerField(default=100)),
                ('max_run_minutes_per_day', models.IntegerField(default=60)),
                ('artifact_retention_days', models.IntegerField(default=7)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('submissions', models.IntegerField(default=0)),
                ('run_minutes', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'date'], name='billing_usa_org_id_cada85_idx')],
                'unique_together': {('org', 'date')},
            },
        ),
    ]
