# Generated by Django 5.1.11 on 2025-09-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquota',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='users.organization'),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='usagecounter',
            index=models.Index(fields=['org', 'date'], name='billing_usa_org_id_cada85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagecounter',
            unique_together={('org', 'date')},
        ),
    ]
