# Generated by Django 5.1.11 on 2025-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
