# Generated by Django 5.1.11 on 2025-09-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_remove_membership_role_membershiprole_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_role_access', to='users.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='workflows.workflow')),
            ],
            options={
                'indexes': [models.Index(fields=['workflow', 'role'], name='workflows_w_workflo_1d18f8_idx')],
                'unique_together': {('workflow', 'role')},
            },
        ),
    ]
