# Generated by Django 5.1.11 on 2025-09-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
