# Generated by Django 5.1.11 on 2025-08-22 02:46

import django_extensions.db.fields
import roscoe.documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(help_text='The file to validate, e.g. IDF, JSON, XML, etc.', upload_to=roscoe.documents.models.submission_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.CharField(blank=True, choices=[('api', 'API'), ('ui', 'UI'), ('github_app', 'GitHub App')], default='', max_length=32)),
                ('client_ref', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
