# Generated by Django 5.1.11 on 2025-08-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional descriptive name.', max_length=256),
        ),
    ]
