# Generated by Django 5.1.11 on 2025-08-26 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('projects', '0001_initial'),
        ('users', '0002_organization_user_current_org_membership'),
        ('validations', '0002_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validator',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='validationrun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_run_times_valid'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('run', 'step_order'), name='uq_step_run_run_order'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('run', 'step'), name='uq_step_run_run_step'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ck_step_run_times_valid'),
        ),
        migrations.AddConstraint(
            model_name='validator',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='uq_validator_slug_version'),
        ),
    ]
