# Generated by Django 5.1.11 on 2025-09-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validationsteprun',
            unique_together=set(),
        ),
    ]
