# Generated by Django 5.1.11 on 2025-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_alter_validator_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional longer description of the validator.'),
        ),
    ]
