# Generated by Django 5.1.11 on 2025-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_remove_ruleset_uq_ruleset_org_type_name_version_and_more'),
        ('workflows', '0003_alter_workflow_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validationsteprun',
            name='uq_step_run_run_order',
        ),
        migrations.RemoveIndex(
            model_name='validationsteprun',
            name='validations_run_id_4865bd_idx',
        ),
        migrations.RenameField(
            model_name='validationsteprun',
            old_name='run',
            new_name='validation_run',
        ),
        migrations.RenameField(
            model_name='validationsteprun',
            old_name='step',
            new_name='workflow_step',
        ),
        migrations.AddIndex(
            model_name='validationsteprun',
            index=models.Index(fields=['validation_run', 'status'], name='validations_validat_1b7c62_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'step_order'), name='uq_step_run_run_order'),
        ),
    ]
