# Generated by Django 5.1.11 on 2025-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_validator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='type',
            field=models.CharField(choices=[('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules')], help_text="Type of validation ruleset, e.g. 'json_schema', 'xml_schema'", max_length=40),
        ),
        migrations.AlterField(
            model_name='validationfinding',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('TIMED_OUT', 'Timed Out')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='validationsteprun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='validator',
            name='type',
            field=models.CharField(choices=[('JSON_SCHEMA', 'JSON Schema'), ('XML_SCHEMA', 'XML Schema'), ('ENERGYPLUS', 'EnergyPlus'), ('CUSTOM_RULES', 'Custom Rules')], max_length=40),
        ),
    ]
