# Generated by Django 5.1.11 on 2025-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0005_remove_validationsteprun_uq_step_run_run_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='validationfinding',
            name='validations_run_id_36eb2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='validationfinding',
            name='validations_run_id_b2c47e_idx',
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['step_run', 'severity'], name='validations_step_ru_a534f9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['step_run', 'code'], name='validations_step_ru_db8e9d_idx'),
        ),
    ]
