# Generated by Django 5.1.11 on 2025-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membership_user'),
        ('validations', '0006_remove_validationfinding_validations_run_id_36eb2a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artifact',
            name='validations_run_id_ddb5c3_idx',
        ),
        migrations.RenameField(
            model_name='artifact',
            old_name='run',
            new_name='validation_run',
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['validation_run', 'created'], name='validations_validat_517e90_idx'),
        ),
    ]
