# Generated by Django 5.1.11 on 2025-09-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0007_remove_artifact_validations_run_id_ddb5c3_idx_and_more'),
        ('workflows', '0003_alter_workflow_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validationsteprun',
            name='uq_step_run_run_step',
        ),
        migrations.AddConstraint(
            model_name='validationsteprun',
            constraint=models.UniqueConstraint(fields=('validation_run', 'workflow_step'), name='uq_step_run_run_step'),
        ),
    ]
