# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_alter_organization_options_user_avatar_user_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('extra_data', models.JSONField(blank=True, help_text='Optional additional data related to the event.', null=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('BUTTON_CLICK', 'Button Click'), ('FORM_SUBMIT', 'Form Submit'), ('FILE_DOWNLOAD', 'File Download'), ('CUSTOM_EVENT', 'Custom Event'), ('APP_EVENT', 'Application Event')], max_length=100)),
                ('app_event_type', models.CharField(choices=[('submission.created', 'Submission Created'), ('workflow.created', 'Workflow Created'), ('workflow.updated', 'Workflow Updated'), ('workflow.deleted', 'Workflow Deleted'), ('validation_run.created', 'Run Created'), ('validation_run.started', 'Run Started'), ('validation_run.succeeded', 'Run Succeeded'), ('validation_run.failed', 'Run Failed'), ('validation_run.canceled', 'Run Canceled'), ('validation_run.timed_out', 'Run Timed Out'), ('validation_run_step.started', 'Run Step Started'), ('validation_run_step.passed', 'Run Step Passed'), ('validation_run_step.failed', 'Run Step Failed'), ('validation_run_step.skipped', 'Run Step Skipped'), ('ruleset.created', 'Ruleset Created'), ('ruleset.updated', 'Ruleset Updated'), ('validator.created', 'Validator Created'), ('validator.updated', 'Validator Updated'), ('check_suite.requested', 'GitHub Check Suite Requested'), ('check_suite.completed', 'GitHub Check Suite Completed'), ('user.logged_in', 'User Logged In'), ('user.logged_out', 'User Logged Out')], default='', help_text='Specific application event identifier when type is APP_EVENT.', max_length=100)),
                ('org', models.ForeignKey(blank=True, help_text='The organization this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='users.organization')),
                ('project', models.ForeignKey(blank=True, help_text='The project this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'event_type'], name='tracking_tr_project_af103e_idx')],
            },
        ),
    ]
