# Generated by Django 5.2.7 on 2025-10-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='app_event_type',
            field=models.CharField(choices=[('submission.created', 'Submission Created'), ('workflow.created', 'Workflow Created'), ('workflow.updated', 'Workflow Updated'), ('workflow.deleted', 'Workflow Deleted'), ('validation_run.created', 'Run Created'), ('validation_run.started', 'Run Started'), ('validation_run.succeeded', 'Run Succeeded'), ('validation_run.failed', 'Run Failed'), ('validation_run.canceled', 'Run Canceled'), ('validation_run.timed_out', 'Run Timed Out'), ('validation_run_step.started', 'Run Step Started'), ('validation_run_step.passed', 'Run Step Passed'), ('validation_run_step.failed', 'Run Step Failed'), ('validation_run_step.skipped', 'Run Step Skipped'), ('ruleset.created', 'Ruleset Created'), ('ruleset.updated', 'Ruleset Updated'), ('validator.created', 'Validator Created'), ('validator.updated', 'Validator Updated'), ('check_suite.requested', 'GitHub Check Suite Requested'), ('check_suite.completed', 'GitHub Check Suite Completed'), ('user.logged_in', 'User Logged In'), ('user.logged_out', 'User Logged Out')], default='', help_text='Specific application event identifier when type is APP_EVENT.', max_length=100),
        ),
    ]
