# Generated by Django 5.2.7 on 2025-10-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='org',
            field=models.ForeignKey(blank=True, help_text='The organization this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='users.organization'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='projects.project'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['project', 'event_type'], name='tracking_tr_project_af103e_idx'),
        ),
    ]
