# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.utils.timezone
import model_utils.fields
import uuid
import validibot.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the initial purge failure occurred.')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='When the last retry attempt was made.', null=True)),
                ('next_retry_at', models.DateTimeField(db_index=True, help_text='When to attempt the next retry.')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Error message from the last failed attempt.')),
            ],
            options={
                'verbose_name_plural': 'Purge retries',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Optional descriptive name.', max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('input_file', models.FileField(blank=True, help_text='The file to validate, e.g. IDF, JSON, XML, etc.', null=True, upload_to=validibot.submissions.models.submission_input_file_upload_to)),
                ('file_type', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('yaml', 'YAML'), ('binary', 'Binary'), ('UNKNOWN', 'Unknown')], max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retention_policy', models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_1_DAY', 'Store for 1 day'), ('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_PERMANENTLY', 'Store permanently')], default='DO_NOT_STORE', help_text="Snapshot of workflow's retention policy at submission time.", max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When content should be purged (null = already purged or DO_NOT_STORE).', null=True)),
                ('content_purged_at', models.DateTimeField(blank=True, help_text='When content was purged (for audit trail).', null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
