# Generated by Django 6.0.7 on 2026-07-16 05:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import validibot.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_initial"),
        ("workflows", "0006_add_description_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionInputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "port_key",
                    models.SlugField(
                        help_text="Artifact input port this submitted file satisfies.",
                        max_length=255,
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True,
                        help_text="Submitted file for a workflow artifact input port.",
                        null=True,
                        upload_to=validibot.submissions.models.submission_port_file_upload_to,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "file_purged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this port file was purged for retention.",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="submissions.submission",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workflow step whose artifact port consumes this file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workflows.workflowstep",
                    ),
                ),
            ],
            options={
                "ordering": ["submission_id", "workflow_step_id", "port_key"],
                "indexes": [
                    models.Index(
                        fields=["submission", "workflow_step", "port_key"],
                        name="submissions_submiss_6ed746_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "workflow_step", "port_key"),
                        name="uniq_submission_step_port_file",
                    )
                ],
            },
        ),
    ]
