# Generated by Django 6.0 on 2025-12-10 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('submissions', '0003_alter_submission_file_type'),
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
        ('validations', '0041_add_error_category'),
        ('workflows', '0016_ephemeral_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='submission_content_present',
        ),
        migrations.AddField(
            model_name='submission',
            name='content_purged_at',
            field=models.DateTimeField(blank=True, help_text='When content was purged (for audit trail).', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When content should be purged (null = already purged or DO_NOT_STORE).', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='retention_policy',
            field=models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_10_DAYS', 'Store for 10 days'), ('STORE_30_DAYS', 'Store for 30 days')], default='DO_NOT_STORE', help_text="Snapshot of workflow's retention policy at submission time.", max_length=32),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content_purged_at__isnull', False), ('content__gt', ''), models.Q(('input_file__isnull', False), models.Q(('input_file', ''), _negated=True)), _connector='OR'), name='submission_content_present'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('content_purged_at__isnull', True), models.Q(('content', ''), ('input_file', '')), _connector='OR'), name='submission_purged_content_cleared'),
        ),
    ]
