# Generated by Django 6.0.7 on 2026-07-27 23:06

from django.db import migrations
from django.db import models


def deduplicate_purge_retries(apps, schema_editor):
    """Merge legacy duplicate work rows before enforcing one target row."""

    del schema_editor
    PurgeRetry = apps.get_model("submissions", "PurgeRetry")
    duplicate_submission_ids = (
        PurgeRetry.objects.values("submission_id")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
        .values_list("submission_id", flat=True)
    )
    for submission_id in duplicate_submission_ids.iterator():
        rows = list(
            PurgeRetry.objects.filter(submission_id=submission_id).order_by(
                "next_retry_at",
                "pk",
            ),
        )
        keeper = rows[0]
        most_attempted = max(rows, key=lambda row: row.attempt_count)
        keeper.attempt_count = most_attempted.attempt_count
        keeper.last_attempt_at = most_attempted.last_attempt_at
        keeper.last_error = most_attempted.last_error
        keeper.save(
            update_fields=["attempt_count", "last_attempt_at", "last_error"],
        )
        PurgeRetry.objects.filter(pk__in=[row.pk for row in rows[1:]]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_current_schema"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_purge_retries,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="purgeretry",
            constraint=models.UniqueConstraint(
                fields=("submission",), name="uq_purge_retry_submission"
            ),
        ),
    ]
