# Generated by Django 6.0 on 2025-12-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_ephemeral_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the initial purge failure occurred.')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='When the last retry attempt was made.', null=True)),
                ('next_retry_at', models.DateTimeField(db_index=True, help_text='When to attempt the next retry.')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Error message from the last failed attempt.')),
                ('submission', models.ForeignKey(help_text='Submission that failed to purge.', on_delete=django.db.models.deletion.CASCADE, related_name='purge_retries', to='submissions.submission')),
            ],
            options={
                'verbose_name_plural': 'Purge retries',
                'indexes': [models.Index(fields=['next_retry_at', 'attempt_count'], name='submissions_next_re_8a75e8_idx')],
            },
        ),
    ]
