# Generated by Django 6.0 on 2026-01-28 21:39

from django.db import migrations, models


def migrate_retention_values(apps, schema_editor):
    """
    Convert old retention values to new values.

    Old values:
        - DO_NOT_STORE -> DO_NOT_STORE (unchanged)
        - STORE_10_DAYS -> STORE_7_DAYS (closest new option)
        - STORE_30_DAYS -> STORE_30_DAYS (unchanged)
    """
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.filter(retention_policy="STORE_10_DAYS").update(
        retention_policy="STORE_7_DAYS"
    )


def reverse_migrate_retention_values(apps, schema_editor):
    """Reverse migration: convert STORE_7_DAYS back to STORE_10_DAYS."""
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.filter(retention_policy="STORE_7_DAYS").update(
        retention_policy="STORE_10_DAYS"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_add_purge_retry'),
    ]

    operations = [
        # First, convert old values to new values
        migrations.RunPython(
            migrate_retention_values,
            reverse_migrate_retention_values,
        ),
        # Then alter the choices
        migrations.AlterField(
            model_name='submission',
            name='retention_policy',
            field=models.CharField(choices=[('DO_NOT_STORE', 'Do not store (delete after validation)'), ('STORE_1_DAY', 'Store for 1 day'), ('STORE_7_DAYS', 'Store for 7 days'), ('STORE_30_DAYS', 'Store for 30 days'), ('STORE_PERMANENTLY', 'Store permanently')], default='DO_NOT_STORE', help_text="Snapshot of workflow's retention policy at submission time.", max_length=32),
        ),
    ]
