# Generated by Django 6.0 on 2025-12-10 22:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('users', '0010_alter_pendinginvite_invitee_email_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('credits', models.IntegerField(help_text='Number of credits purchased.')),
                ('amount_cents', models.IntegerField(help_text='Amount charged in cents.')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for this purchase.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('TEAM', 'Team'), ('ENTERPRISE', 'Enterprise')], help_text='Unique plan identifier, also used as PK.', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the plan.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Marketing description shown on pricing page.')),
                ('basic_launches_limit', models.IntegerField(blank=True, help_text='Monthly basic workflow launches. Null = unlimited.', null=True)),
                ('included_credits', models.IntegerField(default=0, help_text='Credits included per billing period for advanced workflows.')),
                ('max_workflows', models.IntegerField(blank=True, help_text='Maximum number of workflows. Null = unlimited.', null=True)),
                ('max_custom_validators', models.IntegerField(blank=True, help_text='Maximum custom validators. Null = unlimited.', null=True)),
                ('max_seats', models.IntegerField(blank=True, help_text='Maximum team members. Null = unlimited.', null=True)),
                ('max_payload_mb', models.IntegerField(default=5, help_text='Maximum upload file size in MB.')),
                ('has_integrations', models.BooleanField(default=False, help_text='Whether third-party integrations are enabled.')),
                ('has_audit_logs', models.BooleanField(default=False, help_text='Whether audit log access is enabled.')),
                ('monthly_price_cents', models.IntegerField(default=0, help_text='Monthly price in cents for display. 0 = contact sales.')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for subscription checkout.', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which plans appear on pricing page.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('TRIALING', 'Trial'), ('TRIAL_EXPIRED', 'Trial Expired'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended')], default='TRIALING', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, help_text='When the trial began.', null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial expires. Checked by middleware.', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID (cus_xxx).', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID (sub_xxx).', max_length=255)),
                ('included_credits_remaining', models.IntegerField(default=0, help_text="Remaining credits from plan's monthly allotment.")),
                ('purchased_credits_balance', models.IntegerField(default=0, help_text='Credits purchased via credit packs.')),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of current billing period.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period.', null=True)),
                ('custom_basic_launches_limit', models.IntegerField(blank=True, help_text='Enterprise override for basic_launches_limit.', null=True)),
                ('custom_included_credits', models.IntegerField(blank=True, help_text='Enterprise override for included_credits.', null=True)),
                ('custom_max_seats', models.IntegerField(blank=True, help_text='Enterprise override for max_seats.', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orgquota',
            name='org',
        ),
        migrations.AlterUniqueTogether(
            name='usagecounter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='advanced_launches',
            field=models.IntegerField(default=0, help_text='Number of advanced workflow launches this period.'),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='basic_launches',
            field=models.IntegerField(default=0, help_text='Number of basic workflow launches this period.'),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='credits_consumed',
            field=models.IntegerField(default=0, help_text='Total credits consumed this period.'),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of billing period (for monthly tracking).', null=True),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of billing period (for monthly tracking).', null=True),
        ),
        migrations.AlterField(
            model_name='usagecounter',
            name='date',
            field=models.DateField(blank=True, help_text='Date for daily counters. Use period fields for monthly.', null=True),
        ),
        migrations.AddIndex(
            model_name='usagecounter',
            index=models.Index(fields=['org', 'period_start'], name='billing_usa_org_id_4cb244_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.CheckConstraint(condition=models.Q(('date__isnull', False), ('period_start__isnull', False), _connector='OR'), name='usage_counter_has_period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to='billing.subscription'),
        ),
        migrations.DeleteModel(
            name='OrgQuota',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_customer_id'], name='billing_sub_stripe__97887e_idx'),
        ),
    ]
