# Generated by Django 6.0 on 2025-12-10 22:52
"""
Data migration to seed the Plan lookup table.

Populates the three pricing tiers: Starter, Team, Enterprise.
This is the single source of truth for plan limits.
"""

from django.db import migrations


def seed_plans(apps, schema_editor):
    """
    Seed the Plan lookup table with initial pricing tiers.

    Values based on ADR-2025-11-28 pricing system design.
    """
    Plan = apps.get_model("billing", "Plan")

    Plan.objects.create(
        code="STARTER",
        name="Starter",
        description="For individuals and small teams getting started.",
        basic_launches_limit=10_000,
        included_credits=200,
        max_workflows=10,
        max_custom_validators=10,
        max_seats=2,
        max_payload_mb=5,
        has_integrations=False,
        has_audit_logs=False,
        monthly_price_cents=2900,  # $29/month
        stripe_price_id="",  # Set after creating in Stripe Dashboard
        display_order=1,
    )

    Plan.objects.create(
        code="TEAM",
        name="Team",
        description="For growing teams with advanced needs.",
        basic_launches_limit=100_000,
        included_credits=1_000,
        max_workflows=100,
        max_custom_validators=100,
        max_seats=10,
        max_payload_mb=20,
        has_integrations=True,
        has_audit_logs=True,
        monthly_price_cents=9900,  # $99/month
        stripe_price_id="",  # Set after creating in Stripe Dashboard
        display_order=2,
    )

    Plan.objects.create(
        code="ENTERPRISE",
        name="Enterprise",
        description="Custom solutions for large organizations.",
        basic_launches_limit=None,  # Unlimited
        included_credits=5_000,
        max_workflows=None,  # Unlimited
        max_custom_validators=None,  # Unlimited
        max_seats=None,  # Unlimited
        max_payload_mb=100,
        has_integrations=True,
        has_audit_logs=True,
        monthly_price_cents=0,  # Contact sales
        stripe_price_id="",  # Enterprise: manual provisioning
        display_order=3,
    )


def remove_plans(apps, schema_editor):
    """Reverse migration: remove all seeded plans."""
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(code__in=["STARTER", "TEAM", "ENTERPRISE"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_plan_subscription_models"),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]
