# Generated by Django 6.0 on 2025-12-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_seed_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='intended_plan',
            field=models.ForeignKey(blank=True, help_text='Plan user selected from pricing page (may differ from actual plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_subscriptions', to='billing.plan'),
        ),
    ]
