# Generated by Django 6.0 on 2025-12-17 22:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_intended_plan_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('TEAM', 'Team'), ('ENTERPRISE', 'Enterprise')], help_text='Unique plan identifier, also used as PK.', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('change_type', models.CharField(help_text='Type of change: upgrade, downgrade, or lateral.', max_length=20)),
                ('effective_immediately', models.BooleanField(default=True, help_text='Whether change took effect immediately or was scheduled.')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When scheduled change will take effect.', null=True)),
                ('proration_amount_cents', models.IntegerField(blank=True, help_text='Proration amount charged/credited in cents.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context for the change.')),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_to', to='billing.plan')),
                ('old_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_from', to='billing.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
