# Generated by Django 6.0 on 2025-12-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_plan_change_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Whether this plan can be selected. Unavailable plans show 'Coming Soon'."),
        ),
    ]
