# Generated by Django 6.0 on 2025-12-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_plan_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='credit_pack_price_cents',
            field=models.IntegerField(blank=True, help_text='Price in cents for a credit pack. Null = not available / negotiated.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='credit_pack_size',
            field=models.IntegerField(blank=True, help_text='Number of credits in a credit pack. Null = not available / negotiated.', null=True),
        ),
    ]
