# Generated by Django 6.0 on 2025-12-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_credit_pack_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='credit_pack_price_cents',
            field=models.IntegerField(blank=True, help_text='Price in cents for a credit pack. Null = negotiated pricing.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='credit_pack_size',
            field=models.IntegerField(blank=True, help_text='Number of credits in a credit pack. Null = not available.', null=True),
        ),
    ]
