# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simplevalidations.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_organization_options_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the project, e.g. 'My Project'", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description of the project.')),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the project, used in URLs.')),
                ('is_default', models.BooleanField(default=False, help_text='Indicates the default project for an organization.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(default=simplevalidations.projects.models.generate_random_color, help_text='Hex color used when displaying project badges (e.g. #1F883D).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a hex color code like #1F883D.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('org', models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'slug'], name='projects_pr_org_id_527094_idx'), models.Index(fields=['org', 'is_active'], name='projects_pr_org_id_0e57f6_idx'), models.Index(fields=['is_active', 'deleted_at'], name='projects_pr_is_acti_ed77ba_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='uq_project_org_single_default')],
                'unique_together': {('org', 'slug')},
            },
        ),
    ]
