# Generated by Django 5.1.11 on 2025-09-04 03:05

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the project, e.g. 'My Project'", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description of the project.')),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the project, used in URLs.')),
            ],
        ),
    ]
