# Generated by Django 5.2.7 on 2025-10-10 00:53

import django.core.validators
import django.utils.timezone
import model_utils.fields
import simplevalidations.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the project, e.g. 'My Project'", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description of the project.')),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the project, used in URLs.')),
                ('is_default', models.BooleanField(default=False, help_text='Indicates the default project for an organization.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(default=simplevalidations.projects.models.generate_random_color, help_text='Hex color used when displaying project badges (e.g. #1F883D).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a hex color code like #1F883D.', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
        ),
    ]
