# Generated by Django 5.2.7 on 2025-10-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0005_alter_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicates the default project for an organization.'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'is_active'], name='projects_pr_org_id_0e57f6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'deleted_at'], name='projects_pr_is_acti_ed77ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='uq_project_org_single_default'),
        ),
    ]
