# Generated by Django 5.2.7 on 2025-10-08

from uuid import uuid4

from django.db import migrations
from django.utils.text import slugify


def _unique_slug(model, base, prefix=""):
    from django.utils.text import slugify
    base_slug = slugify(base) or uuid4().hex[:8]
    if prefix:
        base_slug = f"{prefix}{base_slug}"
    slug = base_slug
    counter = 2
    while model.objects.filter(slug=slug).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    return slug


def forwards(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Organization = apps.get_model("users", "Organization")

    Project.objects.filter(is_active__isnull=True).update(is_active=True)

    for org in Organization.objects.filter(is_personal=True):
        default = Project.objects.filter(org=org, is_default=True).first()
        if default:
            if not default.is_active:
                default.is_active = True
                default.deleted_at = None
                default.save(update_fields=["is_active", "deleted_at"])
            continue

        name = "Default Project"
        slug = _unique_slug(Project, name, prefix="default-")
        Project.objects.create(
            org=org,
            name=name,
            description="",
            slug=slug,
            is_default=True,
            is_active=True,
        )


def backwards(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(is_default=True).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_deleted_at_project_is_active_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
