# Generated by Django 5.2.7 on 2025-10-08 03:40

import django.core.validators
from django.db import migrations, models

import simplevalidations.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_populate_default_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(
                default=simplevalidations.projects.models.generate_random_color,
                help_text='Hex color used when displaying project badges (e.g. #1F883D).',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Use a hex color code like #1F883D.',
                        regex='^#[0-9A-Fa-f]{6}$',
                    ),
                ],
            ),
        ),
    ]
