# Generated by Django 6.0.3 on 2026-03-15 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('tracking', '0002_initial'),
        ('users', '0002_organization_trial_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['org', 'created'], name='tracking_tr_org_id_44c704_idx'),
        ),
    ]
