# Generated by Django 5.2.7 on 2025-10-10 00:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_alter_organization_options_user_avatar_user_bio_and_more'),
        ('validations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Name of the workflow, e.g. 'My Workflow'", max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the workflow.', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A unique identifier for the workflow, used in URLs. (Leave blank to auto-generate from name.)')),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('is_locked', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='users.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Default project to associate with runs triggered from this workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='projects.project')),
                ('user', models.ForeignKey(help_text='The user who created this workflow.', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug', '-version'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_role_access', to='users.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='validations.ruleset')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validations.validator')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('org', 'slug', 'version'), name='uq_workflow_org_slug_version'),
        ),
        migrations.AddIndex(
            model_name='workflowroleaccess',
            index=models.Index(fields=['workflow', 'role'], name='workflows_w_workflo_1d18f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowroleaccess',
            unique_together={('workflow', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'order')},
        ),
    ]
