# Generated by Django 5.2.7 on 2025-10-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflow_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='make_info_public',
            field=models.BooleanField(default=False, help_text='Allows non-logged in users to see details of the workflow validation.'),
        ),
    ]
