# Generated by Django 5.2.6 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique identifier for the workflow, used in URLs. (Leave blank to auto-generate from name.)'),
        ),
    ]
