# Generated by Django 5.2.7 on 2025-10-08 03:30

import django.db.models.deletion
from django.db import migrations, models


def assign_default_projects(apps, schema_editor):
    Workflow = apps.get_model("workflows", "Workflow")
    Project = apps.get_model("projects", "Project")

    workflows = Workflow.objects.filter(project__isnull=True).select_related("org")
    for workflow in workflows:
        default_project = (
            Project.objects.filter(org=workflow.org, is_default=True).first()
            or Project.all_objects.filter(org=workflow.org, is_default=True).first()
        )
        if default_project:
            Workflow.objects.filter(pk=workflow.pk).update(project=default_project)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_populate_default_projects'),
        ('workflows', '0004_alter_workflow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Default project to associate with runs triggered from this workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='projects.project'),
        ),
        migrations.RunPython(assign_default_projects, migrations.RunPython.noop),
    ]
