# Generated by Django 5.2.7 on 2025-10-16 02:55

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowpublicinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowpublicinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workflowpublicinfo',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='workflowpublicinfo',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='workflowpublicinfo',
            name='show_steps',
            field=models.BooleanField(default=True, help_text='Whether to show the workflow steps on the public info page.'),
        ),
    ]
