# Generated by Django 5.2.7 on 2025-11-03 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('validations', '0003_ruleset_rules_fields'),
        ('workflows', '0008_workflowstep_display_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='actions.action'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='validations.validator'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__isnull', True), ('validator__isnull', False)), models.Q(('action__isnull', False), ('validator__isnull', True)), _connector='OR'), name='workflowstep_validator_xor_action'),
        ),
    ]
