# Generated by Django 5.2.7 on 2025-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_workflow_allowed_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='allow_meta_data',
            field=models.BooleanField(
                default=False,
                help_text='Allow users to submit meta-data along with their files for validation.',
            ),
        ),
    ]
