# Generated by Django 5.2.7 on 2025-11-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_workflow_allow_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='allow_short_description',
            field=models.BooleanField(default=False, help_text='Allow users to submit a short description along with their files for validation.'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='allow_submission_name',
            field=models.BooleanField(default=True, help_text='Allow users to submit a custom name along with their data for validation.'),
        ),
    ]
