# Generated by Django 5.2.7 on 2025-11-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_workflow_allow_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='allow_meta_data',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='allow_short_description',
        ),
        migrations.AddField(
            model_name='workflow',
            name='allow_submission_meta_data',
            field=models.BooleanField(default=False, help_text='Allow users to submit meta-data along with their data for validation.'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='allow_submission_short_description',
            field=models.BooleanField(default=False, help_text='Allow users to submit a short description along with their data for validation.'),
        ),
    ]
