# Generated by Django 6.0.2 on 2026-02-04 03:32

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_type', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('event_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('submission.created', 'Submission Created'), ('workflow.created', 'Workflow Created'), ('workflow.updated', 'Workflow Updated'), ('workflow.deleted', 'Workflow Deleted'), ('validation_run.created', 'Run Created'), ('validation_run.started', 'Run Started'), ('validation_run.succeeded', 'Run Succeeded'), ('validation_run.failed', 'Run Failed'), ('validation_run.canceled', 'Run Canceled'), ('validation_run.timed_out', 'Run Timed Out'), ('validation_run_step.started', 'Run Step Started'), ('validation_run_step.passed', 'Run Step Passed'), ('validation_run_step.failed', 'Run Step Failed'), ('validation_run_step.skipped', 'Run Step Skipped'), ('ruleset.created', 'Ruleset Created'), ('ruleset.updated', 'Ruleset Updated'), ('validator.created', 'Validator Created'), ('validator.updated', 'Validator Updated'), ('check_suite.requested', 'GitHub Check Suite Requested'), ('check_suite.completed', 'GitHub Check Suite Completed'), ('user.logged_in', 'User Logged In'), ('user.logged_out', 'User Logged Out'), ('invite.created', 'Invite Created'), ('invite.accepted', 'Invite Accepted'), ('invite.declined', 'Invite Declined')], max_length=32), blank=True, default=list, help_text='Subset of official event types to deliver.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
