name: CI

permissions:
  contents: read

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version-file: '.python-version'
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      REDIS_URL: 'redis://localhost:6379/0'
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: localhost
      PGPORT: "5432"
      PGDATABASE: postgres

    steps:
      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}" >> "$GITHUB_ENV"

      - name: Checkout Code Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version-file: '.python-version'

      - name: Install Dependencies
        run: uv sync --group dev --frozen

      - name: Audit dependencies
        run: uvx pip-audit

      - name: Check DB Migrations
        run: uv run python manage.py makemigrations --check

      - name: Run DB Migrations
        run: uv run python manage.py migrate

      - name: Test with pytest
        run: uv run pytest

      - name: Django deployment checks
        env:
          DJANGO_SETTINGS_MODULE: config.settings.production
          DJANGO_SECRET_KEY: fake-key-for-ci-only
          DJANGO_ALLOWED_HOSTS: localhost
          DEPLOYMENT_TARGET: docker_compose
        run: uv run python manage.py check --deploy
